// This file is @generated by prost-build.
/// Normalized trade tick from any exchange
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TradeTick {
    /// Timestamp in microseconds since epoch
    #[prost(int64, tag = "1")]
    pub timestamp_us: i64,
    /// Trading pair (e.g., "BTC-USDT")
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    /// Exchange name (e.g., "binance", "bybit", "kucoin")
    #[prost(string, tag = "3")]
    pub exchange: ::prost::alloc::string::String,
    /// Trade side: "buy" or "sell"
    #[prost(string, tag = "4")]
    pub side: ::prost::alloc::string::String,
    /// Price as string to preserve precision
    #[prost(string, tag = "5")]
    pub price: ::prost::alloc::string::String,
    /// Amount/quantity as string to preserve precision
    #[prost(string, tag = "6")]
    pub amount: ::prost::alloc::string::String,
    /// Exchange-specific trade ID
    #[prost(string, tag = "7")]
    pub trade_id: ::prost::alloc::string::String,
    /// Latency from exchange timestamp to receipt (milliseconds)
    #[prost(int64, tag = "8")]
    pub latency_ms: i64,
}
/// Market metric (Fear & Greed, DVOL, ETF flows, etc.)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketMetric {
    /// Timestamp in microseconds since epoch
    #[prost(int64, tag = "1")]
    pub timestamp_us: i64,
    /// Metric type (e.g., "fear_greed", "dvol_index", "etf_inflow")
    #[prost(string, tag = "2")]
    pub metric_type: ::prost::alloc::string::String,
    /// Asset symbol (e.g., "BTC", "ETH", "GLOBAL")
    #[prost(string, tag = "3")]
    pub asset: ::prost::alloc::string::String,
    /// Data source (e.g., "alternative_me", "deribit", "farside")
    #[prost(string, tag = "4")]
    pub source: ::prost::alloc::string::String,
    /// Numeric value
    #[prost(double, tag = "5")]
    pub value: f64,
    /// Optional metadata (JSON string)
    #[prost(string, tag = "6")]
    pub meta: ::prost::alloc::string::String,
}
/// UMAP projection coordinates (2D or 3D)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmapCoordinate {
    /// Timestamp in microseconds since epoch
    #[prost(int64, tag = "1")]
    pub timestamp_us: i64,
    /// Symbol this projection represents
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    /// Model ID used for projection
    #[prost(string, tag = "3")]
    pub model_id: ::prost::alloc::string::String,
    /// X coordinate
    #[prost(double, tag = "4")]
    pub x: f64,
    /// Y coordinate
    #[prost(double, tag = "5")]
    pub y: f64,
    /// Optional Z coordinate (for 3D)
    #[prost(double, optional, tag = "6")]
    pub z: ::core::option::Option<f64>,
    /// Color hint (hex color code, e.g., "#FF5733")
    #[prost(string, tag = "7")]
    pub color: ::prost::alloc::string::String,
}
/// Unified message wrapper for WebSocket streaming
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamMessage {
    #[prost(oneof = "stream_message::Payload", tags = "1, 2, 3, 4")]
    pub payload: ::core::option::Option<stream_message::Payload>,
}
/// Nested message and enum types in `StreamMessage`.
pub mod stream_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Trade(super::TradeTick),
        #[prost(message, tag = "2")]
        Metric(super::MarketMetric),
        #[prost(message, tag = "3")]
        Umap(super::UmapCoordinate),
        #[prost(message, tag = "4")]
        Heartbeat(super::Heartbeat),
    }
}
/// Heartbeat message to keep connection alive
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Heartbeat {
    #[prost(int64, tag = "1")]
    pub timestamp_us: i64,
    /// "ok" or error message
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
}
/// Request for gap analysis
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGapsRequest {
    /// Symbol to analyze (e.g., "BTC-USDT")
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// Start time (RFC3339 format)
    #[prost(string, tag = "2")]
    pub start_time: ::prost::alloc::string::String,
    /// End time (RFC3339 format)
    #[prost(string, tag = "3")]
    pub end_time: ::prost::alloc::string::String,
    /// Minimum gap duration in milliseconds
    #[prost(int64, tag = "4")]
    pub threshold_ms: i64,
    /// Optional: Exchange filter
    #[prost(string, optional, tag = "5")]
    pub exchange: ::core::option::Option<::prost::alloc::string::String>,
}
/// A detected gap in the data
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Gap {
    /// Start of gap
    #[prost(string, tag = "1")]
    pub gap_start: ::prost::alloc::string::String,
    /// End of gap
    #[prost(string, tag = "2")]
    pub gap_end: ::prost::alloc::string::String,
    /// Duration in milliseconds
    #[prost(int64, tag = "3")]
    pub duration_ms: i64,
    /// Symbol
    #[prost(string, tag = "4")]
    pub symbol: ::prost::alloc::string::String,
    /// Exchange
    #[prost(string, tag = "5")]
    pub exchange: ::prost::alloc::string::String,
}
/// Response for gap analysis
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGapsResponse {
    /// List of detected gaps
    #[prost(message, repeated, tag = "1")]
    pub gaps: ::prost::alloc::vec::Vec<Gap>,
    /// Total number of gaps found
    #[prost(int32, tag = "2")]
    pub total_gaps: i32,
    /// Total missing time in milliseconds
    #[prost(int64, tag = "3")]
    pub total_missing_ms: i64,
    /// Query execution time in milliseconds
    #[prost(int64, tag = "4")]
    pub query_time_ms: i64,
}
/// Request for historical market metrics
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMetricsRequest {
    /// Metric type (e.g., "fear_greed", "dvol_index")
    #[prost(string, tag = "1")]
    pub metric_type: ::prost::alloc::string::String,
    /// Asset (e.g., "BTC", "GLOBAL")
    #[prost(string, tag = "2")]
    pub asset: ::prost::alloc::string::String,
    /// Start time (RFC3339 format)
    #[prost(string, tag = "3")]
    pub start_time: ::prost::alloc::string::String,
    /// End time (RFC3339 format)
    #[prost(string, tag = "4")]
    pub end_time: ::prost::alloc::string::String,
    /// Optional: Limit number of results
    #[prost(int32, optional, tag = "5")]
    pub limit: ::core::option::Option<i32>,
}
/// Response for historical metrics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMetricsResponse {
    #[prost(message, repeated, tag = "1")]
    pub metrics: ::prost::alloc::vec::Vec<MarketMetric>,
    #[prost(int32, tag = "2")]
    pub count: i32,
}
/// WebSocket subscription request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeRequest {
    /// Symbols to subscribe to (e.g., \["BTC-USDT", "ETH-USDT"\])
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Message types to receive
    #[prost(enumeration = "MessageType", repeated, tag = "2")]
    pub types: ::prost::alloc::vec::Vec<i32>,
    /// Optional: Exchange filter
    #[prost(string, repeated, tag = "3")]
    pub exchanges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Subscription acknowledgment
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub subscribed_count: i32,
}
/// Health check request
///
/// Empty - just checking if service is alive
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {}
/// Health check response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    /// "healthy", "degraded", "unhealthy"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// e.g., {"questdb": "ok", "redis": "ok"}
    #[prost(map = "string, string", tag = "2")]
    pub components: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int64, tag = "3")]
    pub uptime_seconds: i64,
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
}
/// Request to train a UMAP model
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrainModelRequest {
    /// Model ID to assign
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    /// Historical vectors (flattened)
    #[prost(double, repeated, tag = "2")]
    pub vectors: ::prost::alloc::vec::Vec<f64>,
    /// Number of features per vector
    #[prost(int32, tag = "3")]
    pub dimensions: i32,
    /// Number of output dimensions (2 or 3)
    #[prost(int32, tag = "4")]
    pub output_dims: i32,
    /// Number of neighbors (UMAP hyperparameter)
    #[prost(int32, optional, tag = "5")]
    pub n_neighbors: ::core::option::Option<i32>,
    /// Minimum distance (UMAP hyperparameter)
    #[prost(double, optional, tag = "6")]
    pub min_dist: ::core::option::Option<f64>,
}
/// Response from training
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrainModelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub training_time_ms: i64,
}
/// Request to project a new vector
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectRequest {
    /// Model ID to use
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    /// Vector to project
    #[prost(double, repeated, tag = "2")]
    pub vector: ::prost::alloc::vec::Vec<f64>,
}
/// Response with projected coordinates
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(double, tag = "2")]
    pub x: f64,
    #[prost(double, tag = "3")]
    pub y: f64,
    #[prost(double, optional, tag = "4")]
    pub z: ::core::option::Option<f64>,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
/// Message types for subscription filtering
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Unspecified = 0,
    Trade = 1,
    Metric = 2,
    Umap = 3,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_TYPE_UNSPECIFIED",
            Self::Trade => "MESSAGE_TYPE_TRADE",
            Self::Metric => "MESSAGE_TYPE_METRIC",
            Self::Umap => "MESSAGE_TYPE_UMAP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_TYPE_TRADE" => Some(Self::Trade),
            "MESSAGE_TYPE_METRIC" => Some(Self::Metric),
            "MESSAGE_TYPE_UMAP" => Some(Self::Umap),
            _ => None,
        }
    }
}
