//! Real-time Trading Integration
//!
//! Integrates the cognitive core with the live trading engine.
//! Provides real-time market data processing, fear detection, and decision support.
//!
//! # Architecture
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────────┐
//! │                  Real-time Integration                       │
//! ├─────────────────────────────────────────────────────────────┤
//! │                                                               │
//! │  ┌──────────────┐    ┌──────────────┐    ┌──────────────┐  │
//! │  │Market Data   │───►│  Cognitive   │───►│  Trading     │  │
//! │  │  Stream      │    │    Core      │    │  Decisions   │  │
//! │  └──────────────┘    └──────────────┘    └──────────────┘  │
//! │         │                    │                    │          │
//! │         │                    ▼                    │          │
//! │         │            ┌──────────────┐            │          │
//! │         │            │Fear Network  │            │          │
//! │         │            │  Detection   │            │          │
//! │         │            └──────────────┘            │          │
//! │         │                    │                    │          │
//! │         └────────────────────┴────────────────────┘          │
//! │                              │                                │
//! │                              ▼                                │
//! │                      ┌──────────────┐                        │
//! │                      │  Execution   │                        │
//! │                      │   Engine     │                        │
//! │                      └──────────────┘                        │
//! │                                                               │
//! └─────────────────────────────────────────────────────────────┘
//! ```

use crate::amygdala::MarketConditions;
use crate::integration::{CognitiveCore, CognitiveCoreConfig, FearResponse};
use common::{JanusError, Result};
use ndarray::Array5;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{debug, error, info, warn};

/// Real-time market data point
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketDataPoint {
    /// Symbol (e.g., "BTCUSD")
    pub symbol: String,

    /// Timestamp (Unix epoch milliseconds)
    pub timestamp: i64,

    /// Price
    pub price: f64,

    /// Volume
    pub volume: f64,

    /// Bid price
    pub bid: f64,

    /// Ask price
    pub ask: f64,

    /// 24h high
    pub high_24h: f64,

    /// 24h low
    pub low_24h: f64,

    /// 24h volume
    pub volume_24h: f64,

    /// Volatility (calculated)
    pub volatility: Option<f64>,
}

/// Trading signal generated by the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TradingSignal {
    /// Buy signal with confidence (0.0 to 1.0)
    Buy { confidence: f64, size: f64 },

    /// Sell signal with confidence
    Sell { confidence: f64, size: f64 },

    /// Hold/no action
    Hold,

    /// Emergency halt
    Halt { reason: String, threat: String },
}

/// Trading decision with context
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingDecision {
    /// Symbol
    pub symbol: String,

    /// Timestamp
    pub timestamp: i64,

    /// Signal
    pub signal: TradingSignal,

    /// Market conditions at decision time
    pub conditions: MarketConditions,

    /// Fear response if any
    pub fear_response: Option<FearResponse>,

    /// Similar historical experiences
    pub similar_experiences: Vec<String>,

    /// Decision rationale
    pub rationale: String,
}

/// Real-time integration configuration
#[derive(Debug, Clone)]
pub struct RealtimeConfig {
    /// Cognitive core config
    pub cognitive_config: CognitiveCoreConfig,

    /// Symbols to track
    pub symbols: Vec<String>,

    /// Market data buffer size (number of candles)
    pub buffer_size: usize,

    /// Decision interval (milliseconds)
    pub decision_interval_ms: u64,

    /// Fear threshold for emergency halt
    pub emergency_halt_threshold: f64,

    /// Minimum confidence for trades
    pub min_trade_confidence: f64,

    /// Enable automatic trading
    pub enable_auto_trading: bool,

    /// Maximum position size (USD)
    pub max_position_size: f64,

    /// Enable similarity search
    pub enable_similarity_search: bool,

    /// Similarity threshold
    pub similarity_threshold: f64,
}

impl Default for RealtimeConfig {
    fn default() -> Self {
        Self {
            cognitive_config: CognitiveCoreConfig::default(),
            symbols: vec!["BTCUSD".to_string()],
            buffer_size: 60,            // 1 hour of 1-minute candles
            decision_interval_ms: 5000, // 5 seconds
            emergency_halt_threshold: 0.95,
            min_trade_confidence: 0.7,
            enable_auto_trading: false,
            max_position_size: 10000.0,
            enable_similarity_search: true,
            similarity_threshold: 0.8,
        }
    }
}

/// Market data buffer for a symbol
struct MarketDataBuffer {
    #[allow(dead_code)]
    symbol: String,
    buffer: VecDeque<MarketDataPoint>,
    max_size: usize,
}

impl MarketDataBuffer {
    fn new(symbol: String, max_size: usize) -> Self {
        Self {
            symbol,
            buffer: VecDeque::with_capacity(max_size),
            max_size,
        }
    }

    fn push(&mut self, data: MarketDataPoint) {
        if self.buffer.len() >= self.max_size {
            self.buffer.pop_front();
        }
        self.buffer.push_back(data);
    }

    fn is_full(&self) -> bool {
        self.buffer.len() >= self.max_size
    }

    fn to_video(&self) -> Result<Array5<f32>> {
        if !self.is_full() {
            return Err(JanusError::InvalidState(
                "Buffer not full, cannot generate video".to_string(),
            ));
        }

        // Convert market data to video format
        // For now, use a simple representation
        // Shape: (1, T, H, W, C) = (1, buffer_size, 16, 16, 3)
        // This is a placeholder - in production, you'd use proper chart rendering

        let t = self.buffer.len();
        let h = 16;
        let w = 16;
        let c = 3;

        let mut video = Array5::<f32>::zeros((1, t, h, w, c));

        for (i, data) in self.buffer.iter().enumerate() {
            // Normalize price to [0, 1]
            let price_norm = (data.price / data.high_24h.max(1.0)) as f32;
            let volume_norm = (data.volume / data.volume_24h.max(1.0)) as f32;
            let volatility_norm = data.volatility.unwrap_or(0.0) as f32;

            // Fill the frame with normalized values
            for y in 0..h {
                for x in 0..w {
                    video[[0, i, y, x, 0]] = price_norm;
                    video[[0, i, y, x, 1]] = volume_norm;
                    video[[0, i, y, x, 2]] = volatility_norm;
                }
            }
        }

        Ok(video)
    }

    fn calculate_conditions(&self) -> MarketConditions {
        if self.buffer.is_empty() {
            return MarketConditions {
                volatility: 0.0,
                avg_volatility: 0.0,
                volume: 0.0,
                avg_volume: 0.0,
                price_change_pct: 0.0,
            };
        }

        let recent = self.buffer.iter().rev().take(10).collect::<Vec<_>>();
        let all = self.buffer.iter().collect::<Vec<_>>();

        // Calculate average volatility
        let avg_volatility =
            all.iter().filter_map(|d| d.volatility).sum::<f64>() / all.len() as f64;

        // Calculate current volatility
        let current_volatility = recent
            .first()
            .and_then(|d| d.volatility)
            .unwrap_or(avg_volatility);

        // Calculate average volume
        let avg_volume = all.iter().map(|d| d.volume).sum::<f64>() / all.len() as f64;

        // Calculate current volume
        let current_volume = recent.first().map(|d| d.volume).unwrap_or(avg_volume);

        // Calculate price change
        let first_price = all.first().map(|d| d.price).unwrap_or(0.0);
        let last_price = all.last().map(|d| d.price).unwrap_or(0.0);
        let price_change_pct = if first_price > 0.0 {
            (last_price - first_price) / first_price
        } else {
            0.0
        };

        MarketConditions {
            volatility: current_volatility as f32,
            avg_volatility: avg_volatility as f32,
            volume: current_volume as f32,
            avg_volume: avg_volume as f32,
            price_change_pct: price_change_pct as f32,
        }
    }
}

/// Real-time trading system
pub struct RealtimeSystem {
    /// Configuration
    config: RealtimeConfig,

    /// Cognitive core
    cognitive_core: Arc<RwLock<CognitiveCore>>,

    /// Market data buffers per symbol
    buffers: Arc<RwLock<HashMap<String, MarketDataBuffer>>>,

    /// Recent decisions
    recent_decisions: Arc<RwLock<VecDeque<TradingDecision>>>,

    /// System state
    state: Arc<RwLock<SystemState>>,
}

/// System state
#[derive(Debug, Clone, Default)]
pub struct SystemState {
    /// Is system running
    running: bool,

    /// Is emergency halt active
    emergency_halt: bool,

    /// Halt reason
    halt_reason: Option<String>,

    /// Total decisions made
    total_decisions: u64,

    /// Total trades executed
    total_trades: u64,

    /// Emergency halts triggered
    emergency_halts: u64,
}

impl RealtimeSystem {
    /// Create a new real-time system with real Qdrant backend
    pub async fn new(config: RealtimeConfig) -> Result<Self> {
        info!("Initializing real-time trading system");

        // Initialize cognitive core
        let cognitive_core = CognitiveCore::new(config.cognitive_config.clone()).await?;
        let cognitive_core = Arc::new(RwLock::new(cognitive_core));

        // Initialize buffers
        let mut buffers = HashMap::new();
        for symbol in &config.symbols {
            buffers.insert(
                symbol.clone(),
                MarketDataBuffer::new(symbol.clone(), config.buffer_size),
            );
        }
        let buffers = Arc::new(RwLock::new(buffers));

        let recent_decisions = Arc::new(RwLock::new(VecDeque::with_capacity(100)));
        let state = Arc::new(RwLock::new(SystemState::default()));

        info!(
            "Real-time system initialized for {} symbols",
            config.symbols.len()
        );

        Ok(Self {
            config,
            cognitive_core,
            buffers,
            recent_decisions,
            state,
        })
    }

    /// Create a new real-time system with mock backend (for testing)
    pub fn new_mock(config: RealtimeConfig) -> Self {
        info!("Initializing real-time trading system (mock mode)");

        // Initialize cognitive core with mock backend
        let cognitive_core = CognitiveCore::new_mock(config.cognitive_config.clone());
        let cognitive_core = Arc::new(RwLock::new(cognitive_core));

        // Initialize buffers
        let mut buffers = HashMap::new();
        for symbol in &config.symbols {
            buffers.insert(
                symbol.clone(),
                MarketDataBuffer::new(symbol.clone(), config.buffer_size),
            );
        }
        let buffers = Arc::new(RwLock::new(buffers));

        let recent_decisions = Arc::new(RwLock::new(VecDeque::with_capacity(100)));
        let state = Arc::new(RwLock::new(SystemState::default()));

        info!(
            "Real-time system initialized (mock mode) for {} symbols",
            config.symbols.len()
        );

        Self {
            config,
            cognitive_core,
            buffers,
            recent_decisions,
            state,
        }
    }

    /// Process incoming market data
    pub async fn process_market_data(&self, data: MarketDataPoint) -> Result<()> {
        let mut buffers = self.buffers.write().await;

        if let Some(buffer) = buffers.get_mut(&data.symbol) {
            buffer.push(data);
        } else {
            warn!("Received data for untracked symbol: {}", data.symbol);
        }

        Ok(())
    }

    /// Make trading decision for a symbol
    pub async fn make_decision(&self, symbol: &str) -> Result<TradingDecision> {
        debug!("Making trading decision for {}", symbol);

        // Check emergency halt
        {
            let state = self.state.read().await;
            if state.emergency_halt {
                return Ok(TradingDecision {
                    symbol: symbol.to_string(),
                    timestamp: chrono::Utc::now().timestamp_millis(),
                    signal: TradingSignal::Halt {
                        reason: state.halt_reason.clone().unwrap_or_default(),
                        threat: "EMERGENCY_HALT".to_string(),
                    },
                    conditions: MarketConditions {
                        volatility: 0.0,
                        avg_volatility: 0.0,
                        volume: 0.0,
                        avg_volume: 0.0,
                        price_change_pct: 0.0,
                    },
                    fear_response: None,
                    similar_experiences: vec![],
                    rationale: "System in emergency halt".to_string(),
                });
            }
        }

        // Get market conditions
        let (video, conditions) = {
            let buffers = self.buffers.read().await;
            let buffer = buffers
                .get(symbol)
                .ok_or_else(|| JanusError::NotFound(format!("Symbol not found: {}", symbol)))?;

            if !buffer.is_full() {
                return Err(JanusError::InvalidState(
                    "Insufficient market data".to_string(),
                ));
            }

            (buffer.to_video()?, buffer.calculate_conditions())
        };

        // Process with cognitive core
        let mut metadata = HashMap::new();
        metadata.insert("symbol".to_string(), serde_json::json!(symbol));
        metadata.insert(
            "timestamp".to_string(),
            serde_json::json!(chrono::Utc::now().timestamp_millis()),
        );

        let result = {
            let mut core = self.cognitive_core.write().await;
            core.process_experience(&video, &conditions, 0.0, metadata)
                .await?
        };

        // Check for fear response
        let signal = if let Some(fear) = &result.fear_response {
            if fear.danger_score >= self.config.emergency_halt_threshold as f32 {
                // Trigger emergency halt
                self.trigger_emergency_halt(fear.threat_name.clone(), fear.danger_score)
                    .await?;

                TradingSignal::Halt {
                    reason: format!("Danger score {:.2}", fear.danger_score),
                    threat: fear.threat_name.clone(),
                }
            } else if fear.should_halt_trading {
                TradingSignal::Halt {
                    reason: "Fear network recommendation".to_string(),
                    threat: fear.threat_name.clone(),
                }
            } else {
                TradingSignal::Hold
            }
        } else {
            // No fear response - check similarity to past experiences
            if self.config.enable_similarity_search {
                self.generate_signal_from_similarity(&result.embeddings, &conditions)
                    .await?
            } else {
                TradingSignal::Hold
            }
        };

        // Create decision
        let decision = TradingDecision {
            symbol: symbol.to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            signal: signal.clone(),
            conditions,
            fear_response: result.fear_response.clone(),
            similar_experiences: vec![],
            rationale: self.generate_rationale(&signal, &result.fear_response),
        };

        // Record decision
        {
            let mut decisions = self.recent_decisions.write().await;
            if decisions.len() >= 100 {
                decisions.pop_front();
            }
            decisions.push_back(decision.clone());
        }

        // Update state
        {
            let mut state = self.state.write().await;
            state.total_decisions += 1;
            if matches!(
                signal,
                TradingSignal::Buy { .. } | TradingSignal::Sell { .. }
            ) {
                state.total_trades += 1;
            }
        }

        Ok(decision)
    }

    /// Generate signal based on similarity to past experiences
    async fn generate_signal_from_similarity(
        &self,
        embeddings: &[f32],
        _conditions: &MarketConditions,
    ) -> Result<TradingSignal> {
        let core = self.cognitive_core.read().await;

        // Recall similar experiences
        let similar = core
            .recall_similar_experiences(
                embeddings.to_vec(),
                5,
                self.config.similarity_threshold as f32,
            )
            .await?;

        if similar.is_empty() {
            return Ok(TradingSignal::Hold);
        }

        // Calculate average outcome
        let mut total_outcome = 0.0;
        let mut count = 0;

        for memory in &similar {
            if let Some(outcome) = memory.payload.get("outcome").and_then(|v| v.as_f64()) {
                total_outcome += outcome;
                count += 1;
            }
        }

        if count == 0 {
            return Ok(TradingSignal::Hold);
        }

        let avg_outcome = total_outcome / count as f64;
        let confidence = (count as f64 / 5.0).min(1.0); // Max confidence with 5+ samples

        // Generate signal based on historical outcomes
        if avg_outcome > 100.0 && confidence >= self.config.min_trade_confidence {
            Ok(TradingSignal::Buy {
                confidence,
                size: (avg_outcome / 100.0).min(self.config.max_position_size),
            })
        } else if avg_outcome < -100.0 && confidence >= self.config.min_trade_confidence {
            Ok(TradingSignal::Sell {
                confidence,
                size: (avg_outcome.abs() / 100.0).min(self.config.max_position_size),
            })
        } else {
            Ok(TradingSignal::Hold)
        }
    }

    /// Generate decision rationale
    fn generate_rationale(&self, signal: &TradingSignal, fear: &Option<FearResponse>) -> String {
        match signal {
            TradingSignal::Buy { confidence, .. } => {
                format!("Buy signal (confidence: {:.1}%)", confidence * 100.0)
            }
            TradingSignal::Sell { confidence, .. } => {
                format!("Sell signal (confidence: {:.1}%)", confidence * 100.0)
            }
            TradingSignal::Hold => {
                if let Some(f) = fear {
                    format!(
                        "Hold - threat detected: {} (score: {:.2})",
                        f.threat_name, f.danger_score
                    )
                } else {
                    "Hold - no strong signal".to_string()
                }
            }
            TradingSignal::Halt { reason, threat } => {
                format!("HALT - {}: {}", threat, reason)
            }
        }
    }

    /// Trigger emergency halt
    ///
    /// Sets the system into emergency halt mode and attempts to cancel all open
    /// orders and close all positions via the exchange client. If no exchange
    /// client is configured (e.g. in test/paper-trading mode), the halt state
    /// is still recorded so that no new orders can be placed.
    ///
    /// # Exchange Integration Point
    ///
    /// When a live exchange client is available, this method should:
    /// 1. Cancel all open orders across all symbols
    /// 2. Close all open positions at market price
    /// 3. Confirm cancellation/closure with the exchange
    /// 4. Record the results in the audit log
    ///
    /// The current implementation records the halt event with full audit
    /// information but does not issue exchange commands (no exchange client
    /// is wired in yet). This is safe because the halt flag prevents new
    /// orders from being placed by `make_decision`.
    async fn trigger_emergency_halt(&self, threat: String, score: f32) -> Result<()> {
        error!(
            "🚨 EMERGENCY HALT TRIGGERED: {} (score: {:.2})",
            threat, score
        );

        let mut state = self.state.write().await;
        state.emergency_halt = true;
        state.halt_reason = Some(format!("{} (score: {:.2})", threat, score));
        state.emergency_halts += 1;

        // Audit trail: log all context for post-incident review
        warn!(
            emergency_halt = true,
            threat = %threat,
            danger_score = %score,
            total_halts = state.emergency_halts,
            total_decisions = state.total_decisions,
            total_trades = state.total_trades,
            "Emergency halt recorded — exchange order cancellation requires exchange client integration"
        );

        // NOTE: Exchange integration pending — requires an ExchangeClient trait
        // implementation to be injected into RealtimeSystem. When available,
        // the following steps should be performed here:
        //
        //   let exchange = self.exchange_client.as_ref()
        //       .ok_or_else(|| JanusError::Internal("No exchange client configured".into()))?;
        //   exchange.cancel_all_orders().await?;
        //   exchange.close_all_positions().await?;
        //   info!("All orders cancelled and positions closed");
        //
        // Until then, the halt flag is sufficient to prevent new order placement
        // from make_decision(), and manual intervention is expected.

        Ok(())
    }

    /// Reset emergency halt
    pub async fn reset_emergency_halt(&self) -> Result<()> {
        info!("Resetting emergency halt");

        let mut state = self.state.write().await;
        state.emergency_halt = false;
        state.halt_reason = None;

        Ok(())
    }

    /// Get recent decisions
    pub async fn get_recent_decisions(&self, limit: usize) -> Vec<TradingDecision> {
        let decisions = self.recent_decisions.read().await;
        decisions.iter().rev().take(limit).cloned().collect()
    }

    /// Get system state
    pub async fn get_state(&self) -> SystemState {
        self.state.read().await.clone()
    }

    /// Start the system
    pub async fn start(&self) -> Result<()> {
        info!("Starting real-time trading system");
        let mut state = self.state.write().await;
        state.running = true;
        Ok(())
    }

    /// Stop the system
    pub async fn stop(&self) -> Result<()> {
        info!("Stopping real-time trading system");
        let mut state = self.state.write().await;
        state.running = false;
        Ok(())
    }

    /// Check if system is running
    pub async fn is_running(&self) -> bool {
        self.state.read().await.running
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_market_data_buffer() {
        let mut buffer = MarketDataBuffer::new("BTCUSD".to_string(), 5);

        for i in 0..10 {
            buffer.push(MarketDataPoint {
                symbol: "BTCUSD".to_string(),
                timestamp: i,
                price: 50000.0 + i as f64,
                volume: 1000.0,
                bid: 49999.0,
                ask: 50001.0,
                high_24h: 51000.0,
                low_24h: 49000.0,
                volume_24h: 1000000.0,
                volatility: Some(0.02),
            });
        }

        assert_eq!(buffer.buffer.len(), 5);
        assert!(buffer.is_full());
    }

    #[tokio::test]
    #[ignore = "Requires Qdrant instance running on localhost:6334"]
    async fn test_realtime_system_creation() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new(config).await;
        assert!(system.is_ok());
    }

    #[tokio::test]
    #[ignore = "Requires Qdrant instance running on localhost:6334"]
    async fn test_process_market_data() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new(config).await.unwrap();

        let data = MarketDataPoint {
            symbol: "BTCUSD".to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            price: 50000.0,
            volume: 1000.0,
            bid: 49999.0,
            ask: 50001.0,
            high_24h: 51000.0,
            low_24h: 49000.0,
            volume_24h: 1000000.0,
            volatility: Some(0.02),
        };

        let result = system.process_market_data(data).await;
        assert!(result.is_ok());
    }

    // Mock-based tests that don't require Qdrant

    #[test]
    fn test_realtime_system_mock_creation() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new_mock(config);
        assert!(!system.config.symbols.is_empty());
    }

    #[tokio::test]
    async fn test_process_market_data_mock() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new_mock(config);

        let data = MarketDataPoint {
            symbol: "BTCUSD".to_string(),
            timestamp: chrono::Utc::now().timestamp_millis(),
            price: 50000.0,
            volume: 1000.0,
            bid: 49999.0,
            ask: 50001.0,
            high_24h: 51000.0,
            low_24h: 49000.0,
            volume_24h: 1000000.0,
            volatility: Some(0.02),
        };

        let result = system.process_market_data(data).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_make_decision_mock() {
        let mut config = RealtimeConfig::default();
        config.buffer_size = 8; // Smaller buffer to fill faster
        let system = RealtimeSystem::new_mock(config);

        // Fill buffer with enough data to be "full"
        for i in 0..10 {
            let data = MarketDataPoint {
                symbol: "BTCUSD".to_string(),
                timestamp: chrono::Utc::now().timestamp_millis() + i,
                price: 50000.0 + (i as f64 * 10.0),
                volume: 1000.0,
                bid: 49999.0,
                ask: 50001.0,
                high_24h: 51000.0,
                low_24h: 49000.0,
                volume_24h: 1000000.0,
                volatility: Some(0.02),
            };
            system.process_market_data(data).await.unwrap();
        }

        // Make a decision - it may return an error if buffer conditions aren't met,
        // but that's expected behavior
        let decision = system.make_decision("BTCUSD").await;
        // Decision can succeed or fail based on buffer state - just verify no panic
        let _ = decision;
    }

    #[tokio::test]
    async fn test_system_state_mock() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new_mock(config);

        let state = system.get_state().await;
        assert!(!state.running);
        assert!(!state.emergency_halt);
    }

    #[tokio::test]
    async fn test_start_stop_mock() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new_mock(config);

        system.start().await.unwrap();
        assert!(system.is_running().await);

        system.stop().await.unwrap();
        assert!(!system.is_running().await);
    }

    #[tokio::test]
    async fn test_emergency_halt_mock() {
        let config = RealtimeConfig::default();
        let system = RealtimeSystem::new_mock(config);

        system.start().await.unwrap();
        assert!(system.is_running().await);

        // Trigger emergency halt
        system
            .trigger_emergency_halt("Test halt".to_string(), 0.95)
            .await
            .unwrap();

        let state = system.get_state().await;
        assert!(state.emergency_halt);
        assert_eq!(
            state.halt_reason,
            Some("Test halt (score: 0.95)".to_string())
        );

        // Reset
        system.reset_emergency_halt().await.unwrap();
        let state = system.get_state().await;
        assert!(!state.emergency_halt);
    }
}
