//! Service Bridges Module
//!
//! Part of Integration region - Connecting neuromorphic architecture to services
//!
//! This module provides bridges that connect the neuromorphic brain regions
//! to the JANUS service layer:
//! - Forward Service: Real-time signal generation and streaming
//! - Backward Service: Historical analysis, persistence, and training
//! - CNS Service: Health monitoring, metrics, and auto-recovery
//! - Data Service: Market data ingestion and distribution
//!
//! ## Architecture
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                    NEUROMORPHIC CORE                             │
//! │  ┌─────────┐  ┌─────────┐  ┌─────────┐  ┌─────────┐           │
//! │  │ Cortex  │  │Cerebellum│  │Thalamus │  │Amygdala │           │
//! │  └────┬────┘  └────┬────┘  └────┬────┘  └────┬────┘           │
//! │       │            │            │            │                  │
//! │       └────────────┴──────┬─────┴────────────┘                  │
//! │                           │                                      │
//! │                  ┌────────▼────────┐                            │
//! │                  │ Service Bridges │                            │
//! │                  └────────┬────────┘                            │
//! └──────────────────────────┬─────────────────────────────────────┘
//!                            │
//!         ┌──────────────────┼──────────────────┐
//!         │                  │                  │
//!    ┌────▼────┐       ┌─────▼────┐      ┌─────▼────┐
//!    │ Forward │       │ Backward │      │   CNS    │
//!    │ Service │       │ Service  │      │ Service  │
//!    └─────────┘       └──────────┘      └──────────┘
//! ```

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::{RwLock, broadcast, mpsc};
use tracing::{debug, info, warn};

use crate::common::{Error, Result};

/// Message types for inter-service communication
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BridgeMessage {
    /// Signal generated by neuromorphic processing
    Signal(NeuromorphicSignal),

    /// Training data for backward service
    TrainingData(TrainingPayload),

    /// Health/metrics update for CNS
    HealthUpdate(HealthPayload),

    /// Market data from data service
    MarketData(MarketDataPayload),

    /// Configuration update
    ConfigUpdate(ConfigPayload),

    /// System command
    Command(SystemCommand),
}

/// Signal generated by neuromorphic processing
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NeuromorphicSignal {
    /// Unique signal ID
    pub id: String,

    /// Trading symbol
    pub symbol: String,

    /// Signal type (buy, sell, hold)
    pub signal_type: SignalType,

    /// Confidence score (0.0 to 1.0)
    pub confidence: f64,

    /// Source brain region(s)
    pub source_regions: Vec<String>,

    /// Timestamp
    pub timestamp: DateTime<Utc>,

    /// Risk assessment from amygdala
    pub risk_level: RiskLevel,

    /// Recommended position size from hypothalamus
    pub position_size: Option<f64>,

    /// Stop loss from cerebellum
    pub stop_loss: Option<f64>,

    /// Take profit from cerebellum
    pub take_profit: Option<f64>,

    /// Supporting indicators
    pub indicators: HashMap<String, f64>,

    /// Fear/greed index from amygdala
    pub fear_index: f64,

    /// Reasoning from prefrontal cortex
    pub reasoning: Option<String>,
}

impl NeuromorphicSignal {
    /// Create a new signal
    pub fn new(symbol: String, signal_type: SignalType, confidence: f64) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            symbol,
            signal_type,
            confidence,
            source_regions: Vec::new(),
            timestamp: Utc::now(),
            risk_level: RiskLevel::Medium,
            position_size: None,
            stop_loss: None,
            take_profit: None,
            indicators: HashMap::new(),
            fear_index: 0.5,
            reasoning: None,
        }
    }

    /// Check if signal should be executed
    pub fn should_execute(&self, min_confidence: f64, max_risk: RiskLevel) -> bool {
        self.confidence >= min_confidence && self.risk_level <= max_risk
    }

    /// Add source region
    pub fn add_source(mut self, region: &str) -> Self {
        self.source_regions.push(region.to_string());
        self
    }

    /// Set risk assessment
    pub fn with_risk(mut self, risk: RiskLevel, fear_index: f64) -> Self {
        self.risk_level = risk;
        self.fear_index = fear_index;
        self
    }

    /// Set position sizing
    pub fn with_position(mut self, size: f64, stop_loss: f64, take_profit: f64) -> Self {
        self.position_size = Some(size);
        self.stop_loss = Some(stop_loss);
        self.take_profit = Some(take_profit);
        self
    }
}

/// Signal types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalType {
    Buy,
    Sell,
    Hold,
    ReducePosition,
    IncreasePosition,
    ClosePosition,
    EmergencyExit,
}

/// Risk levels
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RiskLevel {
    VeryLow,
    Low,
    Medium,
    High,
    VeryHigh,
    Extreme,
}

impl Default for RiskLevel {
    fn default() -> Self {
        RiskLevel::Medium
    }
}

/// Training data payload for backward service
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingPayload {
    /// Batch ID
    pub batch_id: String,

    /// Training samples
    pub samples: Vec<TrainingSample>,

    /// Source region
    pub source_region: String,

    /// Priority level
    pub priority: Priority,

    /// Timestamp
    pub timestamp: DateTime<Utc>,
}

/// Individual training sample
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingSample {
    /// Sample ID
    pub id: String,

    /// Input features
    pub features: Vec<f64>,

    /// Target/label
    pub target: Vec<f64>,

    /// Sample weight
    pub weight: f64,

    /// Metadata
    pub metadata: HashMap<String, String>,
}

/// Priority levels for processing
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Priority {
    Low,
    Normal,
    High,
    Critical,
}

impl Default for Priority {
    fn default() -> Self {
        Priority::Normal
    }
}

/// Health/metrics payload for CNS
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthPayload {
    /// Region name
    pub region: String,

    /// Is healthy
    pub healthy: bool,

    /// Status message
    pub status: String,

    /// Metrics
    pub metrics: HashMap<String, f64>,

    /// Timestamp
    pub timestamp: DateTime<Utc>,
}

impl HealthPayload {
    /// Create a healthy status
    pub fn healthy(region: &str) -> Self {
        Self {
            region: region.to_string(),
            healthy: true,
            status: "operational".to_string(),
            metrics: HashMap::new(),
            timestamp: Utc::now(),
        }
    }

    /// Create an unhealthy status
    pub fn unhealthy(region: &str, reason: &str) -> Self {
        Self {
            region: region.to_string(),
            healthy: false,
            status: reason.to_string(),
            metrics: HashMap::new(),
            timestamp: Utc::now(),
        }
    }

    /// Add metric
    pub fn with_metric(mut self, name: &str, value: f64) -> Self {
        self.metrics.insert(name.to_string(), value);
        self
    }
}

/// Market data payload from data service
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketDataPayload {
    /// Symbol
    pub symbol: String,

    /// OHLCV data
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,

    /// Orderbook data
    pub bid: Option<f64>,
    pub ask: Option<f64>,
    pub bid_volume: Option<f64>,
    pub ask_volume: Option<f64>,

    /// Trade data
    pub last_trade_price: Option<f64>,
    pub last_trade_size: Option<f64>,

    /// Timestamp
    pub timestamp: DateTime<Utc>,
}

/// Configuration update payload
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfigPayload {
    /// Target region or service
    pub target: String,

    /// Configuration key-value pairs
    pub config: HashMap<String, String>,

    /// Apply immediately
    pub immediate: bool,

    /// Timestamp
    pub timestamp: DateTime<Utc>,
}

/// System commands
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SystemCommand {
    /// Start a region/service
    Start(String),

    /// Stop a region/service
    Stop(String),

    /// Restart a region/service
    Restart(String),

    /// Pause processing
    Pause,

    /// Resume processing
    Resume,

    /// Emergency shutdown
    EmergencyShutdown,

    /// Trigger circuit breaker
    TriggerCircuitBreaker(String),

    /// Reset circuit breaker
    ResetCircuitBreaker(String),
}

/// Service bridge trait - implemented by each service bridge
#[async_trait]
pub trait ServiceBridge: Send + Sync {
    /// Get bridge name
    fn name(&self) -> &str;

    /// Check if bridge is connected
    fn is_connected(&self) -> bool;

    /// Connect to the service
    async fn connect(&mut self) -> Result<()>;

    /// Disconnect from the service
    async fn disconnect(&mut self) -> Result<()>;

    /// Send a message to the service
    async fn send(&self, message: BridgeMessage) -> Result<()>;

    /// Health check
    async fn health_check(&self) -> bool;
}

/// Forward Service Bridge
/// Sends signals from neuromorphic processing to forward service for execution
pub struct ForwardServiceBridge {
    name: String,
    connected: bool,
    signal_tx: Option<mpsc::Sender<NeuromorphicSignal>>,
    config: ForwardBridgeConfig,
}

/// Configuration for forward service bridge
#[derive(Debug, Clone)]
pub struct ForwardBridgeConfig {
    /// Minimum confidence to forward signals
    pub min_confidence: f64,

    /// Maximum risk level to forward
    pub max_risk_level: RiskLevel,

    /// Enable signal filtering
    pub enable_filtering: bool,

    /// Buffer size for signal channel
    pub buffer_size: usize,
}

impl Default for ForwardBridgeConfig {
    fn default() -> Self {
        Self {
            min_confidence: 0.6,
            max_risk_level: RiskLevel::High,
            enable_filtering: true,
            buffer_size: 1000,
        }
    }
}

impl ForwardServiceBridge {
    /// Create a new forward service bridge
    pub fn new(config: ForwardBridgeConfig) -> Self {
        Self {
            name: "forward_bridge".to_string(),
            connected: false,
            signal_tx: None,
            config,
        }
    }

    /// Get signal receiver (for forward service to consume)
    pub fn create_signal_channel(&mut self) -> mpsc::Receiver<NeuromorphicSignal> {
        let (tx, rx) = mpsc::channel(self.config.buffer_size);
        self.signal_tx = Some(tx);
        rx
    }

    /// Send a signal to forward service
    pub async fn send_signal(&self, signal: NeuromorphicSignal) -> Result<()> {
        // Apply filtering if enabled
        if self.config.enable_filtering {
            if !signal.should_execute(self.config.min_confidence, self.config.max_risk_level) {
                debug!(
                    "Signal filtered: confidence={}, risk={:?}",
                    signal.confidence, signal.risk_level
                );
                return Ok(());
            }
        }

        if let Some(tx) = &self.signal_tx {
            tx.send(signal)
                .await
                .map_err(|e| Error::Other(format!("Failed to send signal: {}", e)))?;
        } else {
            return Err(Error::Other("Forward bridge not connected".to_string()));
        }

        Ok(())
    }
}

#[async_trait]
impl ServiceBridge for ForwardServiceBridge {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_connected(&self) -> bool {
        self.connected && self.signal_tx.is_some()
    }

    async fn connect(&mut self) -> Result<()> {
        info!("Connecting forward service bridge...");
        // Create a dummy channel for testing if not already set
        if self.signal_tx.is_none() {
            let (tx, _rx) = tokio::sync::mpsc::channel(100);
            self.signal_tx = Some(tx);
        }
        self.connected = true;
        Ok(())
    }

    async fn disconnect(&mut self) -> Result<()> {
        info!("Disconnecting forward service bridge...");
        self.connected = false;
        self.signal_tx = None;
        Ok(())
    }

    async fn send(&self, message: BridgeMessage) -> Result<()> {
        match message {
            BridgeMessage::Signal(signal) => self.send_signal(signal).await,
            _ => {
                warn!("Forward bridge received non-signal message");
                Ok(())
            }
        }
    }

    async fn health_check(&self) -> bool {
        self.is_connected()
    }
}

/// Backward Service Bridge
/// Sends training data and receives historical analysis from backward service
pub struct BackwardServiceBridge {
    name: String,
    connected: bool,
    training_tx: Option<mpsc::Sender<TrainingPayload>>,
    config: BackwardBridgeConfig,
}

/// Configuration for backward service bridge
#[derive(Debug, Clone)]
pub struct BackwardBridgeConfig {
    /// Buffer size for training data channel
    pub buffer_size: usize,

    /// Batch training data before sending
    pub batch_size: usize,

    /// Flush interval in seconds
    pub flush_interval: u64,
}

impl Default for BackwardBridgeConfig {
    fn default() -> Self {
        Self {
            buffer_size: 10000,
            batch_size: 100,
            flush_interval: 30,
        }
    }
}

impl BackwardServiceBridge {
    /// Create a new backward service bridge
    pub fn new(config: BackwardBridgeConfig) -> Self {
        Self {
            name: "backward_bridge".to_string(),
            connected: false,
            training_tx: None,
            config,
        }
    }

    /// Get training data receiver (for backward service to consume)
    pub fn create_training_channel(&mut self) -> mpsc::Receiver<TrainingPayload> {
        let (tx, rx) = mpsc::channel(self.config.buffer_size);
        self.training_tx = Some(tx);
        rx
    }

    /// Send training data to backward service
    pub async fn send_training_data(&self, payload: TrainingPayload) -> Result<()> {
        if let Some(tx) = &self.training_tx {
            tx.send(payload)
                .await
                .map_err(|e| Error::Other(format!("Failed to send training data: {}", e)))?;
        } else {
            return Err(Error::Other("Backward bridge not connected".to_string()));
        }

        Ok(())
    }

    /// Send experience for replay (to hippocampus via backward service)
    pub async fn send_experience(
        &self,
        region: &str,
        features: Vec<f64>,
        target: Vec<f64>,
        weight: f64,
    ) -> Result<()> {
        let sample = TrainingSample {
            id: uuid::Uuid::new_v4().to_string(),
            features,
            target,
            weight,
            metadata: HashMap::new(),
        };

        let payload = TrainingPayload {
            batch_id: uuid::Uuid::new_v4().to_string(),
            samples: vec![sample],
            source_region: region.to_string(),
            priority: Priority::Normal,
            timestamp: Utc::now(),
        };

        self.send_training_data(payload).await
    }
}

#[async_trait]
impl ServiceBridge for BackwardServiceBridge {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_connected(&self) -> bool {
        self.connected && self.training_tx.is_some()
    }

    async fn connect(&mut self) -> Result<()> {
        info!("Connecting backward service bridge...");
        // Create a dummy channel for testing if not already set
        if self.training_tx.is_none() {
            let (tx, _rx) = tokio::sync::mpsc::channel(100);
            self.training_tx = Some(tx);
        }
        self.connected = true;
        Ok(())
    }

    async fn disconnect(&mut self) -> Result<()> {
        info!("Disconnecting backward service bridge...");
        self.connected = false;
        self.training_tx = None;
        Ok(())
    }

    async fn send(&self, message: BridgeMessage) -> Result<()> {
        match message {
            BridgeMessage::TrainingData(payload) => self.send_training_data(payload).await,
            _ => {
                warn!("Backward bridge received non-training message");
                Ok(())
            }
        }
    }

    async fn health_check(&self) -> bool {
        self.is_connected()
    }
}

/// CNS Service Bridge
/// Sends health/metrics updates and receives system commands from CNS
pub struct CnsServiceBridge {
    name: String,
    connected: bool,
    health_tx: Option<mpsc::Sender<HealthPayload>>,
    command_rx: Option<broadcast::Receiver<SystemCommand>>,
    config: CnsBridgeConfig,
}

/// Configuration for CNS service bridge
#[derive(Debug, Clone)]
pub struct CnsBridgeConfig {
    /// Buffer size for health updates
    pub buffer_size: usize,

    /// Health report interval in seconds
    pub report_interval: u64,

    /// Enable auto-recovery signals
    pub enable_auto_recovery: bool,
}

impl Default for CnsBridgeConfig {
    fn default() -> Self {
        Self {
            buffer_size: 100,
            report_interval: 10,
            enable_auto_recovery: true,
        }
    }
}

impl CnsServiceBridge {
    /// Create a new CNS service bridge
    pub fn new(config: CnsBridgeConfig) -> Self {
        Self {
            name: "cns_bridge".to_string(),
            connected: false,
            health_tx: None,
            command_rx: None,
            config,
        }
    }

    /// Create health update channel
    pub fn create_health_channel(&mut self) -> mpsc::Receiver<HealthPayload> {
        let (tx, rx) = mpsc::channel(self.config.buffer_size);
        self.health_tx = Some(tx);
        rx
    }

    /// Set command receiver
    pub fn set_command_receiver(&mut self, rx: broadcast::Receiver<SystemCommand>) {
        self.command_rx = Some(rx);
    }

    /// Send health update to CNS
    pub async fn send_health_update(&self, payload: HealthPayload) -> Result<()> {
        if let Some(tx) = &self.health_tx {
            tx.send(payload)
                .await
                .map_err(|e| Error::Other(format!("Failed to send health update: {}", e)))?;
        } else {
            return Err(Error::Other("CNS bridge not connected".to_string()));
        }

        Ok(())
    }

    /// Report region health
    pub async fn report_region_health(
        &self,
        region: &str,
        healthy: bool,
        metrics: HashMap<String, f64>,
    ) -> Result<()> {
        let payload = if healthy {
            HealthPayload::healthy(region)
        } else {
            HealthPayload::unhealthy(region, "Region unhealthy")
        };

        let payload = HealthPayload { metrics, ..payload };

        self.send_health_update(payload).await
    }
}

#[async_trait]
impl ServiceBridge for CnsServiceBridge {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_connected(&self) -> bool {
        self.connected && self.health_tx.is_some()
    }

    async fn connect(&mut self) -> Result<()> {
        info!("Connecting CNS service bridge...");
        // Create a dummy channel for testing if not already set
        if self.health_tx.is_none() {
            let (tx, _rx) = tokio::sync::mpsc::channel(100);
            self.health_tx = Some(tx);
        }
        self.connected = true;
        Ok(())
    }

    async fn disconnect(&mut self) -> Result<()> {
        info!("Disconnecting CNS service bridge...");
        self.connected = false;
        self.health_tx = None;
        self.command_rx = None;
        Ok(())
    }

    async fn send(&self, message: BridgeMessage) -> Result<()> {
        match message {
            BridgeMessage::HealthUpdate(payload) => self.send_health_update(payload).await,
            _ => {
                warn!("CNS bridge received non-health message");
                Ok(())
            }
        }
    }

    async fn health_check(&self) -> bool {
        self.is_connected()
    }
}

/// Data Service Bridge
/// Receives market data from data service and distributes to brain regions
pub struct DataServiceBridge {
    name: String,
    connected: bool,
    market_data_tx: broadcast::Sender<MarketDataPayload>,
    config: DataBridgeConfig,
}

/// Configuration for data service bridge
#[derive(Debug, Clone)]
pub struct DataBridgeConfig {
    /// Buffer size for market data broadcast
    pub buffer_size: usize,

    /// Symbols to subscribe to
    pub symbols: Vec<String>,

    /// Enable data filtering
    pub enable_filtering: bool,
}

impl Default for DataBridgeConfig {
    fn default() -> Self {
        Self {
            buffer_size: 10000,
            symbols: vec!["BTC/USDT".to_string(), "ETH/USDT".to_string()],
            enable_filtering: false,
        }
    }
}

impl DataServiceBridge {
    /// Create a new data service bridge
    pub fn new(config: DataBridgeConfig) -> Self {
        let (tx, _) = broadcast::channel(config.buffer_size);
        Self {
            name: "data_bridge".to_string(),
            connected: false,
            market_data_tx: tx,
            config,
        }
    }

    /// Subscribe to market data (brain regions call this)
    pub fn subscribe(&self) -> broadcast::Receiver<MarketDataPayload> {
        self.market_data_tx.subscribe()
    }

    /// Receive market data from data service and broadcast to brain regions
    pub fn broadcast_market_data(&self, data: MarketDataPayload) -> Result<()> {
        // Apply filtering if enabled
        if self.config.enable_filtering && !self.config.symbols.contains(&data.symbol) {
            return Ok(());
        }

        match self.market_data_tx.send(data) {
            Ok(_) => Ok(()),
            Err(e) => {
                // No receivers is not an error
                debug!("No receivers for market data: {}", e);
                Ok(())
            }
        }
    }

    /// Get subscribed symbols
    pub fn symbols(&self) -> &[String] {
        &self.config.symbols
    }
}

#[async_trait]
impl ServiceBridge for DataServiceBridge {
    fn name(&self) -> &str {
        &self.name
    }

    fn is_connected(&self) -> bool {
        self.connected
    }

    async fn connect(&mut self) -> Result<()> {
        info!("Connecting data service bridge...");
        self.connected = true;
        Ok(())
    }

    async fn disconnect(&mut self) -> Result<()> {
        info!("Disconnecting data service bridge...");
        self.connected = false;
        Ok(())
    }

    async fn send(&self, message: BridgeMessage) -> Result<()> {
        match message {
            BridgeMessage::MarketData(data) => self.broadcast_market_data(data),
            _ => {
                warn!("Data bridge received non-market-data message");
                Ok(())
            }
        }
    }

    async fn health_check(&self) -> bool {
        self.is_connected()
    }
}

/// Bridge Manager - Coordinates all service bridges
pub struct BridgeManager {
    forward_bridge: Arc<RwLock<ForwardServiceBridge>>,
    backward_bridge: Arc<RwLock<BackwardServiceBridge>>,
    cns_bridge: Arc<RwLock<CnsServiceBridge>>,
    data_bridge: Arc<RwLock<DataServiceBridge>>,
}

impl BridgeManager {
    /// Create a new bridge manager with default configurations
    pub fn new() -> Self {
        Self {
            forward_bridge: Arc::new(RwLock::new(ForwardServiceBridge::new(
                ForwardBridgeConfig::default(),
            ))),
            backward_bridge: Arc::new(RwLock::new(BackwardServiceBridge::new(
                BackwardBridgeConfig::default(),
            ))),
            cns_bridge: Arc::new(RwLock::new(CnsServiceBridge::new(
                CnsBridgeConfig::default(),
            ))),
            data_bridge: Arc::new(RwLock::new(DataServiceBridge::new(
                DataBridgeConfig::default(),
            ))),
        }
    }

    /// Create with custom configurations
    pub fn with_configs(
        forward_config: ForwardBridgeConfig,
        backward_config: BackwardBridgeConfig,
        cns_config: CnsBridgeConfig,
        data_config: DataBridgeConfig,
    ) -> Self {
        Self {
            forward_bridge: Arc::new(RwLock::new(ForwardServiceBridge::new(forward_config))),
            backward_bridge: Arc::new(RwLock::new(BackwardServiceBridge::new(backward_config))),
            cns_bridge: Arc::new(RwLock::new(CnsServiceBridge::new(cns_config))),
            data_bridge: Arc::new(RwLock::new(DataServiceBridge::new(data_config))),
        }
    }

    /// Get forward bridge
    pub fn forward(&self) -> Arc<RwLock<ForwardServiceBridge>> {
        Arc::clone(&self.forward_bridge)
    }

    /// Get backward bridge
    pub fn backward(&self) -> Arc<RwLock<BackwardServiceBridge>> {
        Arc::clone(&self.backward_bridge)
    }

    /// Get CNS bridge
    pub fn cns(&self) -> Arc<RwLock<CnsServiceBridge>> {
        Arc::clone(&self.cns_bridge)
    }

    /// Get data bridge
    pub fn data(&self) -> Arc<RwLock<DataServiceBridge>> {
        Arc::clone(&self.data_bridge)
    }

    /// Connect all bridges
    pub async fn connect_all(&self) -> Result<()> {
        info!("Connecting all service bridges...");

        self.forward_bridge.write().await.connect().await?;
        self.backward_bridge.write().await.connect().await?;
        self.cns_bridge.write().await.connect().await?;
        self.data_bridge.write().await.connect().await?;

        info!("All service bridges connected");
        Ok(())
    }

    /// Disconnect all bridges
    pub async fn disconnect_all(&self) -> Result<()> {
        info!("Disconnecting all service bridges...");

        self.forward_bridge.write().await.disconnect().await?;
        self.backward_bridge.write().await.disconnect().await?;
        self.cns_bridge.write().await.disconnect().await?;
        self.data_bridge.write().await.disconnect().await?;

        info!("All service bridges disconnected");
        Ok(())
    }

    /// Health check all bridges
    pub async fn health_check_all(&self) -> HashMap<String, bool> {
        let mut status = HashMap::new();

        status.insert(
            "forward".to_string(),
            self.forward_bridge.read().await.health_check().await,
        );
        status.insert(
            "backward".to_string(),
            self.backward_bridge.read().await.health_check().await,
        );
        status.insert(
            "cns".to_string(),
            self.cns_bridge.read().await.health_check().await,
        );
        status.insert(
            "data".to_string(),
            self.data_bridge.read().await.health_check().await,
        );

        status
    }
}

impl Default for BridgeManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_signal_creation() {
        let signal = NeuromorphicSignal::new("BTC/USDT".to_string(), SignalType::Buy, 0.85);
        assert_eq!(signal.symbol, "BTC/USDT");
        assert_eq!(signal.signal_type, SignalType::Buy);
        assert_eq!(signal.confidence, 0.85);
    }

    #[test]
    fn test_signal_filtering() {
        let high_confidence = NeuromorphicSignal::new("BTC/USDT".to_string(), SignalType::Buy, 0.9)
            .with_risk(RiskLevel::Low, 0.3);
        assert!(high_confidence.should_execute(0.6, RiskLevel::High));

        let low_confidence = NeuromorphicSignal::new("BTC/USDT".to_string(), SignalType::Buy, 0.4)
            .with_risk(RiskLevel::Low, 0.3);
        assert!(!low_confidence.should_execute(0.6, RiskLevel::High));

        let high_risk = NeuromorphicSignal::new("BTC/USDT".to_string(), SignalType::Buy, 0.9)
            .with_risk(RiskLevel::Extreme, 0.9);
        assert!(!high_risk.should_execute(0.6, RiskLevel::High));
    }

    #[test]
    fn test_health_payload() {
        let healthy = HealthPayload::healthy("cortex")
            .with_metric("latency_ms", 5.0)
            .with_metric("signals_per_sec", 100.0);

        assert!(healthy.healthy);
        assert_eq!(healthy.region, "cortex");
        assert_eq!(healthy.metrics.len(), 2);
    }

    #[test]
    fn test_risk_level_ordering() {
        assert!(RiskLevel::Extreme > RiskLevel::High);
        assert!(RiskLevel::High > RiskLevel::Medium);
        assert!(RiskLevel::Medium > RiskLevel::Low);
    }

    #[tokio::test]
    async fn test_forward_bridge() {
        let config = ForwardBridgeConfig::default();
        let mut bridge = ForwardServiceBridge::new(config);

        assert!(!bridge.is_connected());

        bridge.connect().await.unwrap();
        let mut rx = bridge.create_signal_channel();

        assert!(bridge.is_connected());

        let signal = NeuromorphicSignal::new("BTC/USDT".to_string(), SignalType::Buy, 0.9)
            .with_risk(RiskLevel::Low, 0.3);

        bridge.send_signal(signal.clone()).await.unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received.symbol, "BTC/USDT");
    }

    #[tokio::test]
    async fn test_bridge_manager() {
        let manager = BridgeManager::new();

        manager.connect_all().await.unwrap();

        let health = manager.health_check_all().await;
        assert_eq!(health.len(), 4);
        assert!(health.get("forward").copied().unwrap_or(false));
    }

    #[test]
    fn test_training_sample() {
        let sample = TrainingSample {
            id: "test".to_string(),
            features: vec![1.0, 2.0, 3.0],
            target: vec![0.0, 1.0],
            weight: 1.0,
            metadata: HashMap::new(),
        };

        assert_eq!(sample.features.len(), 3);
        assert_eq!(sample.target.len(), 2);
    }
}
