//! Signals API
//!
//! Provides HTTP endpoints for querying trading signals generated by the SignalActor.
//!
//! Endpoints:
//! - GET /api/v1/signals - List all recent signals
//! - GET /api/v1/signals/{symbol} - List signals for a specific symbol
//! - GET /api/v1/signals/{symbol}/{timeframe} - List signals for symbol/timeframe
//! - GET /api/v1/signals/stats - Get signal generation statistics
//! - POST /api/v1/signals/backtest - Run backtest on historical signals

use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::{IntoResponse, Json},
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tracing::{debug, error, info};

use crate::api::AppState;
use crate::backfill::{BacktestConfig, SignalBacktest};

/// Query parameters for signal listing
#[derive(Debug, Deserialize)]
pub struct SignalQuery {
    /// Maximum number of signals to return
    #[serde(default = "default_limit")]
    pub limit: u32,

    /// Signal type filter (e.g., "ema_golden_cross", "rsi_overbought")
    #[serde(default)]
    pub signal_type: Option<String>,

    /// Start timestamp (ISO 8601 or Unix timestamp in milliseconds)
    #[serde(default)]
    pub start_time: Option<String>,

    /// End timestamp (ISO 8601 or Unix timestamp in milliseconds)
    #[serde(default)]
    pub end_time: Option<String>,

    /// Minimum price filter
    #[serde(default)]
    pub min_price: Option<f64>,

    /// Maximum price filter
    #[serde(default)]
    pub max_price: Option<f64>,
}

fn default_limit() -> u32 {
    100
}

/// Signal response structure
#[derive(Debug, Serialize)]
pub struct SignalResponse {
    pub symbol: String,
    pub timeframe: String,
    pub signal_type: String,
    pub direction: String,
    pub timestamp: String,
    pub price: f64,
    pub ema_8: Option<f64>,
    pub ema_21: Option<f64>,
    pub rsi: Option<f64>,
    pub macd: Option<f64>,
    pub macd_signal: Option<f64>,
    pub metadata: String,
}

/// List signals response
#[derive(Debug, Serialize)]
pub struct ListSignalsResponse {
    pub signals: Vec<SignalResponse>,
    pub count: usize,
    pub limit: u32,
}

/// Signal statistics response
#[derive(Debug, Serialize)]
pub struct SignalStatsResponse {
    pub total_signals: u64,
    pub signals_by_type: HashMap<String, u64>,
    pub signals_by_symbol: HashMap<String, u64>,
    pub signals_by_timeframe: HashMap<String, u64>,
    pub last_signal_timestamp: Option<String>,
}

/// Backtest request
#[derive(Debug, Deserialize)]
pub struct BacktestRequest {
    /// Symbol to backtest
    pub symbol: String,

    /// Timeframe to backtest
    pub timeframe: String,

    /// Optional start time filter
    #[serde(default)]
    pub start_time: Option<String>,

    /// Optional end time filter
    #[serde(default)]
    pub end_time: Option<String>,

    /// Lookforward minutes (default: 60)
    #[serde(default = "default_lookforward")]
    pub lookforward_minutes: i64,

    /// Profit target percentage (default: 1.0)
    #[serde(default = "default_profit_target")]
    pub profit_target_pct: f64,

    /// Stop loss percentage (default: 0.5)
    #[serde(default = "default_stop_loss")]
    pub stop_loss_pct: f64,
}

fn default_lookforward() -> i64 {
    60
}

fn default_profit_target() -> f64 {
    1.0
}

fn default_stop_loss() -> f64 {
    0.5
}

/// GET /api/v1/signals
///
/// List all recent signals with optional filtering
pub async fn list_all_signals_handler(
    State(state): State<AppState>,
    Query(query): Query<SignalQuery>,
) -> impl IntoResponse {
    debug!(
        "Fetching all signals with limit={}, type={:?}",
        query.limit, query.signal_type
    );

    match fetch_signals_from_db(&state, None, None, &query).await {
        Ok(response) => (StatusCode::OK, Json(response)).into_response(),
        Err(e) => {
            error!("Failed to fetch signals: {}", e);
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error": "Failed to fetch signals",
                    "details": e.to_string()
                })),
            )
                .into_response()
        }
    }
}

/// GET /api/v1/signals/{symbol}
///
/// List signals for a specific symbol
pub async fn list_signals_by_symbol_handler(
    State(state): State<AppState>,
    Path(symbol): Path<String>,
    Query(query): Query<SignalQuery>,
) -> impl IntoResponse {
    debug!(
        "Fetching signals for symbol={} with limit={}, type={:?}",
        symbol, query.limit, query.signal_type
    );

    match fetch_signals_from_db(&state, Some(&symbol), None, &query).await {
        Ok(response) => (StatusCode::OK, Json(response)).into_response(),
        Err(e) => {
            error!("Failed to fetch signals for {}: {}", symbol, e);
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error": "Failed to fetch signals",
                    "details": e.to_string()
                })),
            )
                .into_response()
        }
    }
}

/// POST /api/v1/signals/backtest
///
/// Run a backtest on historical signals to calculate performance metrics
pub async fn run_backtest_handler(
    State(state): State<AppState>,
    Json(request): Json<BacktestRequest>,
) -> impl IntoResponse {
    info!(
        "Running backtest for {}:{} (lookforward: {}m, target: {}%, stop: {}%)",
        request.symbol,
        request.timeframe,
        request.lookforward_minutes,
        request.profit_target_pct,
        request.stop_loss_pct
    );

    let config = BacktestConfig {
        lookforward_minutes: request.lookforward_minutes,
        profit_target_pct: request.profit_target_pct,
        stop_loss_pct: request.stop_loss_pct,
        min_signals: 1, // Allow backtesting with any number of signals
    };

    let backtest = SignalBacktest::new(state.storage.clone(), config);

    match backtest
        .run(
            &request.symbol,
            &request.timeframe,
            request.start_time.as_deref(),
            request.end_time.as_deref(),
        )
        .await
    {
        Ok(results) => {
            info!(
                "Backtest complete: {} trades, {:.2}% win rate",
                results.total_trades, results.win_rate
            );
            (StatusCode::OK, Json(results)).into_response()
        }
        Err(e) => {
            error!("Backtest failed: {}", e);
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error": "Backtest failed",
                    "details": e.to_string()
                })),
            )
                .into_response()
        }
    }
}

/// GET /api/v1/signals/{symbol}/{timeframe}
///
/// List signals for a specific symbol and timeframe
pub async fn list_signals_handler(
    State(state): State<AppState>,
    Path((symbol, timeframe)): Path<(String, String)>,
    Query(query): Query<SignalQuery>,
) -> impl IntoResponse {
    debug!(
        "Fetching signals for {}:{} with limit={}, type={:?}",
        symbol, timeframe, query.limit, query.signal_type
    );

    match fetch_signals_from_db(&state, Some(&symbol), Some(&timeframe), &query).await {
        Ok(response) => (StatusCode::OK, Json(response)).into_response(),
        Err(e) => {
            error!(
                "Failed to fetch signals for {}:{}: {}",
                symbol, timeframe, e
            );
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error": "Failed to fetch signals",
                    "details": e.to_string()
                })),
            )
                .into_response()
        }
    }
}

/// GET /api/v1/signals/stats
///
/// Get signal generation statistics
pub async fn get_signal_stats_handler(State(state): State<AppState>) -> impl IntoResponse {
    debug!("Fetching signal statistics");

    match fetch_signal_stats(&state).await {
        Ok(stats) => (StatusCode::OK, Json(stats)).into_response(),
        Err(e) => {
            error!("Failed to fetch signal stats: {}", e);
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error": "Failed to fetch signal statistics",
                    "details": e.to_string()
                })),
            )
                .into_response()
        }
    }
}

/// Fetch signals from QuestDB using HTTP API
async fn fetch_signals_from_db(
    _state: &AppState,
    symbol: Option<&str>,
    timeframe: Option<&str>,
    query: &SignalQuery,
) -> Result<ListSignalsResponse, Box<dyn std::error::Error>> {
    // Build SQL query
    let mut sql = String::from(
        "SELECT
            symbol,
            timeframe,
            signal_type,
            direction,
            timestamp,
            price,
            ema_8,
            ema_21,
            rsi,
            macd,
            macd_signal,
            metadata
        FROM signals_crypto",
    );

    let mut conditions = Vec::new();

    // Add symbol filter
    if let Some(sym) = symbol {
        conditions.push(format!("symbol = '{}'", sym));
    }

    // Add timeframe filter
    if let Some(tf) = timeframe {
        conditions.push(format!("timeframe = '{}'", tf));
    }

    // Add signal type filter
    if let Some(sig_type) = &query.signal_type {
        conditions.push(format!("signal_type = '{}'", sig_type));
    }

    // Add time range filters
    if let Some(start) = &query.start_time {
        conditions.push(format!("timestamp >= '{}'", start));
    }

    if let Some(end) = &query.end_time {
        conditions.push(format!("timestamp < '{}'", end));
    }

    // Add price range filters
    if let Some(min_price) = query.min_price {
        conditions.push(format!("price >= {}", min_price));
    }

    if let Some(max_price) = query.max_price {
        conditions.push(format!("price <= {}", max_price));
    }

    // Append WHERE clause if we have conditions
    if !conditions.is_empty() {
        sql.push_str(" WHERE ");
        sql.push_str(&conditions.join(" AND "));
    }

    // Add ordering and limit
    sql.push_str(" ORDER BY timestamp DESC");
    sql.push_str(&format!(" LIMIT {}", query.limit));

    debug!("Executing signal query: {}", sql);

    // Execute query via QuestDB HTTP API
    let questdb_host = std::env::var("QUESTDB_HOST").unwrap_or_else(|_| "questdb".to_string());
    let questdb_http_port =
        std::env::var("QUESTDB_HTTP_PORT").unwrap_or_else(|_| "9000".to_string());

    let url = format!("http://{}:{}/exec", questdb_host, questdb_http_port);

    let client = reqwest::Client::new();
    let response = client.get(&url).query(&[("query", &sql)]).send().await?;

    if !response.status().is_success() {
        let error_text = response.text().await?;
        return Err(format!("QuestDB query failed: {}", error_text).into());
    }

    let json: serde_json::Value = response.json().await?;

    // Parse QuestDB response
    let dataset = json["dataset"]
        .as_array()
        .ok_or("Missing dataset in response")?;

    let mut signals = Vec::new();

    for row in dataset {
        let row_array = row.as_array().ok_or("Invalid row format")?;

        if row_array.len() >= 12 {
            signals.push(SignalResponse {
                symbol: row_array[0].as_str().unwrap_or_default().to_string(),
                timeframe: row_array[1].as_str().unwrap_or_default().to_string(),
                signal_type: row_array[2].as_str().unwrap_or_default().to_string(),
                direction: row_array[3].as_str().unwrap_or_default().to_string(),
                timestamp: row_array[4].as_str().unwrap_or_default().to_string(),
                price: row_array[5].as_f64().unwrap_or(0.0),
                ema_8: row_array[6].as_f64(),
                ema_21: row_array[7].as_f64(),
                rsi: row_array[8].as_f64(),
                macd: row_array[9].as_f64(),
                macd_signal: row_array[10].as_f64(),
                metadata: row_array[11].as_str().unwrap_or_default().to_string(),
            });
        }
    }

    Ok(ListSignalsResponse {
        count: signals.len(),
        signals,
        limit: query.limit,
    })
}

/// Fetch signal statistics from QuestDB
async fn fetch_signal_stats(
    _state: &AppState,
) -> Result<SignalStatsResponse, Box<dyn std::error::Error>> {
    let questdb_host = std::env::var("QUESTDB_HOST").unwrap_or_else(|_| "questdb".to_string());
    let questdb_http_port =
        std::env::var("QUESTDB_HTTP_PORT").unwrap_or_else(|_| "9000".to_string());
    let url = format!("http://{}:{}/exec", questdb_host, questdb_http_port);
    let client = reqwest::Client::new();

    // Total signals
    let total_sql = "SELECT COUNT(*) as total FROM signals_crypto";
    let total_response = client
        .get(&url)
        .query(&[("query", total_sql)])
        .send()
        .await?;

    let total_json: serde_json::Value = total_response.json().await?;
    let total_signals = total_json["dataset"][0][0].as_u64().unwrap_or(0);

    // Signals by type
    let by_type_sql =
        "SELECT signal_type, COUNT(*) as count FROM signals_crypto GROUP BY signal_type";
    let by_type_response = client
        .get(&url)
        .query(&[("query", by_type_sql)])
        .send()
        .await?;

    let by_type_json: serde_json::Value = by_type_response.json().await?;
    let mut signals_by_type = HashMap::new();
    if let Some(dataset) = by_type_json["dataset"].as_array() {
        for row in dataset {
            if let Some(row_array) = row.as_array()
                && row_array.len() >= 2
            {
                let signal_type = row_array[0].as_str().unwrap_or_default().to_string();
                let count = row_array[1].as_u64().unwrap_or(0);
                signals_by_type.insert(signal_type, count);
            }
        }
    }

    // Signals by symbol
    let by_symbol_sql = "SELECT symbol, COUNT(*) as count FROM signals_crypto GROUP BY symbol";
    let by_symbol_response = client
        .get(&url)
        .query(&[("query", by_symbol_sql)])
        .send()
        .await?;

    let by_symbol_json: serde_json::Value = by_symbol_response.json().await?;
    let mut signals_by_symbol = HashMap::new();
    if let Some(dataset) = by_symbol_json["dataset"].as_array() {
        for row in dataset {
            if let Some(row_array) = row.as_array()
                && row_array.len() >= 2
            {
                let symbol = row_array[0].as_str().unwrap_or_default().to_string();
                let count = row_array[1].as_u64().unwrap_or(0);
                signals_by_symbol.insert(symbol, count);
            }
        }
    }

    // Signals by timeframe
    let by_timeframe_sql =
        "SELECT timeframe, COUNT(*) as count FROM signals_crypto GROUP BY timeframe";
    let by_timeframe_response = client
        .get(&url)
        .query(&[("query", by_timeframe_sql)])
        .send()
        .await?;

    let by_timeframe_json: serde_json::Value = by_timeframe_response.json().await?;
    let mut signals_by_timeframe = HashMap::new();
    if let Some(dataset) = by_timeframe_json["dataset"].as_array() {
        for row in dataset {
            if let Some(row_array) = row.as_array()
                && row_array.len() >= 2
            {
                let timeframe = row_array[0].as_str().unwrap_or_default().to_string();
                let count = row_array[1].as_u64().unwrap_or(0);
                signals_by_timeframe.insert(timeframe, count);
            }
        }
    }

    // Last signal timestamp
    let last_signal_sql =
        "SELECT MAX(timestamp) as last_ts FROM signals_crypto WHERE timestamp IS NOT NULL";
    let last_signal_response = client
        .get(&url)
        .query(&[("query", last_signal_sql)])
        .send()
        .await?;

    let last_signal_json: serde_json::Value = last_signal_response.json().await?;
    let last_signal_timestamp = last_signal_json["dataset"][0][0]
        .as_str()
        .map(|s| s.to_string());

    Ok(SignalStatsResponse {
        total_signals,
        signals_by_type,
        signals_by_symbol,
        signals_by_timeframe,
        last_signal_timestamp,
    })
}
