//! # Trading Strategy Framework
//!
//! This module provides shared types and traits for trading strategies.
//! Individual strategy implementations live in the centralized `janus-strategies` crate.
//!
//! ## Usage
//!
//! For strategy implementations, use `janus_strategies::*`.
//! This module retains configuration types used by the param reload system.

use crate::indicators::IndicatorAnalysis;
use crate::signal::types::{SignalSource, SignalType};
use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::fmt;

/// Configuration for trading strategies
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    /// Minimum signal strength (0.0 to 1.0)
    pub min_strength: f64,

    /// Strategy-specific parameters
    pub parameters: StrategyParameters,
}

impl Default for StrategyConfig {
    fn default() -> Self {
        Self {
            min_strength: 0.5,
            parameters: StrategyParameters::default(),
        }
    }
}

/// Strategy-specific parameters
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyParameters {
    /// RSI oversold threshold (default: 30)
    pub rsi_oversold: f64,

    /// RSI overbought threshold (default: 70)
    pub rsi_overbought: f64,

    /// Bollinger Band breakout threshold (default: 0.8)
    pub bb_breakout_threshold: f64,

    /// Trend confirmation required (default: true)
    pub require_trend_confirmation: bool,

    /// Volume confirmation required (default: false)
    pub require_volume_confirmation: bool,
}

impl Default for StrategyParameters {
    fn default() -> Self {
        Self {
            rsi_oversold: 30.0,
            rsi_overbought: 70.0,
            bb_breakout_threshold: 0.8,
            require_trend_confirmation: true,
            require_volume_confirmation: false,
        }
    }
}

/// Signal generated by a strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategySignal {
    /// Strategy that generated this signal
    pub strategy_name: String,

    /// Signal type (Buy, Sell, Hold)
    pub signal_type: SignalType,

    /// Signal strength (0.0 to 1.0)
    pub strength: f64,

    /// Signal confidence (0.0 to 1.0)
    pub confidence: f64,

    /// Reasoning/explanation for the signal
    pub reason: String,

    /// Supporting indicators
    pub indicators: Vec<String>,
}

impl StrategySignal {
    /// Create a new strategy signal
    pub fn new(
        strategy_name: String,
        signal_type: SignalType,
        strength: f64,
        confidence: f64,
        reason: String,
    ) -> Self {
        Self {
            strategy_name,
            signal_type,
            strength: strength.clamp(0.0, 1.0),
            confidence: confidence.clamp(0.0, 1.0),
            reason,
            indicators: Vec::new(),
        }
    }

    /// Add supporting indicator
    pub fn with_indicator(mut self, indicator: String) -> Self {
        self.indicators.push(indicator);
        self
    }

    /// Check if signal meets minimum strength threshold
    pub fn is_valid(&self, min_strength: f64) -> bool {
        self.strength >= min_strength && self.signal_type.is_actionable()
    }
}

/// Core strategy trait
pub trait Strategy: Send + Sync {
    /// Strategy name
    fn name(&self) -> &str;

    /// Analyze indicators and generate a signal
    fn analyze(&self, analysis: &IndicatorAnalysis) -> Result<StrategySignal>;

    /// Get strategy configuration
    fn config(&self) -> &StrategyConfig;

    /// Create signal source for this strategy
    fn signal_source(&self) -> SignalSource {
        SignalSource::Strategy {
            name: self.name().to_string(),
        }
    }
}

/// Strategy performance metrics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyMetrics {
    pub strategy_name: String,
    pub signals_generated: u64,
    pub buy_signals: u64,
    pub sell_signals: u64,
    pub hold_signals: u64,
    pub avg_strength: f64,
    pub avg_confidence: f64,
}

impl StrategyMetrics {
    pub fn new(strategy_name: String) -> Self {
        Self {
            strategy_name,
            signals_generated: 0,
            buy_signals: 0,
            sell_signals: 0,
            hold_signals: 0,
            avg_strength: 0.0,
            avg_confidence: 0.0,
        }
    }

    pub fn record_signal(&mut self, signal: &StrategySignal) {
        self.signals_generated += 1;

        match signal.signal_type {
            SignalType::Buy | SignalType::StrongBuy => self.buy_signals += 1,
            SignalType::Sell | SignalType::StrongSell => self.sell_signals += 1,
            SignalType::Hold => self.hold_signals += 1,
        }

        // Update running averages
        let n = self.signals_generated as f64;
        self.avg_strength = ((self.avg_strength * (n - 1.0)) + signal.strength) / n;
        self.avg_confidence = ((self.avg_confidence * (n - 1.0)) + signal.confidence) / n;
    }
}

impl fmt::Display for StrategySignal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} - {:?} (strength: {:.2}, confidence: {:.2}): {}",
            self.strategy_name, self.signal_type, self.strength, self.confidence, self.reason
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strategy_signal_creation() {
        let signal = StrategySignal::new(
            "Test".to_string(),
            SignalType::Buy,
            0.8,
            0.9,
            "Test signal".to_string(),
        );

        assert_eq!(signal.strategy_name, "Test");
        assert_eq!(signal.signal_type, SignalType::Buy);
        assert_eq!(signal.strength, 0.8);
        assert_eq!(signal.confidence, 0.9);
    }

    #[test]
    fn test_signal_validity() {
        let signal = StrategySignal::new(
            "Test".to_string(),
            SignalType::Buy,
            0.7,
            0.8,
            "Valid signal".to_string(),
        );

        assert!(signal.is_valid(0.5));
        assert!(signal.is_valid(0.7));
        assert!(!signal.is_valid(0.8));
    }

    #[test]
    fn test_hold_signal_not_valid() {
        let signal = StrategySignal::new(
            "Test".to_string(),
            SignalType::Hold,
            0.8,
            0.9,
            "Hold signal".to_string(),
        );

        assert!(!signal.is_valid(0.5)); // Hold is never actionable
    }

    #[test]
    fn test_strategy_metrics() {
        let mut metrics = StrategyMetrics::new("Test".to_string());

        let buy_signal = StrategySignal::new(
            "Test".to_string(),
            SignalType::Buy,
            0.8,
            0.9,
            "Buy".to_string(),
        );

        metrics.record_signal(&buy_signal);
        assert_eq!(metrics.signals_generated, 1);
        assert_eq!(metrics.buy_signals, 1);
        assert_eq!(metrics.avg_strength, 0.8);
    }

    #[test]
    fn test_config_defaults() {
        let config = StrategyConfig::default();
        assert_eq!(config.min_strength, 0.5);
        assert_eq!(config.parameters.rsi_oversold, 30.0);
        assert_eq!(config.parameters.rsi_overbought, 70.0);
    }
}
