//! `PerAssetCnn` — burn-native reimplementation of the Python `PerAssetCNN`.
//!
//! This is the first model ported as part of the Python → Rust migration
//! (see fks-full `docs/architecture/RUST_MIGRATION.md`, Phase 2). It mirrors,
//! layer-for-layer, the champion architecture defined in the Python trainer at
//! `fks-full/src/ruby/src/ml/model.py` so that a `burn` model can serve the
//! same per-asset entry/exit signal at inference parity.
//!
//! # Architecture (inference path)
//!
//! ```text
//! input (B, n_features=20, window=60)
//!   AssetEncoder:
//!     block1  Conv1d(20→64,  k3, d1) → BatchNorm → +skip → ReLU → SE(64)
//!     block2  Conv1d(64→128, k3, d2) → BatchNorm → +skip → ReLU → SE(128)
//!     block3  Conv1d(128→64, k3, d4) → BatchNorm → +skip → ReLU → SE(64)
//!     block4  Conv1d(64→64,  k3, d8) → BatchNorm → +identity → ReLU → SE(64)
//!     globalavg ⊕ globalmax over time → (B, 128) → Linear(128→64, no bias) → ReLU
//!   head:
//!     [Dropout(0.4) — omitted at inference] → Linear(64→32) → ReLU → Linear(32→4)
//! output logits (B, n_classes=4)  →  softmax → [flat, long, short, loss]
//! ```
//!
//! Channels 64 and 128 are fixed (as in the Python model); blocks 3–4 use
//! `embedding_dim`. Dropout is a no-op at inference and is omitted here so the
//! forward pass is deterministic. BatchNorm uses its running statistics on the
//! non-autodiff [`CpuBackend`] (inference mode), matching PyTorch `.eval()`.
//!
//! # Parity
//!
//! [`reference_logits`] is an **independent** raw-`f32` implementation of the
//! same forward pass. The test suite asserts the `burn` modules agree with it
//! (differential testing — see `tests::burn_matches_reference`). The same
//! reference is the spec a PyTorch-vs-`burn` golden must satisfy; drop golden
//! files into `tests/golden/perasset_cnn/` (generated by
//! `tools/parity/record_perasset_cnn.py`) and `tests::pytorch_goldens` checks
//! them automatically.

use std::collections::HashMap;

use burn_core::module::{Param, RunningState};
use burn_core::tensor::{Tensor, TensorData, activation, backend::Backend};
use burn_nn::conv::{Conv1d, Conv1dConfig};
use burn_nn::{BatchNorm, BatchNormConfig, Linear, LinearConfig, PaddingConfig1d};
use serde::{Deserialize, Serialize};

use super::{ModelMetadata, ModelRecord, SerializedTensor, WeightMap};
use crate::error::{MLError, Result};
use std::path::Path;

/// Default input feature channels (must match `ml/features.py`).
pub const N_FEATURES: usize = 20;
/// Default output classes: flat / long / short / loss.
pub const N_CLASSES: usize = 4;
/// Default candle window length.
pub const DEFAULT_WINDOW: usize = 60;
/// Default encoder embedding width.
pub const DEFAULT_EMBEDDING_DIM: usize = 64;
/// BatchNorm epsilon — matches PyTorch / burn default.
const BN_EPS: f32 = 1e-5;

/// Configuration for [`PerAssetCnn`]. Mirrors the Python constructor args.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PerAssetCnnConfig {
    /// Input feature channels.
    pub n_features: usize,
    /// Candle window length (architecture is window-agnostic via global pooling;
    /// kept for validation / metadata).
    pub window: usize,
    /// Output classes.
    pub n_classes: usize,
    /// Encoder embedding width.
    pub embedding_dim: usize,
}

impl Default for PerAssetCnnConfig {
    fn default() -> Self {
        Self {
            n_features: N_FEATURES,
            window: DEFAULT_WINDOW,
            n_classes: N_CLASSES,
            embedding_dim: DEFAULT_EMBEDDING_DIM,
        }
    }
}

impl PerAssetCnnConfig {
    /// Fixed first-block channel count (as in the Python model).
    const C1: usize = 64;
    /// Fixed second-block channel count (as in the Python model).
    const C2: usize = 128;
}

/// SE reduction divisor (channels / reduction, floored at 8).
fn se_mid(channels: usize) -> usize {
    (channels / 4).max(8)
}
/// 'same' padding for an odd kernel at a given dilation.
fn same_pad(kernel: usize, dilation: usize) -> usize {
    dilation * (kernel - 1) / 2
}

// ---------------------------------------------------------------------------
// Squeeze-and-Excitation block
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct SeBlock<B: Backend> {
    fc1: Linear<B>, // (channels -> mid), no bias
    fc2: Linear<B>, // (mid -> channels), no bias
}

impl<B: Backend> SeBlock<B> {
    fn new(channels: usize, device: &B::Device) -> Self {
        let mid = se_mid(channels);
        Self {
            fc1: LinearConfig::new(channels, mid)
                .with_bias(false)
                .init(device),
            fc2: LinearConfig::new(mid, channels)
                .with_bias(false)
                .init(device),
        }
    }

    /// `x`: (batch, channels, time) → scaled (batch, channels, time).
    fn forward(&self, x: Tensor<B, 3>) -> Tensor<B, 3> {
        let [b, c, _l] = x.dims();
        let squeeze = x.clone().mean_dim(2).reshape([b, c]); // (b, c)
        let excite = activation::relu(self.fc1.forward(squeeze)); // (b, mid)
        let excite = activation::sigmoid(self.fc2.forward(excite)); // (b, c)
        x.mul(excite.reshape([b, c, 1])) // broadcast over time
    }
}

// ---------------------------------------------------------------------------
// Residual conv block: Conv1d → BatchNorm → (+ skip) → ReLU
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct ConvBlock<B: Backend> {
    conv: Conv1d<B>,
    bn: BatchNorm<B>,
    /// 1×1 projection skip when in_channels != out_channels (else identity).
    skip: Option<Conv1d<B>>,
}

impl<B: Backend> ConvBlock<B> {
    fn new(
        in_channels: usize,
        out_channels: usize,
        kernel: usize,
        dilation: usize,
        device: &B::Device,
    ) -> Self {
        let conv = Conv1dConfig::new(in_channels, out_channels, kernel)
            .with_padding(PaddingConfig1d::Explicit(same_pad(kernel, dilation)))
            .with_dilation(dilation)
            .with_bias(false)
            .init(device);
        let bn = BatchNormConfig::new(out_channels).init(device);
        let skip = if in_channels != out_channels {
            Some(
                Conv1dConfig::new(in_channels, out_channels, 1)
                    .with_bias(false)
                    .init(device),
            )
        } else {
            None
        };
        Self { conv, bn, skip }
    }

    fn forward(&self, x: Tensor<B, 3>) -> Tensor<B, 3> {
        let main = self.bn.forward(self.conv.forward(x.clone()));
        let identity = match &self.skip {
            Some(skip) => skip.forward(x),
            None => x,
        };
        activation::relu(main.add(identity))
    }
}

// ---------------------------------------------------------------------------
// Asset encoder: 4 residual blocks (+SE) → dual global pool → projection
// ---------------------------------------------------------------------------

/// Shared convolutional backbone. Used by both [`PerAssetCnn`] and (via the
/// `super::master_cnn`) `MasterCnn`, mirroring the single `_AssetEncoder` class
/// reused by both Python models.
#[derive(Debug)]
pub(crate) struct AssetEncoder<B: Backend> {
    block1: ConvBlock<B>,
    se1: SeBlock<B>,
    block2: ConvBlock<B>,
    se2: SeBlock<B>,
    block3: ConvBlock<B>,
    se3: SeBlock<B>,
    block4: ConvBlock<B>,
    se4: SeBlock<B>,
    pool_proj: Linear<B>, // (2*emb -> emb), no bias
}

impl<B: Backend> AssetEncoder<B> {
    pub(crate) fn new(n_features: usize, embedding_dim: usize, device: &B::Device) -> Self {
        let (c1, c2) = (PerAssetCnnConfig::C1, PerAssetCnnConfig::C2);
        Self {
            block1: ConvBlock::new(n_features, c1, 3, 1, device),
            se1: SeBlock::new(c1, device),
            block2: ConvBlock::new(c1, c2, 3, 2, device),
            se2: SeBlock::new(c2, device),
            block3: ConvBlock::new(c2, embedding_dim, 3, 4, device),
            se3: SeBlock::new(embedding_dim, device),
            block4: ConvBlock::new(embedding_dim, embedding_dim, 3, 8, device),
            se4: SeBlock::new(embedding_dim, device),
            pool_proj: LinearConfig::new(embedding_dim * 2, embedding_dim)
                .with_bias(false)
                .init(device),
        }
    }

    pub(crate) fn forward(&self, x: Tensor<B, 3>) -> Tensor<B, 2> {
        let x = self.se1.forward(self.block1.forward(x));
        let x = self.se2.forward(self.block2.forward(x));
        let x = self.se3.forward(self.block3.forward(x));
        let x = self.se4.forward(self.block4.forward(x));
        let [b, c, _l] = x.dims();
        let avg = x.clone().mean_dim(2).reshape([b, c]);
        let max = x.max_dim(2).reshape([b, c]);
        let pooled = Tensor::cat(vec![avg, max], 1); // (b, 2c)
        activation::relu(self.pool_proj.forward(pooled)) // (b, emb)
    }

    /// Append the encoder's weights (keys prefixed `encoder.`) to `w`.
    pub(crate) fn extract_into(&self, w: &mut WeightMap) {
        let blocks = [
            (&self.block1, &self.se1, 1usize),
            (&self.block2, &self.se2, 2),
            (&self.block3, &self.se3, 3),
            (&self.block4, &self.se4, 4),
        ];
        for (block, se, i) in blocks {
            w.push(st3(
                &format!("encoder.block{i}.conv.weight"),
                &block.conv.weight.val(),
            ));
            w.push(st1(
                &format!("encoder.block{i}.bn.gamma"),
                &block.bn.gamma.val(),
            ));
            w.push(st1(
                &format!("encoder.block{i}.bn.beta"),
                &block.bn.beta.val(),
            ));
            w.push(st1(
                &format!("encoder.block{i}.bn.running_mean"),
                &block.bn.running_mean.value(),
            ));
            w.push(st1(
                &format!("encoder.block{i}.bn.running_var"),
                &block.bn.running_var.value(),
            ));
            if let Some(skip) = &block.skip {
                w.push(st3(
                    &format!("encoder.block{i}.skip.weight"),
                    &skip.weight.val(),
                ));
            }
            w.push(st2(
                &format!("encoder.se{i}.fc1.weight"),
                &se.fc1.weight.val(),
            ));
            w.push(st2(
                &format!("encoder.se{i}.fc2.weight"),
                &se.fc2.weight.val(),
            ));
        }
        w.push(st2(
            "encoder.pool_proj.weight",
            &self.pool_proj.weight.val(),
        ));
    }

    /// Overwrite the encoder's weights from a name→tensor map.
    pub(crate) fn apply(&mut self, map: &HashMap<&str, &SerializedTensor>, device: &B::Device) {
        let mut blocks = [
            (&mut self.block1, &mut self.se1, 1usize),
            (&mut self.block2, &mut self.se2, 2),
            (&mut self.block3, &mut self.se3, 3),
            (&mut self.block4, &mut self.se4, 4),
        ];
        for (block, se, i) in blocks.iter_mut() {
            let i = *i;
            set_conv(
                &mut block.conv,
                map.get(format!("encoder.block{i}.conv.weight").as_str()),
                device,
            );
            set_param1(
                &mut block.bn.gamma,
                map.get(format!("encoder.block{i}.bn.gamma").as_str()),
                device,
            );
            set_param1(
                &mut block.bn.beta,
                map.get(format!("encoder.block{i}.bn.beta").as_str()),
                device,
            );
            if let Some(st) = map.get(format!("encoder.block{i}.bn.running_mean").as_str()) {
                block.bn.running_mean = RunningState::new(t1(st, device));
            }
            if let Some(st) = map.get(format!("encoder.block{i}.bn.running_var").as_str()) {
                block.bn.running_var = RunningState::new(t1(st, device));
            }
            if let Some(skip) = block.skip.as_mut() {
                set_conv(
                    skip,
                    map.get(format!("encoder.block{i}.skip.weight").as_str()),
                    device,
                );
            }
            set_linear_w(
                &mut se.fc1,
                map.get(format!("encoder.se{i}.fc1.weight").as_str()),
                device,
            );
            set_linear_w(
                &mut se.fc2,
                map.get(format!("encoder.se{i}.fc2.weight").as_str()),
                device,
            );
        }
        set_linear_w(
            &mut self.pool_proj,
            map.get("encoder.pool_proj.weight"),
            device,
        );
    }
}

// ---------------------------------------------------------------------------
// PerAssetCnn
// ---------------------------------------------------------------------------

/// Per-asset 1-D CNN signal classifier (`burn`-native).
#[derive(Debug)]
pub struct PerAssetCnn<B: Backend> {
    encoder: AssetEncoder<B>,
    head_fc1: Linear<B>, // (emb -> 32)
    head_fc2: Linear<B>, // (32 -> n_classes)
    config: PerAssetCnnConfig,
}

impl<B: Backend> PerAssetCnn<B> {
    /// Build a freshly-initialised model on `device`.
    pub fn new(config: PerAssetCnnConfig, device: &B::Device) -> Self {
        let encoder = AssetEncoder::new(config.n_features, config.embedding_dim, device);
        let head_fc1 = LinearConfig::new(config.embedding_dim, 32).init(device);
        let head_fc2 = LinearConfig::new(32, config.n_classes).init(device);
        Self {
            encoder,
            head_fc1,
            head_fc2,
            config,
        }
    }

    /// Model configuration.
    pub fn config(&self) -> &PerAssetCnnConfig {
        &self.config
    }

    /// Forward pass. `input`: (batch, n_features, window) → logits (batch, n_classes).
    pub fn forward(&self, input: Tensor<B, 3>) -> Tensor<B, 2> {
        let emb = self.encoder.forward(input);
        let hidden = activation::relu(self.head_fc1.forward(emb));
        self.head_fc2.forward(hidden)
    }

    /// Softmax class probabilities.
    pub fn predict_proba(&self, input: Tensor<B, 3>) -> Tensor<B, 2> {
        activation::softmax(self.forward(input), 1)
    }

    // -- weight extract / inject (burn-native layout) ------------------------

    /// Serialise every learnable tensor into a [`WeightMap`] (burn-native
    /// layout: Linear weights `[in, out]`, Conv weights `[out, in, k]`).
    pub fn extract_weights(&self) -> WeightMap {
        let mut w = Vec::new();
        self.encoder.extract_into(&mut w);
        w.push(st2("head.fc1.weight", &self.head_fc1.weight.val()));
        w.push(st1(
            "head.fc1.bias",
            &self.head_fc1.bias.as_ref().unwrap().val(),
        ));
        w.push(st2("head.fc2.weight", &self.head_fc2.weight.val()));
        w.push(st1(
            "head.fc2.bias",
            &self.head_fc2.bias.as_ref().unwrap().val(),
        ));
        w
    }

    /// Overwrite parameters from a [`WeightMap`] in burn-native layout.
    pub fn apply_weights(&mut self, weights: &WeightMap, device: &B::Device) {
        let map: HashMap<&str, &SerializedTensor> =
            weights.iter().map(|st| (st.name.as_str(), st)).collect();
        self.encoder.apply(&map, device);
        set_linear_w(&mut self.head_fc1, map.get("head.fc1.weight"), device);
        set_linear_b(&mut self.head_fc1, map.get("head.fc1.bias"), device);
        set_linear_w(&mut self.head_fc2, map.get("head.fc2.weight"), device);
        set_linear_b(&mut self.head_fc2, map.get("head.fc2.bias"), device);
    }

    /// Persist config + weights to `path` (postcard [`ModelRecord`]). This is
    /// how the forward service loads champions (mirrors `LstmPredictor`).
    pub fn save<P: AsRef<Path>>(&self, path: P) -> Result<()> {
        save_record(
            path.as_ref(),
            &self.config,
            &self.extract_weights(),
            "per_asset_cnn",
            self.config.n_features,
            self.config.n_classes,
        )
    }

    /// Load a model persisted by [`save`](Self::save).
    pub fn load<P: AsRef<Path>>(path: P, device: &B::Device) -> Result<Self> {
        let (config, weights) = load_record::<PerAssetCnnConfig>(path.as_ref())?;
        let mut model = Self::new(config, device);
        if !weights.is_empty() {
            model.apply_weights(&weights, device);
        }
        Ok(model)
    }
}

/// Persist a model as a postcard [`ModelRecord`] (config JSON + JSON weight
/// map). Shared by the burn CNN models so the forward service can load any of
/// them uniformly.
pub(crate) fn save_record<C: Serialize>(
    path: &Path,
    config: &C,
    weights: &WeightMap,
    name: &str,
    input_size: usize,
    output_size: usize,
) -> Result<()> {
    let weights_json = serde_json::to_vec(weights).map_err(|e| MLError::io_error(e.to_string()))?;
    let config_json = serde_json::to_string(config)?;
    let metadata = ModelMetadata::new(
        name.to_string(),
        env!("CARGO_PKG_VERSION").to_string(),
        name.to_string(),
        input_size,
        output_size,
        "cpu".to_string(),
    );
    let record = ModelRecord::new(metadata, config_json, weights_json);
    let bytes = postcard::to_allocvec(&record)?;
    std::fs::write(path, bytes)
        .map_err(|e| MLError::io_error(format!("failed to write {path:?}: {e}")))?;
    Ok(())
}

/// Load a `(config, weights)` pair persisted by [`save_record`].
pub(crate) fn load_record<C: serde::de::DeserializeOwned>(path: &Path) -> Result<(C, WeightMap)> {
    let bytes = std::fs::read(path)
        .map_err(|e| MLError::io_error(format!("failed to read {path:?}: {e}")))?;
    let record: ModelRecord<Vec<u8>> = postcard::from_bytes(&bytes)?;
    if !record.is_compatible() {
        return Err(MLError::invalid_config(format!(
            "incompatible model format version: {}",
            record.format_version
        )));
    }
    let config: C = serde_json::from_str(&record.config)?;
    let weights: WeightMap = if record.weights.is_empty() {
        Vec::new()
    } else {
        serde_json::from_slice(&record.weights)
            .map_err(|e| MLError::model_load(format!("failed to deserialise weights: {e}")))?
    };
    Ok((config, weights))
}

// ---------------------------------------------------------------------------
// Tensor (de)serialisation helpers
// ---------------------------------------------------------------------------

pub(crate) fn st1<B: Backend>(name: &str, t: &Tensor<B, 1>) -> SerializedTensor {
    SerializedTensor {
        name: name.into(),
        shape: t.dims().to_vec(),
        data: t.to_data().to_vec().unwrap(),
    }
}
pub(crate) fn st2<B: Backend>(name: &str, t: &Tensor<B, 2>) -> SerializedTensor {
    SerializedTensor {
        name: name.into(),
        shape: t.dims().to_vec(),
        data: t.to_data().to_vec().unwrap(),
    }
}
fn st3<B: Backend>(name: &str, t: &Tensor<B, 3>) -> SerializedTensor {
    SerializedTensor {
        name: name.into(),
        shape: t.dims().to_vec(),
        data: t.to_data().to_vec().unwrap(),
    }
}
fn t1<B: Backend>(st: &SerializedTensor, device: &B::Device) -> Tensor<B, 1> {
    Tensor::from_data(TensorData::new(st.data.clone(), [st.shape[0]]), device)
}
fn t2<B: Backend>(st: &SerializedTensor, device: &B::Device) -> Tensor<B, 2> {
    Tensor::from_data(
        TensorData::new(st.data.clone(), [st.shape[0], st.shape[1]]),
        device,
    )
}
fn t3<B: Backend>(st: &SerializedTensor, device: &B::Device) -> Tensor<B, 3> {
    Tensor::from_data(
        TensorData::new(st.data.clone(), [st.shape[0], st.shape[1], st.shape[2]]),
        device,
    )
}
fn set_conv<B: Backend>(conv: &mut Conv1d<B>, st: Option<&&SerializedTensor>, device: &B::Device) {
    if let Some(st) = st {
        conv.weight = Param::initialized(conv.weight.id, t3(st, device));
    }
}
pub(crate) fn set_linear_w<B: Backend>(
    lin: &mut Linear<B>,
    st: Option<&&SerializedTensor>,
    device: &B::Device,
) {
    if let Some(st) = st {
        lin.weight = Param::initialized(lin.weight.id, t2(st, device));
    }
}
pub(crate) fn set_linear_b<B: Backend>(
    lin: &mut Linear<B>,
    st: Option<&&SerializedTensor>,
    device: &B::Device,
) {
    if let (Some(bias), Some(st)) = (lin.bias.as_mut(), st) {
        *bias = Param::initialized(bias.id, t1(st, device));
    }
}
pub(crate) fn set_param1<B: Backend>(
    param: &mut Param<Tensor<B, 1>>,
    st: Option<&&SerializedTensor>,
    device: &B::Device,
) {
    if let Some(st) = st {
        *param = Param::initialized(param.id, t1(st, device));
    }
}

// ---------------------------------------------------------------------------
// Independent reference forward pass (raw f32) — the parity oracle
// ---------------------------------------------------------------------------

/// Independent, plain-`f32` reference for the shared [`AssetEncoder`]. Reads
/// weights (keys prefixed `encoder.`) from a name→tensor map and returns the
/// `embedding_dim`-length embedding for one `(n_features, window)` sample.
///
/// Written without the `burn` neural-network modules so that agreement with the
/// `burn` encoder is a genuine cross-check; reused by both [`reference_logits`]
/// and the MasterCnn reference, and the executable spec a PyTorch golden must
/// satisfy.
pub(crate) fn reference_encoder(
    map: &HashMap<&str, &SerializedTensor>,
    input: &[f32],
    n_features: usize,
    window: usize,
    embedding_dim: usize,
) -> Vec<f32> {
    let get = |name: &str| -> &SerializedTensor {
        map.get(name)
            .unwrap_or_else(|| panic!("missing weight {name}"))
    };

    let l = window;
    let emb = embedding_dim;
    let (c1, c2) = (PerAssetCnnConfig::C1, PerAssetCnnConfig::C2);

    // conv1d (stride 1, zero pad, dilation) — w: [out,in,k]; x: (in,L) → (out,L)
    let conv =
        |x: &[f32], in_c: usize, out_c: usize, k: usize, dil: usize, w: &[f32]| -> Vec<f32> {
            let pad = same_pad(k, dil) as isize;
            let mut y = vec![0f32; out_c * l];
            for o in 0..out_c {
                for t in 0..l {
                    let mut acc = 0f32;
                    for ci in 0..in_c {
                        for j in 0..k {
                            let p = t as isize + (j as isize) * dil as isize - pad;
                            if p >= 0 && (p as usize) < l {
                                acc += w[(o * in_c + ci) * k + j] * x[ci * l + p as usize];
                            }
                        }
                    }
                    y[o * l + t] = acc;
                }
            }
            y
        };
    // batchnorm inference (per channel) in place
    let bn = |x: &mut [f32], c: usize, gamma: &[f32], beta: &[f32], mean: &[f32], var: &[f32]| {
        for ch in 0..c {
            let scale = gamma[ch] / (var[ch] + BN_EPS).sqrt();
            for t in 0..l {
                x[ch * l + t] = (x[ch * l + t] - mean[ch]) * scale + beta[ch];
            }
        }
    };
    let relu = |x: &mut [f32]| x.iter_mut().for_each(|v| *v = v.max(0.0));
    // squeeze-excitation (per channel scale) in place. fc1:[c,mid], fc2:[mid,c]
    let se = |x: &mut [f32], c: usize, fc1: &[f32], fc2: &[f32]| {
        let mid = se_mid(c);
        let mut s = vec![0f32; c];
        for ch in 0..c {
            let mut acc = 0f32;
            for t in 0..l {
                acc += x[ch * l + t];
            }
            s[ch] = acc / l as f32;
        }
        let mut e1 = vec![0f32; mid];
        for m in 0..mid {
            let mut acc = 0f32;
            for ch in 0..c {
                acc += s[ch] * fc1[ch * mid + m];
            }
            e1[m] = acc.max(0.0); // ReLU
        }
        for ch in 0..c {
            let mut acc = 0f32;
            for m in 0..mid {
                acc += e1[m] * fc2[m * c + ch];
            }
            let gate = 1.0 / (1.0 + (-acc).exp()); // sigmoid
            for t in 0..l {
                x[ch * l + t] *= gate;
            }
        }
    };

    // one residual block: conv→bn→(+skip|identity)→relu  (+SE)
    let block = |x: &[f32], in_c: usize, out_c: usize, dil: usize, i: usize| -> Vec<f32> {
        let mut main = conv(
            x,
            in_c,
            out_c,
            3,
            dil,
            &get(&format!("encoder.block{i}.conv.weight")).data,
        );
        bn(
            &mut main,
            out_c,
            &get(&format!("encoder.block{i}.bn.gamma")).data,
            &get(&format!("encoder.block{i}.bn.beta")).data,
            &get(&format!("encoder.block{i}.bn.running_mean")).data,
            &get(&format!("encoder.block{i}.bn.running_var")).data,
        );
        let identity = if in_c != out_c {
            conv(
                x,
                in_c,
                out_c,
                1,
                1,
                &get(&format!("encoder.block{i}.skip.weight")).data,
            )
        } else {
            x.to_vec()
        };
        for idx in 0..out_c * l {
            main[idx] += identity[idx];
        }
        relu(&mut main);
        se(
            &mut main,
            out_c,
            &get(&format!("encoder.se{i}.fc1.weight")).data,
            &get(&format!("encoder.se{i}.fc2.weight")).data,
        );
        main
    };

    let x = block(input, n_features, c1, 1, 1);
    let x = block(&x, c1, c2, 2, 2);
    let x = block(&x, c2, emb, 4, 3);
    let x = block(&x, emb, emb, 8, 4);

    // dual global pool over time → (2*emb) → pool_proj → relu
    let mut pooled = vec![0f32; emb * 2];
    for ch in 0..emb {
        let mut sum = 0f32;
        let mut mx = f32::NEG_INFINITY;
        for t in 0..l {
            let v = x[ch * l + t];
            sum += v;
            mx = mx.max(v);
        }
        pooled[ch] = sum / l as f32;
        pooled[emb + ch] = mx;
    }
    let proj_w = &get("encoder.pool_proj.weight").data; // [2*emb, emb]
    let mut embedding = vec![0f32; emb];
    for o in 0..emb {
        let mut acc = 0f32;
        for i in 0..emb * 2 {
            acc += pooled[i] * proj_w[i * emb + o];
        }
        embedding[o] = acc.max(0.0); // ReLU
    }

    embedding
}

/// Independent raw-`f32` reference logits for one `(n_features, window)` sample.
/// Cross-checks [`PerAssetCnn`]; also the executable spec a PyTorch golden must
/// satisfy.
pub fn reference_logits(weights: &WeightMap, input: &[f32], cfg: &PerAssetCnnConfig) -> Vec<f32> {
    let map: HashMap<&str, &SerializedTensor> =
        weights.iter().map(|st| (st.name.as_str(), st)).collect();
    let embedding = reference_encoder(&map, input, cfg.n_features, cfg.window, cfg.embedding_dim);
    let get = |name: &str| -> &SerializedTensor {
        map.get(name)
            .unwrap_or_else(|| panic!("missing weight {name}"))
    };
    let emb = cfg.embedding_dim;

    // head: Linear(emb→32) → relu → Linear(32→n_classes)
    let (w1, b1) = (&get("head.fc1.weight").data, &get("head.fc1.bias").data); // [emb,32]
    let mut hidden = [0f32; 32];
    for o in 0..32 {
        let mut acc = b1[o];
        for i in 0..emb {
            acc += embedding[i] * w1[i * 32 + o];
        }
        hidden[o] = acc.max(0.0);
    }
    let (w2, b2) = (&get("head.fc2.weight").data, &get("head.fc2.bias").data); // [32,n_classes]
    let mut logits = vec![0f32; cfg.n_classes];
    for o in 0..cfg.n_classes {
        let mut acc = b2[o];
        for i in 0..32 {
            acc += hidden[i] * w2[i * cfg.n_classes + o];
        }
        logits[o] = acc;
    }
    logits
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::CpuBackend;

    /// Deterministic pseudo-random input in [-0.5, 0.5).
    fn make_input(batch: usize, n_features: usize, window: usize) -> Vec<f32> {
        (0..batch * n_features * window)
            .map(|i| ((i * 2_654_435_761usize % 1009) as f32 / 1009.0) - 0.5)
            .collect()
    }

    fn argmax(slice: &[f32]) -> usize {
        slice
            .iter()
            .enumerate()
            .fold((0, f32::NEG_INFINITY), |(bi, bv), (i, &v)| {
                if v > bv { (i, v) } else { (bi, bv) }
            })
            .0
    }

    #[test]
    fn save_load_roundtrip() {
        let device = Default::default();
        let cfg = PerAssetCnnConfig::default();
        let model = PerAssetCnn::<CpuBackend>::new(cfg.clone(), &device);
        let input = Tensor::<CpuBackend, 3>::from_data(
            TensorData::new(
                make_input(2, cfg.n_features, cfg.window),
                [2, cfg.n_features, cfg.window],
            ),
            &device,
        );
        let before = model
            .forward(input.clone())
            .to_data()
            .to_vec::<f32>()
            .unwrap();

        let path = std::env::temp_dir().join("per_asset_cnn_roundtrip.bin");
        model.save(&path).unwrap();
        let loaded = PerAssetCnn::<CpuBackend>::load(&path, &device).unwrap();
        let after = loaded.forward(input).to_data().to_vec::<f32>().unwrap();
        std::fs::remove_file(&path).ok();

        assert_eq!(loaded.config(), model.config());
        for (a, b) in before.iter().zip(after.iter()) {
            assert!((a - b).abs() < 1e-6, "save/load mismatch {a} vs {b}");
        }
    }

    #[test]
    fn forward_shape_and_finite() {
        let device = Default::default();
        let cfg = PerAssetCnnConfig::default();
        let model = PerAssetCnn::<CpuBackend>::new(cfg.clone(), &device);
        let input = Tensor::<CpuBackend, 3>::from_data(
            TensorData::new(
                make_input(3, cfg.n_features, cfg.window),
                [3, cfg.n_features, cfg.window],
            ),
            &device,
        );
        let out = model.forward(input);
        assert_eq!(out.dims(), [3, cfg.n_classes]);
        for v in out.to_data().to_vec::<f32>().unwrap() {
            assert!(v.is_finite(), "non-finite logit {v}");
        }
    }

    #[test]
    fn forward_is_deterministic() {
        let device = Default::default();
        let cfg = PerAssetCnnConfig::default();
        let model = PerAssetCnn::<CpuBackend>::new(cfg.clone(), &device);
        let data = make_input(2, cfg.n_features, cfg.window);
        let mk = || {
            Tensor::<CpuBackend, 3>::from_data(
                TensorData::new(data.clone(), [2, cfg.n_features, cfg.window]),
                &device,
            )
        };
        let a = model.forward(mk()).to_data().to_vec::<f32>().unwrap();
        let b = model.forward(mk()).to_data().to_vec::<f32>().unwrap();
        assert_eq!(a, b);
    }

    /// Extract → inject into a fresh model → identical outputs (covers the
    /// weight (de)serialisation path used by golden loading).
    #[test]
    fn weight_injection_roundtrip() {
        let device = Default::default();
        let cfg = PerAssetCnnConfig::default();
        let model_a = PerAssetCnn::<CpuBackend>::new(cfg.clone(), &device);
        let mut model_b = PerAssetCnn::<CpuBackend>::new(cfg.clone(), &device);
        model_b.apply_weights(&model_a.extract_weights(), &device);

        let input = Tensor::<CpuBackend, 3>::from_data(
            TensorData::new(
                make_input(2, cfg.n_features, cfg.window),
                [2, cfg.n_features, cfg.window],
            ),
            &device,
        );
        let oa = model_a
            .forward(input.clone())
            .to_data()
            .to_vec::<f32>()
            .unwrap();
        let ob = model_b.forward(input).to_data().to_vec::<f32>().unwrap();
        for (a, b) in oa.iter().zip(ob.iter()) {
            assert!((a - b).abs() < 1e-6, "roundtrip mismatch {a} vs {b}");
        }
    }

    /// The heart of the spike: the `burn` model must agree with the
    /// independent raw-`f32` reference on the same weights.
    #[test]
    fn burn_matches_reference() {
        let device = Default::default();
        let cfg = PerAssetCnnConfig::default();
        let model = PerAssetCnn::<CpuBackend>::new(cfg.clone(), &device);
        let weights = model.extract_weights();

        let batch = 3;
        let data = make_input(batch, cfg.n_features, cfg.window);
        let input = Tensor::<CpuBackend, 3>::from_data(
            TensorData::new(data.clone(), [batch, cfg.n_features, cfg.window]),
            &device,
        );
        let burn_out = model.forward(input).to_data().to_vec::<f32>().unwrap();

        let sample_len = cfg.n_features * cfg.window;
        for b in 0..batch {
            let sample = &data[b * sample_len..(b + 1) * sample_len];
            let reference = reference_logits(&weights, sample, &cfg);
            let burn_logits = &burn_out[b * cfg.n_classes..(b + 1) * cfg.n_classes];
            assert_eq!(
                argmax(burn_logits),
                argmax(&reference),
                "argmax disagree (sample {b})"
            );
            for c in 0..cfg.n_classes {
                let diff = (burn_logits[c] - reference[c]).abs();
                assert!(
                    diff < 1e-3,
                    "logit mismatch sample {b} class {c}: burn {} vs ref {} (Δ{diff})",
                    burn_logits[c],
                    reference[c]
                );
            }
        }
    }

    /// Golden-vector parity vs PyTorch. Skips cleanly when no golden files are
    /// present (they are generated by `tools/parity/record_perasset_cnn.py` in
    /// an environment with torch + the champion `.pt`).
    #[test]
    fn pytorch_goldens() {
        #[derive(serde::Deserialize)]
        struct Golden {
            config: PerAssetCnnConfig,
            weights: WeightMap,
            cases: Vec<GoldenCase>,
            tolerance: f32,
        }
        #[derive(serde::Deserialize)]
        struct GoldenCase {
            input: SerializedTensor,
            expected_logits: SerializedTensor,
        }

        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/perasset_cnn");
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => {
                eprintln!(
                    "[pytorch_goldens] {dir} absent — skipping (generate with tools/parity/record_perasset_cnn.py)"
                );
                return;
            }
        };
        let device = Default::default();
        let mut checked = 0usize;
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            let golden: Golden = serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
            let mut model = PerAssetCnn::<CpuBackend>::new(golden.config.clone(), &device);
            model.apply_weights(&golden.weights, &device);
            for (ci, case) in golden.cases.iter().enumerate() {
                let batch = case.input.shape[0];
                let input = Tensor::<CpuBackend, 3>::from_data(
                    TensorData::new(
                        case.input.data.clone(),
                        [batch, case.input.shape[1], case.input.shape[2]],
                    ),
                    &device,
                );
                let out = model.forward(input).to_data().to_vec::<f32>().unwrap();
                assert_eq!(
                    out.len(),
                    case.expected_logits.data.len(),
                    "{path:?} case {ci}: output length mismatch"
                );
                for (got, want) in out.iter().zip(case.expected_logits.data.iter()) {
                    assert!(
                        (got - want).abs() < golden.tolerance,
                        "{path:?} case {ci}: {got} vs {want} (tol {})",
                        golden.tolerance
                    );
                }
            }
            checked += 1;
        }
        if checked == 0 {
            eprintln!("[pytorch_goldens] no *.json goldens in {dir} — skipping");
        } else {
            eprintln!("[pytorch_goldens] verified {checked} golden file(s)");
        }
    }
}
