-- Migration: 001_create_signals_table.sql
-- Description: Create signals table for storing trading signals
-- Created: Week 7

-- Signals table - stores all generated trading signals
CREATE TABLE IF NOT EXISTS signals (
    -- Primary identification
    signal_id UUID PRIMARY KEY,

    -- Signal metadata
    symbol VARCHAR(50) NOT NULL,
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('Buy', 'Sell', 'Hold')),
    timeframe VARCHAR(10) NOT NULL,

    -- Signal quality metrics
    confidence DECIMAL(5, 4) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    strength DECIMAL(5, 4) NOT NULL CHECK (strength >= 0 AND strength <= 1),

    -- Timing
    timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Price information
    entry_price DECIMAL(20, 8),
    stop_loss DECIMAL(20, 8),
    take_profit DECIMAL(20, 8),

    -- Risk metrics
    position_size DECIMAL(20, 8),
    risk_amount DECIMAL(20, 8),
    risk_reward_ratio DECIMAL(10, 4),

    -- Signal source
    source_type VARCHAR(50) NOT NULL,
    source_name VARCHAR(100),

    -- Strategy information
    strategy_name VARCHAR(100),
    strategy_score DECIMAL(5, 4),

    -- ML model information (if applicable)
    model_name VARCHAR(100),
    model_version VARCHAR(50),
    model_confidence DECIMAL(5, 4),

    -- Technical indicators (JSONB for flexibility)
    indicators JSONB,

    -- Additional metadata
    metadata JSONB,

    -- Status tracking
    status VARCHAR(20) DEFAULT 'generated' CHECK (status IN ('generated', 'validated', 'executed', 'cancelled', 'expired')),

    -- Execution tracking
    executed_at TIMESTAMPTZ,
    execution_price DECIMAL(20, 8),

    -- Performance tracking (filled after position close)
    closed_at TIMESTAMPTZ,
    close_price DECIMAL(20, 8),
    pnl DECIMAL(20, 8),
    pnl_percentage DECIMAL(10, 4),

    -- Flags
    filtered BOOLEAN DEFAULT FALSE,
    is_backtest BOOLEAN DEFAULT FALSE
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_signal_type ON signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_symbol_timestamp ON signals(symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_timeframe ON signals(timeframe);
CREATE INDEX IF NOT EXISTS idx_signals_confidence ON signals(confidence DESC);

-- Index for JSONB queries
CREATE INDEX IF NOT EXISTS idx_signals_indicators ON signals USING GIN (indicators);
CREATE INDEX IF NOT EXISTS idx_signals_metadata ON signals USING GIN (metadata);

-- Comments
COMMENT ON TABLE signals IS 'Trading signals generated by JANUS service';
COMMENT ON COLUMN signals.signal_id IS 'Unique identifier for the signal';
COMMENT ON COLUMN signals.confidence IS 'Signal confidence score (0.0 to 1.0)';
COMMENT ON COLUMN signals.strength IS 'Signal strength score (0.0 to 1.0)';
COMMENT ON COLUMN signals.indicators IS 'Technical indicator values at signal generation time';
COMMENT ON COLUMN signals.metadata IS 'Additional signal metadata and context';
