-- ============================================================================
-- JANUS Data Service - QuestDB Schema
-- ============================================================================
-- This script creates the database tables for the JANUS data service.
--
-- Tables:
-- - trades: Individual trade ticks from exchanges
-- - candles: OHLCV candlestick data
-- - orderbook: Order book snapshots
-- - funding_rates: Perpetual futures funding rates
-- - liquidations: Liquidation events
-- - indicators: Technical indicator values
-- - signals: Trading signals generated by the system
--
-- Usage:
--   curl -G http://localhost:9000/exec \
--     --data-urlencode "$(cat schema.sql)"
--
-- Or run interactively in QuestDB UI at http://localhost:9000
-- ============================================================================

-- ============================================================================
-- Trades Table
-- ============================================================================
-- Stores individual trade ticks from exchanges
-- Partitioned by day for efficient queries and data management
-- WAL (Write-Ahead Log) enabled for data durability

CREATE TABLE IF NOT EXISTS trades (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    exchange SYMBOL capacity 16 CACHE,
    side SYMBOL capacity 2 CACHE,
    price DOUBLE,
    amount DOUBLE,
    trade_id SYMBOL capacity 256 NOCACHE,
    exchange_ts TIMESTAMP,
    receipt_ts TIMESTAMP
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_exchange ON trades(exchange);

-- ============================================================================
-- Candles Table
-- ============================================================================
-- Stores aggregated OHLCV candlestick data
-- Used for technical analysis and charting

CREATE TABLE IF NOT EXISTS candles (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    exchange SYMBOL capacity 16 CACHE,
    timeframe SYMBOL capacity 8 CACHE,
    open DOUBLE,
    high DOUBLE,
    low DOUBLE,
    close DOUBLE,
    volume DOUBLE,
    trades_count LONG,
    vwap DOUBLE
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_candles_symbol_timeframe ON candles(symbol, timeframe);

-- ============================================================================
-- Order Book Table
-- ============================================================================
-- Stores order book snapshots
-- Level 2 market data (aggregated by price level)

CREATE TABLE IF NOT EXISTS orderbook (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    exchange SYMBOL capacity 16 CACHE,
    side SYMBOL capacity 2 CACHE,
    price DOUBLE,
    quantity DOUBLE,
    level INT,
    update_id LONG
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_orderbook_symbol ON orderbook(symbol);

-- ============================================================================
-- Funding Rates Table
-- ============================================================================
-- Stores perpetual futures funding rates
-- Important for understanding market sentiment and cost of carry

CREATE TABLE IF NOT EXISTS funding_rates (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    exchange SYMBOL capacity 16 CACHE,
    funding_rate DOUBLE,
    mark_price DOUBLE,
    index_price DOUBLE,
    next_funding_time TIMESTAMP
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_funding_symbol ON funding_rates(symbol);

-- ============================================================================
-- Liquidations Table
-- ============================================================================
-- Stores liquidation events
-- Useful for understanding market stress and volatility

CREATE TABLE IF NOT EXISTS liquidations (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    exchange SYMBOL capacity 16 CACHE,
    side SYMBOL capacity 2 CACHE,
    price DOUBLE,
    quantity DOUBLE,
    value DOUBLE
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_liquidations_symbol ON liquidations(symbol);

-- ============================================================================
-- Indicators Table
-- ============================================================================
-- Stores calculated technical indicator values
-- EMA, RSI, MACD, ATR, Bollinger Bands, etc.

CREATE TABLE IF NOT EXISTS indicators (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    timeframe SYMBOL capacity 8 CACHE,
    indicator_name SYMBOL capacity 32 CACHE,
    value DOUBLE,
    metadata STRING
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_indicators_symbol_name ON indicators(symbol, indicator_name);

-- ============================================================================
-- Signals Table
-- ============================================================================
-- Stores trading signals generated by the system
-- Both rule-based and ML-generated signals

CREATE TABLE IF NOT EXISTS signals (
    timestamp TIMESTAMP,
    signal_id SYMBOL capacity 256 NOCACHE,
    symbol SYMBOL capacity 256 CACHE,
    signal_type SYMBOL capacity 32 CACHE,
    action SYMBOL capacity 8 CACHE,
    strength DOUBLE,
    confidence DOUBLE,
    source SYMBOL capacity 32 CACHE,
    metadata STRING,
    active BOOLEAN
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_active ON signals(active);

-- ============================================================================
-- Alternative Data Table
-- ============================================================================
-- Stores alternative metrics (Fear & Greed, ETF Flows, etc.)

CREATE TABLE IF NOT EXISTS alternative_data (
    timestamp TIMESTAMP,
    metric_name SYMBOL capacity 64 CACHE,
    metric_value DOUBLE,
    category SYMBOL capacity 32 CACHE,
    source SYMBOL capacity 32 CACHE,
    metadata STRING
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_alt_data_metric ON alternative_data(metric_name);

-- ============================================================================
-- System Metrics Table
-- ============================================================================
-- Stores system performance and health metrics

CREATE TABLE IF NOT EXISTS system_metrics (
    timestamp TIMESTAMP,
    metric_name SYMBOL capacity 128 CACHE,
    metric_value DOUBLE,
    component SYMBOL capacity 32 CACHE,
    hostname SYMBOL capacity 64 CACHE,
    tags STRING
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_system_metrics_component ON system_metrics(component);

-- ============================================================================
-- Data Quality Table
-- ============================================================================
-- Tracks data quality issues, gaps, and anomalies

CREATE TABLE IF NOT EXISTS data_quality (
    timestamp TIMESTAMP,
    symbol SYMBOL capacity 256 CACHE,
    exchange SYMBOL capacity 16 CACHE,
    issue_type SYMBOL capacity 32 CACHE,
    severity SYMBOL capacity 16 CACHE,
    description STRING,
    resolved BOOLEAN,
    resolved_at TIMESTAMP
) TIMESTAMP(timestamp) PARTITION BY DAY WAL;

CREATE INDEX IF NOT EXISTS idx_quality_unresolved ON data_quality(resolved);

-- ============================================================================
-- Schema Information
-- ============================================================================
-- Table to track schema version and migrations

CREATE TABLE IF NOT EXISTS schema_info (
    timestamp TIMESTAMP,
    version INT,
    description STRING,
    applied_by STRING
) TIMESTAMP(timestamp);

-- Insert initial schema version
INSERT INTO schema_info VALUES (now(), 1, 'Initial schema creation', 'janus-data-service');

-- ============================================================================
-- Useful Query Examples (commented out)
-- ============================================================================

-- Get latest trades for BTC
-- SELECT * FROM trades WHERE symbol = 'BTCUSD' ORDER BY timestamp DESC LIMIT 100;

-- Get 1-minute candles for the last hour
-- SELECT * FROM candles
-- WHERE symbol = 'BTCUSD'
--   AND timeframe = '1m'
--   AND timestamp > dateadd('h', -1, now())
-- ORDER BY timestamp DESC;

-- Get trade volume by symbol (last 24h)
-- SELECT
--     symbol,
--     count() as trade_count,
--     sum(amount) as total_volume,
--     avg(price) as avg_price
-- FROM trades
-- WHERE timestamp > dateadd('d', -1, now())
-- GROUP BY symbol
-- ORDER BY total_volume DESC;

-- Get price OHLC by hour
-- SELECT
--     timestamp,
--     first(price) as open,
--     max(price) as high,
--     min(price) as low,
--     last(price) as close,
--     sum(amount) as volume
-- FROM trades
-- WHERE symbol = 'BTCUSD'
-- SAMPLE BY 1h
-- ALIGN TO CALENDAR;

-- Get funding rate history
-- SELECT * FROM funding_rates
-- WHERE symbol = 'BTCUSD'
-- ORDER BY timestamp DESC
-- LIMIT 100;

-- Get active signals
-- SELECT * FROM signals
-- WHERE active = true
--   AND timestamp > dateadd('h', -1, now())
-- ORDER BY timestamp DESC;

-- ============================================================================
-- Schema Creation Complete
-- ============================================================================
-- All tables created successfully.
-- You can now start ingesting data!
--
-- Next steps:
-- 1. Start the data service: cargo run --release --bin janus-data
-- 2. Monitor data ingestion in QuestDB UI: http://localhost:9000
-- 3. Check metrics: curl http://localhost:8080/metrics
-- ============================================================================
