//! Shared traits for Project JANUS
//!
//! These traits define the interfaces that components must implement
//! to participate in the JANUS ecosystem.

/// Time provider abstraction for testability
pub trait TimeProvider: Send + Sync {
    /// Get current time in microseconds since epoch
    fn now(&self) -> u64;
}

/// System time provider using actual system clock
pub struct SystemTimeProvider;

impl TimeProvider for SystemTimeProvider {
    fn now(&self) -> u64 {
        use std::time::{SystemTime, UNIX_EPOCH};
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_micros() as u64
    }
}

use crate::errors::JanusError;
use crate::types::{Candle, Order, Tick};

/// Market data source - provides ticks from exchanges
pub trait MarketSource: Send + Sync {
    /// Connect to the market data feed
    fn connect(&mut self) -> Result<(), JanusError>;

    /// Disconnect from the market data feed
    fn disconnect(&mut self) -> Result<(), JanusError>;

    /// Check if connected
    fn is_connected(&self) -> bool;

    /// Get the next tick (blocking)
    fn next_tick(&mut self) -> Result<Option<Tick>, JanusError>;
}

/// Alpha model - generates trading signals from market state
pub trait AlphaModel: Send + Sync {
    /// Generate a signal from a candle
    fn generate_signal(&self, candle: &Candle) -> Result<Option<Signal>, JanusError>;

    /// Update the model with new experience
    fn update(&mut self, experience: &crate::types::Experience) -> Result<(), JanusError>;
}

/// Signal generated by an alpha model
#[derive(Debug, Clone)]
pub struct Signal {
    pub symbol: String,
    pub side: crate::types::OrderSide,
    pub strength: f64,   // 0.0 to 1.0
    pub confidence: f64, // 0.0 to 1.0
    pub predicted_duration_seconds: Option<u64>,
}

/// Risk engine - validates orders against risk constraints
pub trait RiskEngine: Send + Sync {
    /// Verify an order against risk limits
    fn verify_order(&self, order: &Order) -> Result<f64, JanusError>;
    // Returns compliance score: 0.0 (reject) to 1.0 (fully compliant)

    /// Check if an order violates any hard constraints
    fn is_valid(&self, order: &Order) -> bool;
}

/// Execution engine - routes orders to exchanges
pub trait ExecutionEngine: Send + Sync {
    /// Submit an order for execution
    fn submit_order(&mut self, order: Order) -> Result<uuid::Uuid, JanusError>;

    /// Cancel an order
    fn cancel_order(&mut self, order_id: uuid::Uuid) -> Result<(), JanusError>;

    /// Get order status
    fn get_order_status(&self, order_id: uuid::Uuid) -> Result<OrderStatus, JanusError>;
}

/// Order status
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrderStatus {
    Pending,
    Submitted,
    PartiallyFilled,
    Filled,
    Cancelled,
    Rejected,
}
