//! # Bollinger Squeeze Breakout Strategy
//!
//! Identifies periods of low volatility (Bollinger Band squeeze) and generates
//! breakout signals when price closes outside the bands after a squeeze period.
//!
//! ## How It Works
//!
//! 1. **Squeeze Detection**: Bollinger Band width falls below a configurable
//!    threshold (as a percentage of price). This indicates consolidation.
//!
//! 2. **Breakout Signal**: When price breaks above the upper band (bullish) or
//!    below the lower band (bearish) after being in a squeeze for at least
//!    `min_squeeze_candles`, a breakout signal is generated.
//!
//! 3. **Trend Confirmation**: EMA short/long crossover confirms the breakout
//!    direction. ADX strength adds confidence.
//!
//! 4. **ATR-Based Stops**: Stop loss is placed at the Bollinger middle band
//!    minus an ATR multiple. Take profit uses a larger ATR multiple.
//!
//! ## Regime Integration
//!
//! This strategy is most effective during transitions from ranging to trending
//! regimes. Use `should_trade_in_regime()` to gate activation:
//!
//! - **MeanReverting** → Yes (squeeze forms during ranging markets)
//! - **Uncertain** → Yes with reduced size (squeeze may be forming)
//! - **Trending** → No (breakout already happened)
//! - **Volatile** → No (not a true squeeze breakout)
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/swing.rs::BollingerSqueeze`, adapted for
//! the JANUS single-asset design, `janus-regime` indicator types, and
//! regime-aware position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::{ADX, ATR, BollingerBands, BollingerBandsValues, EMA};
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal Types
// ============================================================================

/// Signal generated by the Bollinger Squeeze Breakout strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SqueezeBreakoutSignal {
    /// Bullish breakout — price closed above upper Bollinger Band after squeeze.
    BuyBreakout,
    /// Bearish breakout — price closed below lower Bollinger Band after squeeze.
    SellBreakout,
    /// Currently in a squeeze (consolidation) — no action yet.
    Squeeze,
    /// No signal — not in squeeze and no breakout detected.
    Hold,
}

impl std::fmt::Display for SqueezeBreakoutSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SqueezeBreakoutSignal::BuyBreakout => write!(f, "BuyBreakout"),
            SqueezeBreakoutSignal::SellBreakout => write!(f, "SellBreakout"),
            SqueezeBreakoutSignal::Squeeze => write!(f, "Squeeze"),
            SqueezeBreakoutSignal::Hold => write!(f, "Hold"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the Bollinger Squeeze Breakout strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqueezeBreakoutConfig {
    // Bollinger Band parameters
    /// Bollinger Band lookback period (default: 20)
    pub bb_period: usize,
    /// Bollinger Band standard deviation multiplier (default: 2.0)
    pub bb_std_dev: f64,

    // Squeeze detection
    /// Squeeze threshold — Bollinger Band width (as percentage of price,
    /// where 3% = 3.0) below which the market is considered "in a squeeze"
    /// (default: 3.0). The BB width from `janus-regime` is already scaled
    /// as `(upper - lower) / middle * 100`.
    pub squeeze_threshold: f64,
    /// Minimum number of candles in squeeze before a breakout is valid
    /// (default: 5). Longer squeezes tend to produce more reliable breakouts.
    pub min_squeeze_candles: usize,

    // Trend confirmation
    /// Short EMA period for trend direction (default: 50)
    pub ema_short_period: usize,
    /// Long EMA period for trend direction (default: 200)
    pub ema_long_period: usize,
    /// ADX period for trend strength measurement (default: 14)
    pub adx_period: usize,
    /// ADX threshold — values above this indicate a trending market (default: 25.0)
    pub adx_threshold: f64,

    // Risk management
    /// ATR multiplier for stop loss distance (default: 2.0)
    pub atr_stop_multiplier: f64,
    /// ATR multiplier for take profit distance (default: 4.0)
    pub atr_tp_multiplier: f64,

    // Signal quality
    /// Minimum confidence score to emit a signal (default: 0.6)
    pub min_confidence: f64,
    /// Minimum candle body ratio (body_size / range) for a "strong" candle
    /// (default: 0.6). Breakouts on strong candles get extra confidence.
    pub min_body_ratio: f64,
}

impl Default for SqueezeBreakoutConfig {
    fn default() -> Self {
        Self {
            bb_period: 20,
            bb_std_dev: 2.0,
            squeeze_threshold: 3.0,
            min_squeeze_candles: 5,
            ema_short_period: 50,
            ema_long_period: 200,
            adx_period: 14,
            adx_threshold: 25.0,
            atr_stop_multiplier: 2.0,
            atr_tp_multiplier: 4.0,
            min_confidence: 0.6,
            min_body_ratio: 0.6,
        }
    }
}

impl SqueezeBreakoutConfig {
    /// Aggressive config for crypto — tighter squeeze, lower confidence threshold.
    pub fn crypto_aggressive() -> Self {
        Self {
            squeeze_threshold: 2.5,
            min_squeeze_candles: 4,
            atr_stop_multiplier: 1.5,
            atr_tp_multiplier: 3.5,
            min_confidence: 0.55,
            min_body_ratio: 0.55,
            ..Default::default()
        }
    }

    /// Conservative config — requires longer squeeze, higher confidence.
    pub fn conservative() -> Self {
        Self {
            squeeze_threshold: 3.5,
            min_squeeze_candles: 8,
            atr_stop_multiplier: 2.5,
            atr_tp_multiplier: 5.0,
            min_confidence: 0.70,
            min_body_ratio: 0.65,
            ..Default::default()
        }
    }
}

// ============================================================================
// Result
// ============================================================================

/// Detailed result from a Bollinger Squeeze Breakout strategy update.
#[derive(Debug, Clone)]
pub struct SqueezeBreakoutResult {
    /// The signal produced.
    pub signal: SqueezeBreakoutSignal,
    /// Bollinger Band values at the time of the signal (if available).
    pub bb_values: Option<BollingerBandsValues>,
    /// Current ATR value (if available).
    pub atr: Option<f64>,
    /// Current ADX value (if available).
    pub adx: Option<f64>,
    /// Whether the strategy is currently in a squeeze.
    pub in_squeeze: bool,
    /// How many candles the current (or most recent) squeeze lasted.
    pub squeeze_duration: usize,
    /// Confidence score for the signal (0.0–1.0).
    pub confidence: f64,
    /// Computed stop loss price (only set on breakout signals).
    pub stop_loss: Option<f64>,
    /// Computed take profit price (only set on breakout signals).
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// Strategy
// ============================================================================

/// Bollinger Squeeze Breakout Strategy
///
/// Detects low-volatility squeeze periods via Bollinger Band width and
/// generates breakout signals when price escapes the bands after a squeeze.
/// Uses EMA trend direction and ADX strength for confirmation.
///
/// This is a single-asset strategy — instantiate one per symbol.
#[derive(Debug)]
pub struct SqueezeBreakoutStrategy {
    config: SqueezeBreakoutConfig,

    // Indicators
    bb: BollingerBands,
    ema_short: EMA,
    ema_long: EMA,
    adx: ADX,
    atr: ATR,

    // Squeeze tracking
    in_squeeze: bool,
    squeeze_candles: usize,
    /// True if we were in a squeeze on the *previous* candle (for transition detection).
    was_in_squeeze: bool,
    /// Duration of the squeeze that just ended (if any).
    last_squeeze_duration: usize,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<SqueezeBreakoutSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Last computed values
    last_bb: Option<BollingerBandsValues>,
    last_adx: Option<f64>,
    last_atr: Option<f64>,
    last_signal: SqueezeBreakoutSignal,
    candle_count: usize,
}

impl SqueezeBreakoutStrategy {
    /// Create a new Bollinger Squeeze Breakout strategy with the given config.
    pub fn new(config: SqueezeBreakoutConfig) -> Self {
        Self {
            bb: BollingerBands::new(config.bb_period, config.bb_std_dev),
            ema_short: EMA::new(config.ema_short_period),
            ema_long: EMA::new(config.ema_long_period),
            adx: ADX::new(config.adx_period),
            atr: ATR::new(config.adx_period), // ATR uses same period as ADX by convention
            config,
            in_squeeze: false,
            squeeze_candles: 0,
            was_in_squeeze: false,
            last_squeeze_duration: 0,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            last_bb: None,
            last_adx: None,
            last_atr: None,
            last_signal: SqueezeBreakoutSignal::Hold,
            candle_count: 0,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(SqueezeBreakoutConfig::default())
    }

    /// Update the strategy with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> SqueezeBreakoutSignal {
        self.update_ohlc(candle.open, candle.high, candle.low, candle.close)
            .signal
    }

    /// Update the strategy with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(
        &mut self,
        candle: &janus_models::Candle,
    ) -> SqueezeBreakoutResult {
        self.update_ohlc(candle.open, candle.high, candle.low, candle.close)
    }

    /// Update with raw OHLC values and return a detailed result.
    pub fn update_ohlc(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
    ) -> SqueezeBreakoutResult {
        self.candle_count += 1;

        // Update all indicators
        self.ema_short.update(close);
        self.ema_long.update(close);
        self.adx.update(high, low, close);
        self.atr.update(high, low, close);

        // BollingerBands::update takes a single price (close)
        let bb_values = self.bb.update(close);
        self.last_bb = bb_values;
        self.last_adx = self.adx.value();
        self.last_atr = self.atr.value();

        // Save pre-update squeeze state for transition detection
        self.was_in_squeeze = self.in_squeeze;
        let prev_squeeze_duration = self.squeeze_candles;

        // Update squeeze detection
        if let Some(ref bbv) = bb_values {
            let previously_in_squeeze = self.in_squeeze;
            self.in_squeeze = bbv.width < self.config.squeeze_threshold;

            if self.in_squeeze {
                self.squeeze_candles += 1;
            } else if previously_in_squeeze {
                // Just exited squeeze — record the duration
                self.last_squeeze_duration = self.squeeze_candles;
                self.squeeze_candles = 0;
            }
        }

        // Not enough data yet
        if !self.bb.is_ready() || !self.atr.is_ready() {
            let signal = if self.in_squeeze {
                SqueezeBreakoutSignal::Squeeze
            } else {
                SqueezeBreakoutSignal::Hold
            };
            self.last_signal = signal;
            return SqueezeBreakoutResult {
                signal,
                bb_values,
                atr: self.last_atr,
                adx: self.last_adx,
                in_squeeze: self.in_squeeze,
                squeeze_duration: self.squeeze_candles,
                confidence: 0.0,
                stop_loss: None,
                take_profit: None,
                reason: "Hold: Indicators warming up".to_string(),
            };
        }

        // Check for exits if in position
        if self.in_position {
            let signal = self.check_exit(close);
            if signal != SqueezeBreakoutSignal::Hold {
                return self.make_result(signal, close, open, high, low);
            }
            // Still in position, no exit triggered
            return self.make_result(SqueezeBreakoutSignal::Hold, close, open, high, low);
        }

        // Check for breakout entry
        // Conditions: was in squeeze for min_squeeze_candles, now breaking out
        if self.was_in_squeeze
            && prev_squeeze_duration >= self.config.min_squeeze_candles
            && !self.in_squeeze
            && let Some(ref bbv) = bb_values
        {
            let atr = self.last_atr.unwrap_or(close * 0.02);
            let body_size = (close - open).abs();
            let range = high - low;
            let body_ratio = if range > 0.0 { body_size / range } else { 0.0 };
            let is_bullish = close > open;
            let is_bearish = close < open;

            // EMA trend direction
            let ema_short_val = self.ema_short.value();
            let ema_long_val = self.ema_long.value();
            let ema_bullish = match (ema_short_val, ema_long_val) {
                (Some(s), Some(l)) => s > l,
                _ => false,
            };
            let ema_bearish = match (ema_short_val, ema_long_val) {
                (Some(s), Some(l)) => s < l,
                _ => false,
            };

            let adx_val = self.last_adx.unwrap_or(0.0);

            // === BULLISH BREAKOUT ===
            if close > bbv.upper && is_bullish {
                let mut confidence = 0.5;
                if ema_bullish {
                    confidence += 0.20;
                }
                if prev_squeeze_duration > 10 {
                    confidence += 0.10; // Longer squeeze = more reliable
                }
                if body_ratio > self.config.min_body_ratio {
                    confidence += 0.10; // Strong candle body
                }
                if adx_val > self.config.adx_threshold {
                    confidence += 0.05; // Trend strength confirmation
                }

                if confidence >= self.config.min_confidence {
                    let stop = bbv.middle - atr * self.config.atr_stop_multiplier;
                    let tp = close + atr * self.config.atr_tp_multiplier;

                    self.enter_position(SqueezeBreakoutSignal::BuyBreakout, close, stop, tp);

                    let signal = SqueezeBreakoutSignal::BuyBreakout;
                    self.last_signal = signal;
                    return SqueezeBreakoutResult {
                        signal,
                        bb_values: self.last_bb,
                        atr: self.last_atr,
                        adx: self.last_adx,
                        in_squeeze: false,
                        squeeze_duration: prev_squeeze_duration,
                        confidence,
                        stop_loss: Some(stop),
                        take_profit: Some(tp),
                        reason: format!(
                            "BuyBreakout: price {:.2} > upper BB {:.2}, squeeze {} candles, conf {:.0}%",
                            close,
                            bbv.upper,
                            prev_squeeze_duration,
                            confidence * 100.0
                        ),
                    };
                }
            }

            // === BEARISH BREAKOUT ===
            if close < bbv.lower && is_bearish {
                let mut confidence = 0.5;
                if ema_bearish {
                    confidence += 0.20;
                }
                if prev_squeeze_duration > 10 {
                    confidence += 0.10;
                }
                if body_ratio > self.config.min_body_ratio {
                    confidence += 0.10;
                }
                if adx_val > self.config.adx_threshold {
                    confidence += 0.05;
                }

                if confidence >= self.config.min_confidence {
                    let stop = bbv.middle + atr * self.config.atr_stop_multiplier;
                    let tp = close - atr * self.config.atr_tp_multiplier;

                    self.enter_position(SqueezeBreakoutSignal::SellBreakout, close, stop, tp);

                    let signal = SqueezeBreakoutSignal::SellBreakout;
                    self.last_signal = signal;
                    return SqueezeBreakoutResult {
                        signal,
                        bb_values: self.last_bb,
                        atr: self.last_atr,
                        adx: self.last_adx,
                        in_squeeze: false,
                        squeeze_duration: prev_squeeze_duration,
                        confidence,
                        stop_loss: Some(stop),
                        take_profit: Some(tp),
                        reason: format!(
                            "SellBreakout: price {:.2} < lower BB {:.2}, squeeze {} candles, conf {:.0}%",
                            close,
                            bbv.lower,
                            prev_squeeze_duration,
                            confidence * 100.0
                        ),
                    };
                }
            }
        }

        // Currently in squeeze — report it
        if self.in_squeeze {
            let signal = SqueezeBreakoutSignal::Squeeze;
            self.last_signal = signal;
            return SqueezeBreakoutResult {
                signal,
                bb_values,
                atr: self.last_atr,
                adx: self.last_adx,
                in_squeeze: true,
                squeeze_duration: self.squeeze_candles,
                confidence: 0.0,
                stop_loss: None,
                take_profit: None,
                reason: format!(
                    "Squeeze: BB width {:.4} < threshold {:.4}, {} candles",
                    bb_values.as_ref().map(|b| b.width).unwrap_or(0.0),
                    self.config.squeeze_threshold,
                    self.squeeze_candles,
                ),
            };
        }

        // No signal
        let signal = SqueezeBreakoutSignal::Hold;
        self.last_signal = signal;
        self.make_result(signal, close, open, high, low)
    }

    /// Update with HLC values only (open defaults to close, matching tick-aggregated
    /// candles from RegimeManager which don't have distinct open).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> SqueezeBreakoutResult {
        // Use close as open approximation for tick-aggregated candles
        self.update_ohlc(close, high, low, close)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// Squeeze breakouts form during ranging/mean-reverting markets and fire
    /// when the market transitions. The strategy should NOT be active during
    /// already-trending or highly volatile regimes.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(
            regime,
            MarketRegime::MeanReverting | MarketRegime::Uncertain
        )
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    ///
    /// Returns `Some(factor)` if the regime is suitable, `None` otherwise.
    /// Factor ranges from 0.0 to 1.0.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::MeanReverting => {
                // Squeeze breakouts from ranging → trending are ideal
                Some(confidence.clamp(0.4, 1.0))
            }
            MarketRegime::Uncertain => {
                // May be transitioning — allow with reduced size
                if confidence < 0.5 {
                    Some(0.30)
                } else {
                    Some(0.20)
                }
            }
            _ => None,
        }
    }

    // ========================================================================
    // Position management
    // ========================================================================

    fn enter_position(&mut self, side: SqueezeBreakoutSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(&mut self, close: f64) -> SqueezeBreakoutSignal {
        let stop = self.stop_loss.unwrap_or(0.0);
        let tp = self.take_profit.unwrap_or(f64::MAX);

        match self.entry_side {
            Some(SqueezeBreakoutSignal::BuyBreakout) => {
                // Stop loss hit
                if close <= stop {
                    self.exit_position();
                    return SqueezeBreakoutSignal::SellBreakout; // Exit signal
                }
                // Take profit hit
                if close >= tp {
                    self.exit_position();
                    return SqueezeBreakoutSignal::SellBreakout;
                }
            }
            Some(SqueezeBreakoutSignal::SellBreakout) => {
                if close >= stop {
                    self.exit_position();
                    return SqueezeBreakoutSignal::BuyBreakout;
                }
                if close <= tp {
                    self.exit_position();
                    return SqueezeBreakoutSignal::BuyBreakout;
                }
            }
            _ => {}
        }

        SqueezeBreakoutSignal::Hold
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(
        &self,
        signal: SqueezeBreakoutSignal,
        _close: f64,
        _open: f64,
        _high: f64,
        _low: f64,
    ) -> SqueezeBreakoutResult {
        SqueezeBreakoutResult {
            signal,
            bb_values: self.last_bb,
            atr: self.last_atr,
            adx: self.last_adx,
            in_squeeze: self.in_squeeze,
            squeeze_duration: self.squeeze_candles,
            confidence: 0.0,
            stop_loss: self.stop_loss,
            take_profit: self.take_profit,
            reason: match signal {
                SqueezeBreakoutSignal::Hold => "Hold: No signal".to_string(),
                SqueezeBreakoutSignal::Squeeze => {
                    format!("Squeeze: {} candles", self.squeeze_candles,)
                }
                _ => format!("{}", signal),
            },
        }
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Reset all strategy state.
    pub fn reset(&mut self) {
        self.bb.reset();
        self.ema_short.reset();
        self.ema_long.reset();
        self.adx.reset();
        self.atr.reset();
        self.in_squeeze = false;
        self.squeeze_candles = 0;
        self.was_in_squeeze = false;
        self.last_squeeze_duration = 0;
        self.exit_position();
        self.last_bb = None;
        self.last_adx = None;
        self.last_atr = None;
        self.last_signal = SqueezeBreakoutSignal::Hold;
        self.candle_count = 0;
    }

    /// Whether the strategy has enough data to produce meaningful signals.
    pub fn is_ready(&self) -> bool {
        self.bb.is_ready() && self.atr.is_ready()
    }

    /// Whether the strategy is currently tracking an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// Whether the market is currently in a squeeze.
    pub fn is_in_squeeze(&self) -> bool {
        self.in_squeeze
    }

    /// Number of consecutive candles in the current squeeze.
    pub fn squeeze_duration(&self) -> usize {
        self.squeeze_candles
    }

    /// Duration of the most recently completed squeeze.
    pub fn last_completed_squeeze_duration(&self) -> usize {
        self.last_squeeze_duration
    }

    /// Last computed Bollinger Band values.
    pub fn last_bb_values(&self) -> Option<BollingerBandsValues> {
        self.last_bb
    }

    /// Last computed ADX value.
    pub fn last_adx(&self) -> Option<f64> {
        self.last_adx
    }

    /// Last computed ATR value.
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// Current entry price (if in position).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Current stop loss (if in position).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Current take profit (if in position).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// The last signal emitted.
    pub fn last_signal(&self) -> SqueezeBreakoutSignal {
        self.last_signal
    }

    /// Number of candles processed.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Reference to the current configuration.
    pub fn config(&self) -> &SqueezeBreakoutConfig {
        &self.config
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use janus_regime::{MarketRegime, TrendDirection};

    /// Feed a steady stream of similar-priced candles to warm up indicators.
    fn warm_up(strategy: &mut SqueezeBreakoutStrategy, center: f64, count: usize) {
        for i in 0..count {
            let phase = (i as f64) * std::f64::consts::PI / 7.0;
            let high = center + 50.0 + 20.0 * phase.sin().abs();
            let low = center - 50.0 - 20.0 * phase.cos().abs();
            let open = center + 10.0 * phase.cos();
            let close = center + 30.0 * phase.sin();
            strategy.update_ohlc(open, high, low, close);
        }
    }

    /// Feed a tight-range squeeze pattern.
    #[allow(dead_code)]
    fn feed_squeeze(strategy: &mut SqueezeBreakoutStrategy, center: f64, count: usize) {
        for i in 0..count {
            let tiny = (i as f64) * 0.01;
            let open = center - 0.5 + tiny;
            let high = center + 1.0 + tiny;
            let low = center - 1.0 + tiny;
            let close = center + 0.5 + tiny;
            strategy.update_ohlc(open, high, low, close);
        }
    }

    // ── Config tests ──

    #[test]
    fn test_default_config() {
        let config = SqueezeBreakoutConfig::default();
        assert_eq!(config.bb_period, 20);
        assert!((config.bb_std_dev - 2.0).abs() < f64::EPSILON);
        assert!((config.squeeze_threshold - 3.0).abs() < f64::EPSILON);
        assert_eq!(config.min_squeeze_candles, 5);
        assert!((config.min_confidence - 0.6).abs() < f64::EPSILON);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = SqueezeBreakoutConfig::crypto_aggressive();
        assert!(config.squeeze_threshold < SqueezeBreakoutConfig::default().squeeze_threshold);
        assert!(config.min_squeeze_candles < SqueezeBreakoutConfig::default().min_squeeze_candles);
        assert!(config.min_confidence < SqueezeBreakoutConfig::default().min_confidence);
    }

    #[test]
    fn test_conservative_config() {
        let config = SqueezeBreakoutConfig::conservative();
        assert!(config.squeeze_threshold > SqueezeBreakoutConfig::default().squeeze_threshold);
        assert!(config.min_squeeze_candles > SqueezeBreakoutConfig::default().min_squeeze_candles);
        assert!(config.min_confidence > SqueezeBreakoutConfig::default().min_confidence);
    }

    // ── Strategy creation ──

    #[test]
    fn test_strategy_creation() {
        let strategy = SqueezeBreakoutStrategy::with_defaults();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert!(!strategy.is_in_squeeze());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.last_signal(), SqueezeBreakoutSignal::Hold);
    }

    #[test]
    fn test_warmup_hold() {
        let mut strategy = SqueezeBreakoutStrategy::with_defaults();

        // During warmup, should produce Hold or Squeeze
        for i in 0..10 {
            let price = 50000.0 + (i as f64) * 10.0;
            let result = strategy.update_ohlc(price - 5.0, price + 20.0, price - 20.0, price);
            assert!(
                result.signal == SqueezeBreakoutSignal::Hold
                    || result.signal == SqueezeBreakoutSignal::Squeeze,
                "During warmup should be Hold or Squeeze, got: {:?}",
                result.signal
            );
        }
        assert_eq!(strategy.candle_count(), 10);
    }

    #[test]
    fn test_becomes_ready_after_warmup() {
        let mut strategy = SqueezeBreakoutStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 50);
        assert!(
            strategy.is_ready(),
            "Strategy should be ready after 50 candles"
        );
    }

    // ── Regime gating ──

    #[test]
    fn test_should_trade_in_mean_reverting() {
        assert!(SqueezeBreakoutStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_trade_in_uncertain() {
        assert!(SqueezeBreakoutStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_should_not_trade_in_trending() {
        assert!(!SqueezeBreakoutStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
        assert!(!SqueezeBreakoutStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_not_trade_in_volatile() {
        assert!(!SqueezeBreakoutStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_regime_size_factor_mean_reverting() {
        let factor = SqueezeBreakoutStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.9);
        assert!(factor.is_some());
        assert!(factor.unwrap() >= 0.4);
    }

    #[test]
    fn test_regime_size_factor_uncertain() {
        let factor = SqueezeBreakoutStrategy::regime_size_factor(&MarketRegime::Uncertain, 0.3);
        assert!(factor.is_some());
        assert!(factor.unwrap() <= 0.5);
    }

    #[test]
    fn test_regime_size_factor_volatile_is_none() {
        let factor = SqueezeBreakoutStrategy::regime_size_factor(&MarketRegime::Volatile, 0.9);
        assert!(factor.is_none());
    }

    #[test]
    fn test_regime_size_factor_trending_is_none() {
        let factor = SqueezeBreakoutStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.9,
        );
        assert!(factor.is_none());
    }

    // ── Signal output ──

    #[test]
    fn test_signal_display() {
        assert_eq!(
            format!("{}", SqueezeBreakoutSignal::BuyBreakout),
            "BuyBreakout"
        );
        assert_eq!(
            format!("{}", SqueezeBreakoutSignal::SellBreakout),
            "SellBreakout"
        );
        assert_eq!(format!("{}", SqueezeBreakoutSignal::Squeeze), "Squeeze");
        assert_eq!(format!("{}", SqueezeBreakoutSignal::Hold), "Hold");
    }

    #[test]
    fn test_signal_serialization() {
        let json = serde_json::to_string(&SqueezeBreakoutSignal::BuyBreakout).unwrap();
        let deserialized: SqueezeBreakoutSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, SqueezeBreakoutSignal::BuyBreakout);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = SqueezeBreakoutConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: SqueezeBreakoutConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.bb_period, config.bb_period);
        assert!((deserialized.squeeze_threshold - config.squeeze_threshold).abs() < f64::EPSILON);
    }

    // ── Reset ──

    #[test]
    fn test_reset_clears_state() {
        let mut strategy = SqueezeBreakoutStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 50);

        assert!(strategy.is_ready());
        assert!(strategy.candle_count() > 0);

        strategy.reset();

        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert!(!strategy.is_in_squeeze());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.last_signal(), SqueezeBreakoutSignal::Hold);
        assert!(strategy.last_bb_values().is_none());
        assert!(strategy.last_adx().is_none());
        assert!(strategy.last_atr().is_none());
    }

    // ── Squeeze detection ──

    #[test]
    fn test_squeeze_detection_on_tight_range() {
        let mut strategy = SqueezeBreakoutStrategy::new(SqueezeBreakoutConfig {
            bb_period: 20,
            bb_std_dev: 2.0,
            squeeze_threshold: 5.0, // Generous threshold for testing (5% of price)
            min_squeeze_candles: 3,
            ..Default::default()
        });

        // Warm up with normal volatility
        warm_up(&mut strategy, 1000.0, 25);

        // Now feed very tight-range candles
        for i in 0..20 {
            let tiny = (i as f64) * 0.001;
            let result = strategy.update_ohlc(
                1000.0 - 0.1 + tiny,
                1000.0 + 0.5 + tiny,
                1000.0 - 0.5 + tiny,
                1000.0 + 0.1 + tiny,
            );
            // After enough tight candles, should detect squeeze
            if strategy.is_in_squeeze() {
                assert!(
                    result.signal == SqueezeBreakoutSignal::Squeeze
                        || result.signal == SqueezeBreakoutSignal::Hold,
                    "In squeeze should report Squeeze or Hold, got: {:?}",
                    result.signal
                );
            }
        }
    }

    // ── HLC interface ──

    #[test]
    fn test_hlc_interface() {
        let mut strategy = SqueezeBreakoutStrategy::with_defaults();
        let result = strategy.update_hlc(50100.0, 49900.0, 50050.0);
        assert!(
            result.signal == SqueezeBreakoutSignal::Hold
                || result.signal == SqueezeBreakoutSignal::Squeeze
        );
        assert_eq!(strategy.candle_count(), 1);
    }

    // ── Accessors ──

    #[test]
    fn test_config_accessor() {
        let config = SqueezeBreakoutConfig::conservative();
        let strategy = SqueezeBreakoutStrategy::new(config.clone());
        assert_eq!(
            strategy.config().min_squeeze_candles,
            config.min_squeeze_candles
        );
        assert!(
            (strategy.config().squeeze_threshold - config.squeeze_threshold).abs() < f64::EPSILON
        );
    }

    #[test]
    fn test_not_in_position_initially() {
        let strategy = SqueezeBreakoutStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    // ── Stress test ──

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = SqueezeBreakoutStrategy::with_defaults();

        // Feed 500 candles with varying patterns — no panics expected
        for i in 0..500 {
            let phase = (i as f64) * std::f64::consts::PI / 10.0;
            let base = 50000.0 + 500.0 * phase.sin();
            let volatility = 50.0 + 200.0 * ((i as f64) * 0.03).sin().abs();
            let open = base - volatility * 0.3;
            let high = base + volatility;
            let low = base - volatility;
            let close = base + volatility * 0.4 * phase.cos();

            let result = strategy.update_ohlc(open, high, low, close);
            assert!(
                matches!(
                    result.signal,
                    SqueezeBreakoutSignal::BuyBreakout
                        | SqueezeBreakoutSignal::SellBreakout
                        | SqueezeBreakoutSignal::Squeeze
                        | SqueezeBreakoutSignal::Hold
                ),
                "Signal should be a valid variant"
            );
        }

        assert_eq!(strategy.candle_count(), 500);
    }

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = SqueezeBreakoutStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 30);

        let result = strategy.update_ohlc(50000.0, 50100.0, 49900.0, 50050.0);
        assert!(
            !result.reason.is_empty(),
            "Reason string should be populated"
        );
    }

    #[test]
    fn test_squeeze_duration_tracking() {
        let mut strategy = SqueezeBreakoutStrategy::new(SqueezeBreakoutConfig {
            bb_period: 20,
            squeeze_threshold: 10.0, // Very generous for testing (10% of price)
            min_squeeze_candles: 2,
            ..Default::default()
        });

        // Warm up
        warm_up(&mut strategy, 1000.0, 25);

        // Feed tight candles and track squeeze
        let mut max_squeeze = 0;
        for i in 0..30 {
            let tiny = (i as f64) * 0.0001;
            strategy.update_ohlc(
                1000.0 + tiny,
                1000.0 + 0.1 + tiny,
                1000.0 - 0.1 + tiny,
                1000.0 + 0.05 + tiny,
            );
            if strategy.is_in_squeeze() {
                max_squeeze = max_squeeze.max(strategy.squeeze_duration());
            }
        }
        // After enough tight candles, squeeze should have been detected for
        // at least a few candles (exact count depends on BB warmup)
        // This is a soft check since the exact squeeze detection depends on
        // how the BB width compares to the threshold
    }
}
