//! # EMA Ribbon Scalper Strategy
//!
//! Uses an 8/13/21 EMA ribbon to identify trend direction and enters on
//! pullbacks to the ribbon with volume confirmation. ATR-based stop losses
//! and take profits.
//!
//! ## How It Works
//!
//! 1. **Ribbon Direction**: All three EMAs (8, 13, 21) are checked for alignment.
//!    Bullish when 8 > 13 > 21, bearish when 8 < 13 < 21.
//!
//! 2. **Pullback Detection**: Price pulls back to touch or cross the middle EMA
//!    (13) but remains on the correct side of the slow EMA (21).
//!
//! 3. **Volume Confirmation**: Volume must be above a configurable multiple of
//!    the rolling average to confirm institutional interest.
//!
//! 4. **Candle Confirmation**: The entry candle must be directionally aligned
//!    (bullish candle for long, bearish for short) with a strong body.
//!
//! 5. **ATR-Based Stops**: Stop loss and take profit are placed at ATR multiples
//!    from entry.
//!
//! ## Regime Integration
//!
//! This strategy is designed for trending markets. Use `should_trade_in_regime()`
//! to gate activation:
//!
//! - **Trending(Bullish/Bearish)** → Yes (primary use case)
//! - **Volatile** → Yes with reduced size (momentum may carry)
//! - **MeanReverting** → No (ribbon signals are noise in ranging markets)
//! - **Uncertain** → No (wait for clarity)
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/scalping.rs::EmaRibbonScalper`, adapted for
//! the JANUS single-asset design, `janus-regime` indicator types, and
//! regime-aware position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::{ATR, EMA};
use janus_regime::types::TrendDirection;
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal Types
// ============================================================================

/// Signal generated by the EMA Ribbon Scalper strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EmaRibbonSignal {
    /// Enter long — bullish ribbon pullback with volume.
    Buy,
    /// Enter short / exit long — bearish ribbon pullback with volume.
    Sell,
    /// No action.
    Hold,
}

impl std::fmt::Display for EmaRibbonSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmaRibbonSignal::Buy => write!(f, "BUY"),
            EmaRibbonSignal::Sell => write!(f, "SELL"),
            EmaRibbonSignal::Hold => write!(f, "HOLD"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the EMA Ribbon Scalper strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmaRibbonConfig {
    /// Fast EMA period (default: 8).
    pub fast_ema_period: usize,

    /// Mid EMA period (default: 13).
    pub mid_ema_period: usize,

    /// Slow EMA period (default: 21).
    pub slow_ema_period: usize,

    /// ATR period for volatility measurement (default: 14).
    pub atr_period: usize,

    /// ATR multiplier for stop-loss distance (default: 1.5).
    pub atr_stop_multiplier: f64,

    /// ATR multiplier for take-profit distance (default: 3.0).
    pub atr_tp_multiplier: f64,

    /// Rolling volume lookback period for spike detection (default: 20).
    pub volume_period: usize,

    /// Minimum volume multiplier (vs rolling average) to confirm entry
    /// (default: 1.3). Set lower than VWAP since trend context provides
    /// additional confirmation.
    pub min_volume_multiplier: f64,

    /// Minimum confidence score to emit a signal (default: 0.55).
    pub min_confidence: f64,

    /// Minimum candle body ratio (body / range) to count as "strong" candle
    /// (default: 0.45).
    pub min_body_ratio: f64,

    /// Pullback tolerance — how far past the mid EMA the price can go, as a
    /// fraction (default: 0.002 = 0.2%). For a long setup, `price <= mid_ema * (1 + tolerance)`.
    pub pullback_tolerance: f64,

    /// Minimum number of candles before the strategy is ready (default: 25).
    pub warmup_candles: usize,
}

impl Default for EmaRibbonConfig {
    fn default() -> Self {
        Self {
            fast_ema_period: 8,
            mid_ema_period: 13,
            slow_ema_period: 21,
            atr_period: 14,
            atr_stop_multiplier: 1.5,
            atr_tp_multiplier: 3.0,
            volume_period: 20,
            min_volume_multiplier: 1.3,
            min_confidence: 0.55,
            min_body_ratio: 0.45,
            pullback_tolerance: 0.002,
            warmup_candles: 25,
        }
    }
}

impl EmaRibbonConfig {
    /// Aggressive config for crypto — tighter tolerance, lower thresholds.
    pub fn crypto_aggressive() -> Self {
        Self {
            atr_stop_multiplier: 1.2,
            atr_tp_multiplier: 2.5,
            min_volume_multiplier: 1.2,
            min_confidence: 0.50,
            min_body_ratio: 0.40,
            pullback_tolerance: 0.003,
            warmup_candles: 20,
            ..Default::default()
        }
    }

    /// Conservative config — wider stops, higher confidence required.
    pub fn conservative() -> Self {
        Self {
            atr_stop_multiplier: 2.0,
            atr_tp_multiplier: 4.0,
            min_volume_multiplier: 1.5,
            min_confidence: 0.65,
            min_body_ratio: 0.50,
            pullback_tolerance: 0.001,
            warmup_candles: 30,
            ..Default::default()
        }
    }
}

// ============================================================================
// Detailed Result
// ============================================================================

/// Detailed result from an EMA Ribbon Scalper strategy update.
#[derive(Debug, Clone)]
pub struct EmaRibbonResult {
    /// The signal produced.
    pub signal: EmaRibbonSignal,
    /// Current fast EMA value (if available).
    pub fast_ema: Option<f64>,
    /// Current mid EMA value (if available).
    pub mid_ema: Option<f64>,
    /// Current slow EMA value (if available).
    pub slow_ema: Option<f64>,
    /// Whether the ribbon is aligned bullish (fast > mid > slow).
    pub ribbon_bullish: bool,
    /// Whether the ribbon is aligned bearish (fast < mid < slow).
    pub ribbon_bearish: bool,
    /// Current ATR value (if available).
    pub atr: Option<f64>,
    /// Volume multiplier relative to rolling average.
    pub volume_multiplier: f64,
    /// Confidence score (0.0–1.0).
    pub confidence: f64,
    /// Computed stop-loss price (only set on buy/sell signals).
    pub stop_loss: Option<f64>,
    /// Computed take-profit price (only set on buy/sell signals).
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// Volume Analyzer (internal)
// ============================================================================

/// Rolling volume analyzer for spike detection.
#[derive(Debug)]
struct VolumeAnalyzer {
    period: usize,
    volumes: Vec<f64>,
}

impl VolumeAnalyzer {
    fn new(period: usize) -> Self {
        Self {
            period: period.max(1),
            volumes: Vec::with_capacity(period),
        }
    }

    /// Push a new volume value. Returns the multiplier (volume / rolling avg).
    fn update(&mut self, volume: f64) -> f64 {
        let avg = self.average();

        self.volumes.push(volume);
        if self.volumes.len() > self.period {
            self.volumes.remove(0);
        }

        if avg > 0.0 { volume / avg } else { 1.0 }
    }

    /// Rolling average volume.
    fn average(&self) -> f64 {
        if self.volumes.is_empty() {
            0.0
        } else {
            self.volumes.iter().sum::<f64>() / self.volumes.len() as f64
        }
    }
}

// ============================================================================
// Strategy
// ============================================================================

/// EMA Ribbon Scalper Strategy
///
/// Trend-following scalper using 8/13/21 EMA ribbon alignment with pullback
/// entries. Single-asset — instantiate one per symbol.
#[derive(Debug)]
pub struct EmaRibbonScalperStrategy {
    config: EmaRibbonConfig,

    // Indicators
    fast_ema: EMA,
    mid_ema: EMA,
    slow_ema: EMA,
    atr: ATR,
    volume_analyzer: VolumeAnalyzer,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<EmaRibbonSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Last computed values
    last_fast_ema: Option<f64>,
    last_mid_ema: Option<f64>,
    last_slow_ema: Option<f64>,
    last_atr: Option<f64>,
    last_signal: EmaRibbonSignal,
    candle_count: usize,

    // HTF trend bias (optional — set externally from higher-timeframe analysis)
    htf_trend: Option<TrendDirection>,
}

impl EmaRibbonScalperStrategy {
    /// Create a new EMA Ribbon Scalper strategy with the given config.
    pub fn new(config: EmaRibbonConfig) -> Self {
        let fast_ema = EMA::new(config.fast_ema_period);
        let mid_ema = EMA::new(config.mid_ema_period);
        let slow_ema = EMA::new(config.slow_ema_period);
        let atr = ATR::new(config.atr_period);
        let volume_analyzer = VolumeAnalyzer::new(config.volume_period);

        Self {
            fast_ema,
            mid_ema,
            slow_ema,
            atr,
            volume_analyzer,
            config,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            last_fast_ema: None,
            last_mid_ema: None,
            last_slow_ema: None,
            last_atr: None,
            last_signal: EmaRibbonSignal::Hold,
            candle_count: 0,
            htf_trend: None,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(EmaRibbonConfig::default())
    }

    /// Set higher-timeframe trend bias. When set, long setups are only taken
    /// if HTF is bullish (or flat), and short setups only if HTF is bearish
    /// (or flat).
    pub fn set_htf_trend(&mut self, trend: TrendDirection) {
        self.htf_trend = Some(trend);
    }

    /// Clear the HTF trend bias.
    pub fn clear_htf_trend(&mut self) {
        self.htf_trend = None;
    }

    /// Update with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> EmaRibbonSignal {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
        .signal
    }

    /// Update with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(&mut self, candle: &janus_models::Candle) -> EmaRibbonResult {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
    }

    /// Main update with OHLCV values — returns a detailed result.
    pub fn update_ohlcv(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
    ) -> EmaRibbonResult {
        self.candle_count += 1;

        // Update indicators
        self.fast_ema.update(close);
        self.mid_ema.update(close);
        self.slow_ema.update(close);
        self.atr.update(high, low, close);
        let vol_mult = self.volume_analyzer.update(volume);

        self.last_fast_ema = self.fast_ema.value();
        self.last_mid_ema = self.mid_ema.value();
        self.last_slow_ema = self.slow_ema.value();
        self.last_atr = self.atr.value();

        // Not ready yet?
        if self.candle_count < self.config.warmup_candles {
            return self.make_result(
                EmaRibbonSignal::Hold,
                vol_mult,
                0.0,
                "Warming up".to_string(),
            );
        }

        let fast = match self.last_fast_ema {
            Some(v) => v,
            None => {
                return self.make_result(
                    EmaRibbonSignal::Hold,
                    vol_mult,
                    0.0,
                    "Fast EMA not ready".to_string(),
                );
            }
        };
        let mid = match self.last_mid_ema {
            Some(v) => v,
            None => {
                return self.make_result(
                    EmaRibbonSignal::Hold,
                    vol_mult,
                    0.0,
                    "Mid EMA not ready".to_string(),
                );
            }
        };
        let slow = match self.last_slow_ema {
            Some(v) => v,
            None => {
                return self.make_result(
                    EmaRibbonSignal::Hold,
                    vol_mult,
                    0.0,
                    "Slow EMA not ready".to_string(),
                );
            }
        };

        let atr_val = match self.last_atr {
            Some(a) if a > 0.0 => a,
            _ => {
                return self.make_result(
                    EmaRibbonSignal::Hold,
                    vol_mult,
                    0.0,
                    "ATR not ready".to_string(),
                );
            }
        };

        // Ribbon alignment
        let ribbon_bullish = fast > mid && mid > slow;
        let ribbon_bearish = fast < mid && mid < slow;

        // Candle properties
        let body = (close - open).abs();
        let range = high - low;
        let is_bullish = close > open;
        let is_bearish = close < open;
        let body_ratio = if range > 0.0 { body / range } else { 0.0 };
        let upper_wick = high - close.max(open);
        let lower_wick = close.min(open) - low;

        // Check for exit if in position
        if self.in_position
            && let Some(ref side) = self.entry_side
        {
            let exit = self.check_exit(close, fast, slow, atr_val, side);
            if let Some(exit_signal) = exit {
                self.exit_position();
                return self.make_result(
                    exit_signal,
                    vol_mult,
                    0.8,
                    format!(
                        "Ribbon exit: price {:.2} (fast={:.2}, slow={:.2})",
                        close, fast, slow
                    ),
                );
            }
        }

        // Already in position — don't open another
        if self.in_position {
            return self.make_result(
                EmaRibbonSignal::Hold,
                vol_mult,
                0.0,
                "In position".to_string(),
            );
        }

        // HTF trend filtering
        let htf_allows_long = !matches!(self.htf_trend, Some(TrendDirection::Bearish));
        let htf_allows_short = !matches!(self.htf_trend, Some(TrendDirection::Bullish));

        // === LONG SETUP ===
        // Ribbon bullish + price pulled back to mid EMA + bullish candle + volume
        if ribbon_bullish
            && htf_allows_long
            && close > slow
            && close <= mid * (1.0 + self.config.pullback_tolerance)
            && is_bullish
            && vol_mult >= self.config.min_volume_multiplier
        {
            let mut confidence: f64 = 0.40;

            // HTF alignment bonus
            if self.htf_trend == Some(TrendDirection::Bullish) {
                confidence += 0.20;
            }

            // Volume spike bonus
            if vol_mult > 2.0 {
                confidence += 0.15;
            } else if vol_mult >= self.config.min_volume_multiplier {
                confidence += 0.05;
            }

            // Strong candle body bonus
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.10;
            }

            // Body larger than wicks — clean candle
            if body > upper_wick + lower_wick {
                confidence += 0.05;
            }

            // Tight ribbon (EMAs close together = strong trend)
            let ribbon_spread = ((fast - slow) / slow).abs();
            if ribbon_spread < 0.01 {
                confidence += 0.05;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                let stop = close - atr_val * self.config.atr_stop_multiplier;
                let tp = close + atr_val * self.config.atr_tp_multiplier;

                self.enter_position(EmaRibbonSignal::Buy, close, stop, tp);
                self.last_signal = EmaRibbonSignal::Buy;

                return self.make_result(
                    EmaRibbonSignal::Buy,
                    vol_mult,
                    confidence,
                    format!(
                        "Ribbon long: price {:.2} pullback to mid EMA {:.2}, ribbon [{:.2}/{:.2}/{:.2}], vol {:.1}x",
                        close, mid, fast, mid, slow, vol_mult
                    ),
                );
            }
        }

        // === SHORT SETUP ===
        // Ribbon bearish + price pulled back to mid EMA + bearish candle + volume
        if ribbon_bearish
            && htf_allows_short
            && close < slow
            && close >= mid * (1.0 - self.config.pullback_tolerance)
            && is_bearish
            && vol_mult >= self.config.min_volume_multiplier
        {
            let mut confidence: f64 = 0.40;

            // HTF alignment bonus
            if self.htf_trend == Some(TrendDirection::Bearish) {
                confidence += 0.20;
            }

            // Volume spike bonus
            if vol_mult > 2.0 {
                confidence += 0.15;
            } else if vol_mult >= self.config.min_volume_multiplier {
                confidence += 0.05;
            }

            // Strong candle body bonus
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.10;
            }

            // Body larger than wicks
            if body > upper_wick + lower_wick {
                confidence += 0.05;
            }

            // Tight ribbon
            let ribbon_spread = ((fast - slow) / slow).abs();
            if ribbon_spread < 0.01 {
                confidence += 0.05;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                let stop = close + atr_val * self.config.atr_stop_multiplier;
                let tp = close - atr_val * self.config.atr_tp_multiplier;

                self.enter_position(EmaRibbonSignal::Sell, close, stop, tp);
                self.last_signal = EmaRibbonSignal::Sell;

                return self.make_result(
                    EmaRibbonSignal::Sell,
                    vol_mult,
                    confidence,
                    format!(
                        "Ribbon short: price {:.2} pullback to mid EMA {:.2}, ribbon [{:.2}/{:.2}/{:.2}], vol {:.1}x",
                        close, mid, fast, mid, slow, vol_mult
                    ),
                );
            }
        }

        self.last_signal = EmaRibbonSignal::Hold;
        self.make_result(
            EmaRibbonSignal::Hold,
            vol_mult,
            0.0,
            format!(
                "No signal: price {:.2}, ribbon [{:.2}/{:.2}/{:.2}], {}",
                close,
                fast,
                mid,
                slow,
                if ribbon_bullish {
                    "bullish"
                } else if ribbon_bearish {
                    "bearish"
                } else {
                    "mixed"
                }
            ),
        )
    }

    /// Update with HLC values (no volume — uses volume=0 fallback).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> EmaRibbonResult {
        self.update_ohlcv(close, high, low, close, 0.0)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// EMA Ribbon Scalper is a trend-following strategy — it works best when
    /// the market has a clear directional bias.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(regime, MarketRegime::Trending(_) | MarketRegime::Volatile)
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    ///
    /// Returns `Some(factor)` if the regime is suitable, `None` otherwise.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::Trending(_) => {
                // Primary regime — full confidence scaling
                Some(confidence.clamp(0.4, 1.0))
            }
            MarketRegime::Volatile => {
                // Momentum can carry in volatile markets, but reduce size
                Some(if confidence >= 0.6 { 0.40 } else { 0.25 })
            }
            _ => None,
        }
    }

    // ========================================================================
    // Position management (internal)
    // ========================================================================

    fn enter_position(&mut self, side: EmaRibbonSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(
        &self,
        close: f64,
        fast_ema: f64,
        slow_ema: f64,
        _atr: f64,
        side: &EmaRibbonSignal,
    ) -> Option<EmaRibbonSignal> {
        match side {
            EmaRibbonSignal::Buy => {
                // Exit long if price closes below slow EMA (trend break)
                if close < slow_ema {
                    return Some(EmaRibbonSignal::Sell);
                }
                // Exit long if fast EMA crosses below slow EMA
                if fast_ema < slow_ema {
                    return Some(EmaRibbonSignal::Sell);
                }
                // Check stop loss
                if let Some(stop) = self.stop_loss
                    && close <= stop
                {
                    return Some(EmaRibbonSignal::Sell);
                }
                // Check take profit
                if let Some(tp) = self.take_profit
                    && close >= tp
                {
                    return Some(EmaRibbonSignal::Sell);
                }
                None
            }
            EmaRibbonSignal::Sell => {
                // Exit short if price closes above slow EMA
                if close > slow_ema {
                    return Some(EmaRibbonSignal::Buy);
                }
                // Exit short if fast EMA crosses above slow EMA
                if fast_ema > slow_ema {
                    return Some(EmaRibbonSignal::Buy);
                }
                // Check stop loss
                if let Some(stop) = self.stop_loss
                    && close >= stop
                {
                    return Some(EmaRibbonSignal::Buy);
                }
                // Check take profit
                if let Some(tp) = self.take_profit
                    && close <= tp
                {
                    return Some(EmaRibbonSignal::Buy);
                }
                None
            }
            EmaRibbonSignal::Hold => None,
        }
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(
        &self,
        signal: EmaRibbonSignal,
        volume_multiplier: f64,
        confidence: f64,
        reason: String,
    ) -> EmaRibbonResult {
        EmaRibbonResult {
            signal,
            fast_ema: self.last_fast_ema,
            mid_ema: self.last_mid_ema,
            slow_ema: self.last_slow_ema,
            ribbon_bullish: self.is_ribbon_bullish(),
            ribbon_bearish: self.is_ribbon_bearish(),
            atr: self.last_atr,
            volume_multiplier,
            confidence,
            stop_loss: if matches!(signal, EmaRibbonSignal::Buy | EmaRibbonSignal::Sell) {
                self.stop_loss
            } else {
                None
            },
            take_profit: if matches!(signal, EmaRibbonSignal::Buy | EmaRibbonSignal::Sell) {
                self.take_profit
            } else {
                None
            },
            reason,
        }
    }

    // ========================================================================
    // Reset
    // ========================================================================

    /// Full reset — clears all indicator and position state.
    pub fn reset(&mut self) {
        self.fast_ema = EMA::new(self.config.fast_ema_period);
        self.mid_ema = EMA::new(self.config.mid_ema_period);
        self.slow_ema = EMA::new(self.config.slow_ema_period);
        self.atr = ATR::new(self.config.atr_period);
        self.volume_analyzer = VolumeAnalyzer::new(self.config.volume_period);
        self.exit_position();
        self.last_fast_ema = None;
        self.last_mid_ema = None;
        self.last_slow_ema = None;
        self.last_atr = None;
        self.last_signal = EmaRibbonSignal::Hold;
        self.candle_count = 0;
        self.htf_trend = None;
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Whether the strategy has enough data to produce signals.
    pub fn is_ready(&self) -> bool {
        self.candle_count >= self.config.warmup_candles
            && self.last_fast_ema.is_some()
            && self.last_mid_ema.is_some()
            && self.last_slow_ema.is_some()
            && self.last_atr.is_some()
    }

    /// Whether the ribbon is aligned bullish (fast > mid > slow).
    pub fn is_ribbon_bullish(&self) -> bool {
        match (self.last_fast_ema, self.last_mid_ema, self.last_slow_ema) {
            (Some(f), Some(m), Some(s)) => f > m && m > s,
            _ => false,
        }
    }

    /// Whether the ribbon is aligned bearish (fast < mid < slow).
    pub fn is_ribbon_bearish(&self) -> bool {
        match (self.last_fast_ema, self.last_mid_ema, self.last_slow_ema) {
            (Some(f), Some(m), Some(s)) => f < m && m < s,
            _ => false,
        }
    }

    /// Whether the strategy currently has an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// The last fast EMA value.
    pub fn last_fast_ema(&self) -> Option<f64> {
        self.last_fast_ema
    }

    /// The last mid EMA value.
    pub fn last_mid_ema(&self) -> Option<f64> {
        self.last_mid_ema
    }

    /// The last slow EMA value.
    pub fn last_slow_ema(&self) -> Option<f64> {
        self.last_slow_ema
    }

    /// The last ATR value.
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// The last signal produced.
    pub fn last_signal(&self) -> EmaRibbonSignal {
        self.last_signal
    }

    /// Total candles processed.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Current entry price (if in position).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Current stop loss (if in position).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Current take profit (if in position).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// Strategy configuration.
    pub fn config(&self) -> &EmaRibbonConfig {
        &self.config
    }

    /// Current HTF trend bias (if set).
    pub fn htf_trend(&self) -> Option<TrendDirection> {
        self.htf_trend
    }

    /// Return current EMA ribbon values as (fast, mid, slow).
    pub fn ribbon_values(&self) -> (Option<f64>, Option<f64>, Option<f64>) {
        (self.last_fast_ema, self.last_mid_ema, self.last_slow_ema)
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Feed enough candles to warm up the strategy.
    fn warm_up(strategy: &mut EmaRibbonScalperStrategy, base_price: f64, count: usize) {
        for i in 0..count {
            let price = base_price + (i as f64) * 0.01; // slight uptrend
            strategy.update_ohlcv(price, price + 10.0, price - 10.0, price, 1000.0);
        }
    }

    // ── Config tests ─────────────────────────────────────────────────────

    #[test]
    fn test_default_config() {
        let config = EmaRibbonConfig::default();
        assert_eq!(config.fast_ema_period, 8);
        assert_eq!(config.mid_ema_period, 13);
        assert_eq!(config.slow_ema_period, 21);
        assert_eq!(config.atr_period, 14);
        assert!((config.atr_stop_multiplier - 1.5).abs() < 1e-10);
        assert!((config.atr_tp_multiplier - 3.0).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 25);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = EmaRibbonConfig::crypto_aggressive();
        assert!((config.atr_stop_multiplier - 1.2).abs() < 1e-10);
        assert!((config.min_confidence - 0.50).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 20);
    }

    #[test]
    fn test_conservative_config() {
        let config = EmaRibbonConfig::conservative();
        assert!((config.atr_stop_multiplier - 2.0).abs() < 1e-10);
        assert!((config.min_confidence - 0.65).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 30);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = EmaRibbonConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: EmaRibbonConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.fast_ema_period, config.fast_ema_period);
        assert_eq!(deserialized.mid_ema_period, config.mid_ema_period);
        assert_eq!(deserialized.slow_ema_period, config.slow_ema_period);
    }

    // ── Strategy creation tests ──────────────────────────────────────────

    #[test]
    fn test_strategy_creation() {
        let strategy = EmaRibbonScalperStrategy::with_defaults();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert!(!strategy.is_ribbon_bullish());
        assert!(!strategy.is_ribbon_bearish());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.last_signal(), EmaRibbonSignal::Hold);
    }

    #[test]
    fn test_warmup_hold() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        for i in 0..10 {
            let result = strategy.update_ohlcv(
                100.0 + i as f64,
                105.0 + i as f64,
                95.0 + i as f64,
                100.0 + i as f64,
                1000.0,
            );
            assert_eq!(result.signal, EmaRibbonSignal::Hold);
        }
        assert!(!strategy.is_ready());
    }

    #[test]
    fn test_becomes_ready_after_warmup() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 30);
        assert!(strategy.is_ready());
    }

    // ── Volume analyzer tests ────────────────────────────────────────────

    #[test]
    fn test_volume_analyzer_basic() {
        let mut va = VolumeAnalyzer::new(5);
        // First update has no history
        let mult = va.update(100.0);
        assert!((mult - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_volume_analyzer_spike_detection() {
        let mut va = VolumeAnalyzer::new(5);
        for _ in 0..5 {
            va.update(100.0);
        }
        // Spike at 3x
        let mult = va.update(300.0);
        assert!(mult > 2.5);
    }

    // ── Ribbon alignment tests ───────────────────────────────────────────

    #[test]
    fn test_ribbon_bullish_alignment() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        // Feed strong uptrend data
        for i in 0..50 {
            let price = 50000.0 + (i as f64) * 50.0;
            strategy.update_ohlcv(price - 10.0, price + 20.0, price - 20.0, price, 1000.0);
        }
        assert!(strategy.is_ribbon_bullish());
        assert!(!strategy.is_ribbon_bearish());
    }

    #[test]
    fn test_ribbon_bearish_alignment() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        // Feed strong downtrend data
        for i in 0..50 {
            let price = 55000.0 - (i as f64) * 50.0;
            strategy.update_ohlcv(price + 10.0, price + 20.0, price - 20.0, price, 1000.0);
        }
        assert!(strategy.is_ribbon_bearish());
        assert!(!strategy.is_ribbon_bullish());
    }

    // ── Signal generation tests ──────────────────────────────────────────

    #[test]
    fn test_buy_signal_on_pullback() {
        let mut strategy = EmaRibbonScalperStrategy::new(EmaRibbonConfig {
            min_confidence: 0.40,
            min_volume_multiplier: 1.0,
            warmup_candles: 25,
            ..EmaRibbonConfig::default()
        });

        // Build strong uptrend to align ribbon
        for i in 0..40 {
            let price = 50000.0 + (i as f64) * 30.0;
            strategy.update_ohlcv(price - 5.0, price + 15.0, price - 15.0, price, 1000.0);
        }

        assert!(strategy.is_ribbon_bullish());

        // Now simulate a pullback to mid EMA area
        if let Some(mid) = strategy.last_mid_ema() {
            // Drop price to just at the mid EMA but above slow EMA
            let slow = strategy.last_slow_ema().unwrap();
            let pullback_price = mid; // right at mid EMA
            // Ensure close > slow
            if pullback_price > slow {
                let result = strategy.update_ohlcv(
                    pullback_price - 10.0, // open lower
                    pullback_price + 20.0, // high above
                    pullback_price - 20.0, // low below
                    pullback_price + 5.0,  // close bullish above open
                    3000.0,                // 3x normal volume
                );
                // May or may not fire depending on exact EMA alignment after the dip
                // but should not panic
                assert!(result.fast_ema.is_some());
                assert!(result.mid_ema.is_some());
                assert!(result.slow_ema.is_some());
            }
        }
    }

    #[test]
    fn test_no_signal_in_mixed_ribbon() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        // Feed choppy sideways data — ribbon should not align
        for i in 0..50 {
            let base = 50000.0;
            let price = base + (i as f64 * 0.5).sin() * 100.0;
            strategy.update_ohlcv(price - 5.0, price + 30.0, price - 30.0, price, 1000.0);
        }
        // Should produce Hold
        let result = strategy.update_ohlcv(50000.0, 50030.0, 49970.0, 50000.0, 1000.0);
        assert_eq!(result.signal, EmaRibbonSignal::Hold);
    }

    // ── HTF trend tests ──────────────────────────────────────────────────

    #[test]
    fn test_htf_trend_filtering() {
        let strategy = EmaRibbonScalperStrategy::with_defaults();
        assert!(strategy.htf_trend().is_none());
    }

    #[test]
    fn test_set_htf_trend() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        strategy.set_htf_trend(TrendDirection::Bullish);
        assert_eq!(strategy.htf_trend(), Some(TrendDirection::Bullish));
        strategy.clear_htf_trend();
        assert!(strategy.htf_trend().is_none());
    }

    // ── Regime gating tests ──────────────────────────────────────────────

    #[test]
    fn test_should_trade_in_trending_bullish() {
        assert!(EmaRibbonScalperStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
    }

    #[test]
    fn test_should_trade_in_trending_bearish() {
        assert!(EmaRibbonScalperStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_trade_in_volatile() {
        assert!(EmaRibbonScalperStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_should_not_trade_in_mean_reverting() {
        assert!(!EmaRibbonScalperStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_not_trade_in_uncertain() {
        assert!(!EmaRibbonScalperStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_regime_size_factor_trending() {
        let factor = EmaRibbonScalperStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.8,
        );
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.8).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_volatile() {
        let factor = EmaRibbonScalperStrategy::regime_size_factor(&MarketRegime::Volatile, 0.7);
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.40).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_mean_reverting_is_none() {
        let factor =
            EmaRibbonScalperStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.8);
        assert!(factor.is_none());
    }

    // ── Reset tests ──────────────────────────────────────────────────────

    #[test]
    fn test_full_reset() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 30);
        assert!(strategy.is_ready());

        strategy.reset();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert!(strategy.last_fast_ema().is_none());
        assert!(strategy.last_mid_ema().is_none());
        assert!(strategy.last_slow_ema().is_none());
    }

    // ── Position tracking tests ──────────────────────────────────────────

    #[test]
    fn test_not_in_position_initially() {
        let strategy = EmaRibbonScalperStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    #[test]
    fn test_internal_position_tracking() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        strategy.enter_position(EmaRibbonSignal::Buy, 50000.0, 49500.0, 51500.0);
        assert!(strategy.is_in_position());
        assert_eq!(strategy.entry_price(), Some(50000.0));
        assert_eq!(strategy.stop_loss(), Some(49500.0));
        assert_eq!(strategy.take_profit(), Some(51500.0));

        strategy.exit_position();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
    }

    // ── Signal display tests ─────────────────────────────────────────────

    #[test]
    fn test_signal_display() {
        assert_eq!(format!("{}", EmaRibbonSignal::Buy), "BUY");
        assert_eq!(format!("{}", EmaRibbonSignal::Sell), "SELL");
        assert_eq!(format!("{}", EmaRibbonSignal::Hold), "HOLD");
    }

    #[test]
    fn test_signal_serialization() {
        let signal = EmaRibbonSignal::Buy;
        let json = serde_json::to_string(&signal).unwrap();
        let deserialized: EmaRibbonSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, signal);
    }

    // ── Ribbon values accessor ───────────────────────────────────────────

    #[test]
    fn test_ribbon_values() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        let (f, m, s) = strategy.ribbon_values();
        assert!(f.is_none());
        assert!(m.is_none());
        assert!(s.is_none());

        warm_up(&mut strategy, 50000.0, 30);
        let (f, m, s) = strategy.ribbon_values();
        assert!(f.is_some());
        assert!(m.is_some());
        assert!(s.is_some());
    }

    // ── Stress test ──────────────────────────────────────────────────────

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = EmaRibbonScalperStrategy::new(EmaRibbonConfig::crypto_aggressive());
        let mut price = 50000.0;
        for i in 0..2000 {
            let direction = if (i / 50) % 2 == 0 { 1.0 } else { -1.0 };
            price += direction * 20.0 + (i as f64 * 0.1).sin() * 50.0;
            let high = price + 30.0;
            let low = price - 30.0;
            let open = price - direction * 5.0;
            let volume = 1000.0 + (i as f64 * 0.3).cos().abs() * 2000.0;
            let _ = strategy.update_ohlcv(open, high, low, price, volume);
        }
        // Should not panic; should have processed all candles
        assert_eq!(strategy.candle_count(), 2000);
    }

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        let result = strategy.update_ohlcv(50000.0, 50010.0, 49990.0, 50000.0, 1000.0);
        assert!(!result.reason.is_empty());
    }

    #[test]
    fn test_config_accessor() {
        let strategy = EmaRibbonScalperStrategy::with_defaults();
        assert_eq!(strategy.config().fast_ema_period, 8);
        assert_eq!(strategy.config().mid_ema_period, 13);
        assert_eq!(strategy.config().slow_ema_period, 21);
    }

    // ── HLC interface test ───────────────────────────────────────────────

    #[test]
    fn test_hlc_interface() {
        let mut strategy = EmaRibbonScalperStrategy::with_defaults();
        for i in 0..30 {
            let price = 50000.0 + i as f64;
            strategy.update_hlc(price + 10.0, price - 10.0, price);
        }
        assert!(strategy.is_ready());
        assert!(strategy.last_atr().is_some());
    }
}
