//! # Momentum Surge Strategy
//!
//! Detects sudden momentum surges — large price moves accompanied by volume
//! spikes — and enters on the first pullback within the surge. Uses
//! candle-count based lookback instead of `chrono::DateTime` timestamps,
//! making it compatible with JANUS's tick-aggregated candle pipeline.
//!
//! ## How It Works
//!
//! 1. **Price Change Detection**: Tracks the percentage price change over a
//!    configurable lookback window (in candles, not minutes). A surge is
//!    detected when the change exceeds `momentum_threshold_pct`.
//!
//! 2. **Volume Spike Confirmation**: The current candle's volume must exceed
//!    the rolling average by `volume_spike_multiplier` to confirm real
//!    institutional participation (not just a thin-book wick).
//!
//! 3. **Pullback Entry**: Rather than chasing the top/bottom of the surge,
//!    the strategy waits for a slight pullback from the recent extreme before
//!    entering. This gives a better risk/reward entry point.
//!
//! 4. **ATR-Based Stops**: Stop loss and take profit are placed at ATR
//!    multiples from entry, with tighter stops for the inherently riskier
//!    momentum plays.
//!
//! ## Regime Integration
//!
//! Momentum surges happen in trending and volatile markets:
//!
//! - **Trending(Bullish/Bearish)** → Yes (momentum aligned with trend)
//! - **Volatile** → Yes (surges are common in volatile regimes)
//! - **MeanReverting** → No (surges are likely to revert)
//! - **Uncertain** → No (spurious signals)
//!
//! ## Differences from Kraken Version
//!
//! The Kraken `MomentumSurge` used `chrono::DateTime<Utc>` price history with
//! minute-based lookback (`Duration::minutes(15)`). This JANUS version uses a
//! rolling window of candle close prices, where the lookback is specified in
//! number of candles. This is more natural for the tick-aggregated candle
//! pipeline where candle duration depends on tick rate, not wall-clock time.
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/intraday.rs::MomentumSurge`, adapted for
//! the JANUS single-asset design, candle-count based lookback, `janus-regime`
//! indicator types, and regime-aware position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::ATR;
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal Types
// ============================================================================

/// Signal generated by the Momentum Surge strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MomentumSurgeSignal {
    /// Enter long — bullish momentum surge with pullback entry.
    Buy,
    /// Enter short / exit long — bearish momentum surge with pullback entry.
    Sell,
    /// No action.
    Hold,
}

impl std::fmt::Display for MomentumSurgeSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MomentumSurgeSignal::Buy => write!(f, "BUY"),
            MomentumSurgeSignal::Sell => write!(f, "SELL"),
            MomentumSurgeSignal::Hold => write!(f, "HOLD"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the Momentum Surge strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MomentumSurgeConfig {
    /// Number of candles to look back for price change calculation (default: 15).
    /// In the Kraken version this was 15 minutes; here it is 15 candles.
    pub lookback_candles: usize,

    /// Minimum absolute price change (%) over the lookback window to qualify
    /// as a "surge" (default: 5.0 = 5%).
    pub momentum_threshold_pct: f64,

    /// Minimum volume multiplier (vs rolling average) to confirm the surge
    /// (default: 3.0 = 3× average volume).
    pub volume_spike_multiplier: f64,

    /// Rolling volume lookback period for average calculation (default: 20).
    pub volume_period: usize,

    /// ATR period for volatility measurement (default: 14).
    pub atr_period: usize,

    /// ATR multiplier for stop-loss distance (default: 1.5).
    pub atr_stop_multiplier: f64,

    /// ATR multiplier for take-profit distance (default: 3.0).
    pub atr_tp_multiplier: f64,

    /// Pullback threshold — fraction below recent high (for longs) or above
    /// recent low (for shorts) required before entering (default: 0.005 = 0.5%).
    /// Prevents chasing the absolute peak/trough.
    pub pullback_threshold: f64,

    /// Number of recent candles to scan for the pullback extreme (default: 5).
    pub pullback_lookback: usize,

    /// Minimum confidence score to emit a signal (default: 0.50).
    pub min_confidence: f64,

    /// Maximum price history to keep in the rolling window (default: 60).
    pub max_history: usize,

    /// Minimum number of candles before the strategy is ready (default: 20).
    pub warmup_candles: usize,
}

impl Default for MomentumSurgeConfig {
    fn default() -> Self {
        Self {
            lookback_candles: 15,
            momentum_threshold_pct: 5.0,
            volume_spike_multiplier: 3.0,
            volume_period: 20,
            atr_period: 14,
            atr_stop_multiplier: 1.5,
            atr_tp_multiplier: 3.0,
            pullback_threshold: 0.005,
            pullback_lookback: 5,
            min_confidence: 0.50,
            max_history: 60,
            warmup_candles: 20,
        }
    }
}

impl MomentumSurgeConfig {
    /// Aggressive config for meme coins — lower thresholds, tighter stops.
    pub fn meme_coin() -> Self {
        Self {
            lookback_candles: 10,
            momentum_threshold_pct: 3.0,
            volume_spike_multiplier: 2.0,
            atr_stop_multiplier: 1.2,
            atr_tp_multiplier: 2.5,
            pullback_threshold: 0.003,
            min_confidence: 0.45,
            warmup_candles: 15,
            ..Default::default()
        }
    }

    /// Aggressive config for crypto majors (BTC, ETH, SOL).
    pub fn crypto_aggressive() -> Self {
        Self {
            lookback_candles: 15,
            momentum_threshold_pct: 4.0,
            volume_spike_multiplier: 2.5,
            atr_stop_multiplier: 1.3,
            atr_tp_multiplier: 2.8,
            pullback_threshold: 0.004,
            min_confidence: 0.48,
            warmup_candles: 18,
            ..Default::default()
        }
    }

    /// Conservative config — higher thresholds, wider stops.
    pub fn conservative() -> Self {
        Self {
            lookback_candles: 20,
            momentum_threshold_pct: 8.0,
            volume_spike_multiplier: 4.0,
            atr_stop_multiplier: 2.0,
            atr_tp_multiplier: 4.0,
            pullback_threshold: 0.008,
            min_confidence: 0.60,
            warmup_candles: 25,
            ..Default::default()
        }
    }
}

// ============================================================================
// Detailed Result
// ============================================================================

/// Detailed result from a Momentum Surge strategy update.
#[derive(Debug, Clone)]
pub struct MomentumSurgeResult {
    /// The signal produced.
    pub signal: MomentumSurgeSignal,
    /// Price change (%) over the lookback window.
    pub price_change_pct: Option<f64>,
    /// Volume multiplier relative to rolling average.
    pub volume_multiplier: f64,
    /// Current ATR value.
    pub atr: Option<f64>,
    /// Recent high over the pullback lookback window.
    pub recent_high: Option<f64>,
    /// Recent low over the pullback lookback window.
    pub recent_low: Option<f64>,
    /// Confidence score (0.0–1.0).
    pub confidence: f64,
    /// Computed stop-loss price.
    pub stop_loss: Option<f64>,
    /// Computed take-profit price.
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// Internal: Volume Analyzer
// ============================================================================

/// Rolling volume analyzer for spike detection.
#[derive(Debug)]
struct VolumeAnalyzer {
    period: usize,
    volumes: Vec<f64>,
}

impl VolumeAnalyzer {
    fn new(period: usize) -> Self {
        Self {
            period: period.max(1),
            volumes: Vec::with_capacity(period),
        }
    }

    /// Push a new volume value. Returns the multiplier (volume / rolling avg).
    fn update(&mut self, volume: f64) -> f64 {
        let avg = self.average();

        self.volumes.push(volume);
        if self.volumes.len() > self.period {
            self.volumes.remove(0);
        }

        if avg > 0.0 { volume / avg } else { 1.0 }
    }

    /// Rolling average volume.
    fn average(&self) -> f64 {
        if self.volumes.is_empty() {
            0.0
        } else {
            self.volumes.iter().sum::<f64>() / self.volumes.len() as f64
        }
    }
}

// ============================================================================
// Internal: Price History (candle-count based)
// ============================================================================

/// Minimal candle data stored in the rolling history window.
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct PricePoint {
    high: f64,
    low: f64,
    close: f64,
    is_bullish: bool,
}

/// Rolling price history for lookback calculations.
#[derive(Debug)]
struct PriceHistory {
    points: Vec<PricePoint>,
    max_size: usize,
}

impl PriceHistory {
    fn new(max_size: usize) -> Self {
        Self {
            points: Vec::with_capacity(max_size),
            max_size: max_size.max(1),
        }
    }

    fn push(&mut self, point: PricePoint) {
        self.points.push(point);
        if self.points.len() > self.max_size {
            self.points.remove(0);
        }
    }

    fn len(&self) -> usize {
        self.points.len()
    }

    /// Calculate price change (%) over the last `lookback` candles.
    /// Returns None if not enough history.
    fn price_change_pct(&self, lookback: usize) -> Option<f64> {
        if self.points.len() < lookback + 1 {
            return None;
        }

        let current_idx = self.points.len() - 1;
        let old_idx = current_idx.saturating_sub(lookback);

        let old_price = self.points[old_idx].close;
        let current_price = self.points[current_idx].close;

        if old_price == 0.0 {
            return None;
        }

        Some((current_price - old_price) / old_price * 100.0)
    }

    /// Get the highest high over the last `n` candles.
    fn recent_high(&self, n: usize) -> Option<f64> {
        if self.points.is_empty() {
            return None;
        }
        let start = self.points.len().saturating_sub(n);
        self.points[start..]
            .iter()
            .map(|p| p.high)
            .fold(None, |acc: Option<f64>, h| {
                Some(acc.map_or(h, |a: f64| a.max(h)))
            })
    }

    /// Get the lowest low over the last `n` candles.
    fn recent_low(&self, n: usize) -> Option<f64> {
        if self.points.is_empty() {
            return None;
        }
        let start = self.points.len().saturating_sub(n);
        self.points[start..]
            .iter()
            .map(|p| p.low)
            .fold(None, |acc: Option<f64>, l| {
                Some(acc.map_or(l, |a: f64| a.min(l)))
            })
    }

    /// Get the last price point.
    fn last(&self) -> Option<&PricePoint> {
        self.points.last()
    }

    fn clear(&mut self) {
        self.points.clear();
    }
}

// ============================================================================
// Strategy
// ============================================================================

/// Momentum Surge Strategy
///
/// Detects sudden momentum surges (large price moves + volume spikes) and
/// enters on pullback within the surge. Single-asset — instantiate one per
/// symbol.
#[derive(Debug)]
pub struct MomentumSurgeStrategy {
    config: MomentumSurgeConfig,

    // Indicators
    atr: ATR,
    volume_analyzer: VolumeAnalyzer,

    // Price history (candle-count based lookback)
    history: PriceHistory,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<MomentumSurgeSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Last computed values
    last_atr: Option<f64>,
    last_signal: MomentumSurgeSignal,
    candle_count: usize,
}

impl MomentumSurgeStrategy {
    /// Create a new Momentum Surge strategy with the given config.
    pub fn new(config: MomentumSurgeConfig) -> Self {
        let atr = ATR::new(config.atr_period);
        let volume_analyzer = VolumeAnalyzer::new(config.volume_period);
        let history = PriceHistory::new(config.max_history);

        Self {
            atr,
            volume_analyzer,
            history,
            config,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            last_atr: None,
            last_signal: MomentumSurgeSignal::Hold,
            candle_count: 0,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(MomentumSurgeConfig::default())
    }

    /// Update with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> MomentumSurgeSignal {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
        .signal
    }

    /// Update with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(
        &mut self,
        candle: &janus_models::Candle,
    ) -> MomentumSurgeResult {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
    }

    /// Main update with OHLCV values — returns a detailed result.
    pub fn update_ohlcv(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
    ) -> MomentumSurgeResult {
        self.candle_count += 1;

        // Update indicators
        self.atr.update(high, low, close);
        let vol_mult = self.volume_analyzer.update(volume);
        self.last_atr = self.atr.value();

        // Store in price history
        let is_bullish = close > open;
        self.history.push(PricePoint {
            high,
            low,
            close,
            is_bullish,
        });

        // Not ready yet?
        if self.candle_count < self.config.warmup_candles
            || self.history.len() < self.config.lookback_candles + 1
        {
            return self.make_result(
                MomentumSurgeSignal::Hold,
                None,
                vol_mult,
                0.0,
                "Warming up".to_string(),
            );
        }

        let atr_val = match self.last_atr {
            Some(a) if a > 0.0 => a,
            _ => {
                return self.make_result(
                    MomentumSurgeSignal::Hold,
                    None,
                    vol_mult,
                    0.0,
                    "ATR not ready".to_string(),
                );
            }
        };

        // Calculate price change over lookback window
        let price_change = self.history.price_change_pct(self.config.lookback_candles);

        // Check for exit if in position
        if self.in_position
            && let Some(ref side) = self.entry_side
        {
            let exit = self.check_exit(close, atr_val, side);
            if let Some(exit_signal) = exit {
                self.exit_position();
                return self.make_result(
                    exit_signal,
                    price_change,
                    vol_mult,
                    0.8,
                    format!("Momentum exit: price {:.2}", close),
                );
            }
        }

        // Already in position — don't open another
        if self.in_position {
            return self.make_result(
                MomentumSurgeSignal::Hold,
                price_change,
                vol_mult,
                0.0,
                "In position".to_string(),
            );
        }

        // Need price change data
        let pct_change = match price_change {
            Some(c) => c,
            None => {
                return self.make_result(
                    MomentumSurgeSignal::Hold,
                    None,
                    vol_mult,
                    0.0,
                    "Price history not long enough".to_string(),
                );
            }
        };

        let price = close;

        // Compute recent extreme for pullback check
        let recent_high = self.history.recent_high(self.config.pullback_lookback);
        let recent_low = self.history.recent_low(self.config.pullback_lookback);

        // === BULLISH MOMENTUM SURGE ===
        if pct_change >= self.config.momentum_threshold_pct
            && vol_mult >= self.config.volume_spike_multiplier
        {
            // Check for pullback from recent high
            if let Some(rh) = recent_high {
                let pullback = rh > 0.0 && price < rh * (1.0 - self.config.pullback_threshold);
                let candle_bullish = is_bullish;

                if pullback && candle_bullish {
                    let stop = price - atr_val * self.config.atr_stop_multiplier;
                    let tp = price + atr_val * self.config.atr_tp_multiplier;

                    let mut confidence = 0.40;

                    // More surge = more confidence (capped)
                    confidence += (pct_change / 20.0).min(0.25);

                    // Bigger volume spike = more confidence
                    confidence += (vol_mult / 10.0).min(0.20);

                    // Strong bullish candle body
                    let body = (close - open).abs();
                    let range = high - low;
                    if range > 0.0 && body / range > 0.6 {
                        confidence += 0.05;
                    }

                    confidence = confidence.min(1.0);

                    if confidence >= self.config.min_confidence {
                        self.enter_position(MomentumSurgeSignal::Buy, price, stop, tp);
                        self.last_signal = MomentumSurgeSignal::Buy;

                        return self.make_result(
                            MomentumSurgeSignal::Buy,
                            Some(pct_change),
                            vol_mult,
                            confidence,
                            format!(
                                "Bullish momentum surge: +{:.1}% in {} candles, vol {:.1}x, pullback entry from {:.2}",
                                pct_change, self.config.lookback_candles, vol_mult, rh
                            ),
                        );
                    }
                }
            }
        }

        // === BEARISH MOMENTUM SURGE ===
        if pct_change <= -self.config.momentum_threshold_pct
            && vol_mult >= self.config.volume_spike_multiplier
            && let Some(rl) = recent_low
        {
            let pullback = rl > 0.0 && price > rl * (1.0 + self.config.pullback_threshold);
            let candle_bearish = !is_bullish && close != open; // bearish, not doji

            if pullback && candle_bearish {
                let stop = price + atr_val * self.config.atr_stop_multiplier;
                let tp = price - atr_val * self.config.atr_tp_multiplier;

                let mut confidence = 0.40;

                confidence += (pct_change.abs() / 20.0).min(0.25);
                confidence += (vol_mult / 10.0).min(0.20);

                let body = (close - open).abs();
                let range = high - low;
                if range > 0.0 && body / range > 0.6 {
                    confidence += 0.05;
                }

                confidence = confidence.min(1.0);

                if confidence >= self.config.min_confidence {
                    self.enter_position(MomentumSurgeSignal::Sell, price, stop, tp);
                    self.last_signal = MomentumSurgeSignal::Sell;

                    return self.make_result(
                            MomentumSurgeSignal::Sell,
                            Some(pct_change),
                            vol_mult,
                            confidence,
                            format!(
                                "Bearish momentum surge: {:.1}% in {} candles, vol {:.1}x, pullback entry from {:.2}",
                                pct_change, self.config.lookback_candles, vol_mult, rl
                            ),
                        );
                }
            }
        }

        self.last_signal = MomentumSurgeSignal::Hold;
        self.make_result(
            MomentumSurgeSignal::Hold,
            Some(pct_change),
            vol_mult,
            0.0,
            format!(
                "No signal: price {:.2}, change {:.1}%, vol {:.1}x",
                price, pct_change, vol_mult
            ),
        )
    }

    /// Update with HLC values (no volume — uses volume=0 fallback).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> MomentumSurgeResult {
        self.update_ohlcv(close, high, low, close, 0.0)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// Momentum surges are most meaningful in trending or volatile markets.
    /// In mean-reverting markets the surge is likely to reverse before
    /// reaching the take-profit.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(regime, MarketRegime::Trending(_) | MarketRegime::Volatile)
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    ///
    /// Returns `Some(factor)` if the regime is suitable, `None` otherwise.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::Trending(_) => {
                // Primary regime — momentum aligned with trend
                Some(confidence.clamp(0.3, 0.8))
            }
            MarketRegime::Volatile => {
                // Surges are common but riskier — cap size
                Some(if confidence >= 0.6 { 0.35 } else { 0.20 })
            }
            _ => None,
        }
    }

    // ========================================================================
    // Momentum accessors
    // ========================================================================

    /// Get the current momentum reading: (price_change_pct, volume_multiplier).
    /// Returns None if not enough data.
    pub fn get_momentum(&self) -> Option<(f64, f64)> {
        let pct = self
            .history
            .price_change_pct(self.config.lookback_candles)?;
        let vol_avg = self.volume_analyzer.average();
        if vol_avg <= 0.0 {
            return None;
        }
        // Use the last volume relative to the average
        let last_vol = self.history.last().map(|_| vol_avg).unwrap_or(0.0);
        if last_vol > 0.0 {
            Some((pct, 1.0)) // current multiplier already consumed; return baseline
        } else {
            Some((pct, 0.0))
        }
    }

    // ========================================================================
    // Position management (internal)
    // ========================================================================

    fn enter_position(&mut self, side: MomentumSurgeSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(
        &self,
        close: f64,
        _atr: f64,
        side: &MomentumSurgeSignal,
    ) -> Option<MomentumSurgeSignal> {
        match side {
            MomentumSurgeSignal::Buy => {
                // Stop loss
                if let Some(stop) = self.stop_loss
                    && close <= stop
                {
                    return Some(MomentumSurgeSignal::Sell);
                }
                // Take profit
                if let Some(tp) = self.take_profit
                    && close >= tp
                {
                    return Some(MomentumSurgeSignal::Sell);
                }
                None
            }
            MomentumSurgeSignal::Sell => {
                if let Some(stop) = self.stop_loss
                    && close >= stop
                {
                    return Some(MomentumSurgeSignal::Buy);
                }
                if let Some(tp) = self.take_profit
                    && close <= tp
                {
                    return Some(MomentumSurgeSignal::Buy);
                }
                None
            }
            MomentumSurgeSignal::Hold => None,
        }
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(
        &self,
        signal: MomentumSurgeSignal,
        price_change_pct: Option<f64>,
        volume_multiplier: f64,
        confidence: f64,
        reason: String,
    ) -> MomentumSurgeResult {
        MomentumSurgeResult {
            signal,
            price_change_pct,
            volume_multiplier,
            atr: self.last_atr,
            recent_high: self.history.recent_high(self.config.pullback_lookback),
            recent_low: self.history.recent_low(self.config.pullback_lookback),
            confidence,
            stop_loss: if matches!(signal, MomentumSurgeSignal::Buy | MomentumSurgeSignal::Sell) {
                self.stop_loss
            } else {
                None
            },
            take_profit: if matches!(signal, MomentumSurgeSignal::Buy | MomentumSurgeSignal::Sell) {
                self.take_profit
            } else {
                None
            },
            reason,
        }
    }

    // ========================================================================
    // Reset
    // ========================================================================

    /// Full reset — clears all indicator and position state.
    pub fn reset(&mut self) {
        self.atr = ATR::new(self.config.atr_period);
        self.volume_analyzer = VolumeAnalyzer::new(self.config.volume_period);
        self.history.clear();
        self.exit_position();
        self.last_atr = None;
        self.last_signal = MomentumSurgeSignal::Hold;
        self.candle_count = 0;
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Whether the strategy has enough data to produce signals.
    pub fn is_ready(&self) -> bool {
        self.candle_count >= self.config.warmup_candles
            && self.history.len() > self.config.lookback_candles
            && self.last_atr.is_some()
    }

    /// Whether the strategy currently has an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// The last ATR value.
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// The last signal produced.
    pub fn last_signal(&self) -> MomentumSurgeSignal {
        self.last_signal
    }

    /// Total candles processed.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Current entry price (if in position).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Current stop loss (if in position).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Current take profit (if in position).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// Strategy configuration.
    pub fn config(&self) -> &MomentumSurgeConfig {
        &self.config
    }

    /// Number of price points in the rolling history.
    pub fn history_len(&self) -> usize {
        self.history.len()
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use janus_regime::types::TrendDirection;

    /// Feed candles to warm up the strategy.
    fn warm_up(strategy: &mut MomentumSurgeStrategy, base_price: f64, count: usize) {
        for i in 0..count {
            let price = base_price + (i as f64) * 0.5;
            strategy.update_ohlcv(price - 2.0, price + 10.0, price - 10.0, price, 1000.0);
        }
    }

    // ── Config tests ─────────────────────────────────────────────────────

    #[test]
    fn test_default_config() {
        let config = MomentumSurgeConfig::default();
        assert_eq!(config.lookback_candles, 15);
        assert!((config.momentum_threshold_pct - 5.0).abs() < 1e-10);
        assert!((config.volume_spike_multiplier - 3.0).abs() < 1e-10);
        assert_eq!(config.volume_period, 20);
        assert_eq!(config.atr_period, 14);
        assert!((config.atr_stop_multiplier - 1.5).abs() < 1e-10);
        assert!((config.atr_tp_multiplier - 3.0).abs() < 1e-10);
        assert!((config.pullback_threshold - 0.005).abs() < 1e-10);
        assert_eq!(config.pullback_lookback, 5);
        assert!((config.min_confidence - 0.50).abs() < 1e-10);
        assert_eq!(config.max_history, 60);
        assert_eq!(config.warmup_candles, 20);
    }

    #[test]
    fn test_meme_coin_config() {
        let config = MomentumSurgeConfig::meme_coin();
        assert_eq!(config.lookback_candles, 10);
        assert!((config.momentum_threshold_pct - 3.0).abs() < 1e-10);
        assert!((config.volume_spike_multiplier - 2.0).abs() < 1e-10);
        assert!((config.min_confidence - 0.45).abs() < 1e-10);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = MomentumSurgeConfig::crypto_aggressive();
        assert!((config.momentum_threshold_pct - 4.0).abs() < 1e-10);
        assert!((config.volume_spike_multiplier - 2.5).abs() < 1e-10);
    }

    #[test]
    fn test_conservative_config() {
        let config = MomentumSurgeConfig::conservative();
        assert!((config.momentum_threshold_pct - 8.0).abs() < 1e-10);
        assert!((config.volume_spike_multiplier - 4.0).abs() < 1e-10);
        assert!((config.min_confidence - 0.60).abs() < 1e-10);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = MomentumSurgeConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: MomentumSurgeConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.lookback_candles, config.lookback_candles);
        assert!(
            (deserialized.momentum_threshold_pct - config.momentum_threshold_pct).abs() < 1e-10
        );
    }

    // ── Strategy creation tests ──────────────────────────────────────────

    #[test]
    fn test_strategy_creation() {
        let strategy = MomentumSurgeStrategy::with_defaults();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.last_signal(), MomentumSurgeSignal::Hold);
        assert_eq!(strategy.history_len(), 0);
    }

    #[test]
    fn test_warmup_hold() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        for i in 0..10 {
            let result = strategy.update_ohlcv(
                100.0 + i as f64,
                110.0 + i as f64,
                90.0 + i as f64,
                100.0 + i as f64,
                1000.0,
            );
            assert_eq!(result.signal, MomentumSurgeSignal::Hold);
        }
        assert!(!strategy.is_ready());
    }

    #[test]
    fn test_becomes_ready_after_warmup() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);
        assert!(strategy.is_ready());
    }

    // ── Price history tests ──────────────────────────────────────────────

    #[test]
    fn test_price_history_basic() {
        let mut history = PriceHistory::new(10);
        for i in 0..5 {
            history.push(PricePoint {
                high: 100.0 + i as f64,
                low: 90.0 + i as f64,
                close: 95.0 + i as f64,
                is_bullish: true,
            });
        }
        assert_eq!(history.len(), 5);
    }

    #[test]
    fn test_price_history_max_size() {
        let mut history = PriceHistory::new(5);
        for i in 0..10 {
            history.push(PricePoint {
                high: 100.0 + i as f64,
                low: 90.0 + i as f64,
                close: 95.0 + i as f64,
                is_bullish: true,
            });
        }
        assert_eq!(history.len(), 5);
    }

    #[test]
    fn test_price_change_pct() {
        let mut history = PriceHistory::new(20);
        // Price goes from 100 to 110 over 10 candles
        for i in 0..10 {
            history.push(PricePoint {
                high: 100.0 + i as f64 + 5.0,
                low: 100.0 + i as f64 - 5.0,
                close: 100.0 + i as f64,
                is_bullish: true,
            });
        }
        // Lookback of 9 candles: from close=100 to close=109
        let pct = history.price_change_pct(9).unwrap();
        assert!((pct - 9.0).abs() < 0.01);
    }

    #[test]
    fn test_recent_high_low() {
        let mut history = PriceHistory::new(20);
        history.push(PricePoint {
            high: 110.0,
            low: 90.0,
            close: 100.0,
            is_bullish: true,
        });
        history.push(PricePoint {
            high: 120.0,
            low: 85.0,
            close: 105.0,
            is_bullish: true,
        });
        history.push(PricePoint {
            high: 115.0,
            low: 88.0,
            close: 102.0,
            is_bullish: true,
        });

        assert!((history.recent_high(3).unwrap() - 120.0).abs() < 1e-10);
        assert!((history.recent_low(3).unwrap() - 85.0).abs() < 1e-10);

        // Only last 2
        assert!((history.recent_high(2).unwrap() - 120.0).abs() < 1e-10);
        assert!((history.recent_low(2).unwrap() - 85.0).abs() < 1e-10);

        // Only last 1
        assert!((history.recent_high(1).unwrap() - 115.0).abs() < 1e-10);
        assert!((history.recent_low(1).unwrap() - 88.0).abs() < 1e-10);
    }

    // ── Volume analyzer tests ────────────────────────────────────────────

    #[test]
    fn test_volume_analyzer_basic() {
        let mut va = VolumeAnalyzer::new(5);
        let mult = va.update(100.0);
        assert!((mult - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_volume_analyzer_spike() {
        let mut va = VolumeAnalyzer::new(5);
        for _ in 0..5 {
            va.update(100.0);
        }
        let mult = va.update(500.0);
        assert!(mult > 4.0);
    }

    // ── Regime gating tests ──────────────────────────────────────────────

    #[test]
    fn test_should_trade_in_trending_bullish() {
        assert!(MomentumSurgeStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
    }

    #[test]
    fn test_should_trade_in_trending_bearish() {
        assert!(MomentumSurgeStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_trade_in_volatile() {
        assert!(MomentumSurgeStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_should_not_trade_in_mean_reverting() {
        assert!(!MomentumSurgeStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_not_trade_in_uncertain() {
        assert!(!MomentumSurgeStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_regime_size_factor_trending() {
        let factor = MomentumSurgeStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.7,
        );
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.7).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_trending_clamped() {
        let factor = MomentumSurgeStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.95,
        );
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.8).abs() < 1e-10); // clamped to 0.8
    }

    #[test]
    fn test_regime_size_factor_volatile() {
        let factor = MomentumSurgeStrategy::regime_size_factor(&MarketRegime::Volatile, 0.7);
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.35).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_mean_reverting_is_none() {
        let factor = MomentumSurgeStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.8);
        assert!(factor.is_none());
    }

    // ── Reset tests ──────────────────────────────────────────────────────

    #[test]
    fn test_full_reset() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);
        assert!(strategy.is_ready());

        strategy.reset();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.history_len(), 0);
        assert!(strategy.last_atr().is_none());
    }

    // ── Position tracking tests ──────────────────────────────────────────

    #[test]
    fn test_not_in_position_initially() {
        let strategy = MomentumSurgeStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    #[test]
    fn test_internal_position_tracking() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        strategy.enter_position(MomentumSurgeSignal::Buy, 50000.0, 49500.0, 51500.0);
        assert!(strategy.is_in_position());
        assert_eq!(strategy.entry_price(), Some(50000.0));
        assert_eq!(strategy.stop_loss(), Some(49500.0));
        assert_eq!(strategy.take_profit(), Some(51500.0));

        strategy.exit_position();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
    }

    // ── Signal display tests ─────────────────────────────────────────────

    #[test]
    fn test_signal_display() {
        assert_eq!(format!("{}", MomentumSurgeSignal::Buy), "BUY");
        assert_eq!(format!("{}", MomentumSurgeSignal::Sell), "SELL");
        assert_eq!(format!("{}", MomentumSurgeSignal::Hold), "HOLD");
    }

    #[test]
    fn test_signal_serialization() {
        let signal = MomentumSurgeSignal::Buy;
        let json = serde_json::to_string(&signal).unwrap();
        let deserialized: MomentumSurgeSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, signal);
    }

    // ── Momentum detection test ──────────────────────────────────────────

    #[test]
    fn test_bullish_surge_detection() {
        let mut strategy = MomentumSurgeStrategy::new(MomentumSurgeConfig {
            lookback_candles: 10,
            momentum_threshold_pct: 5.0,
            volume_spike_multiplier: 2.0,
            pullback_threshold: 0.003,
            min_confidence: 0.40,
            warmup_candles: 15,
            ..Default::default()
        });

        // Warmup with stable prices and volume
        for i in 0..15 {
            let price = 1000.0 + (i as f64) * 0.1;
            strategy.update_ohlcv(price - 1.0, price + 2.0, price - 2.0, price, 100.0);
        }

        assert!(strategy.is_ready());

        // Now spike the price up 10% over 5 candles
        for i in 0..5 {
            let base = 1001.5 + (i as f64) * 22.0;
            strategy.update_ohlcv(
                base - 5.0,
                base + 10.0,
                base - 10.0,
                base,
                500.0, // 5x normal volume
            );
        }

        // After the spike, add a small pullback candle
        let peak = 1001.5 + 4.0 * 22.0; // ~1089.5
        let pullback_price = peak * 0.994; // pulled back slightly
        let result = strategy.update_ohlcv(
            pullback_price - 3.0, // open below close = bullish
            pullback_price + 5.0,
            pullback_price - 5.0,
            pullback_price, // bullish close above open
            600.0,          // still elevated volume
        );

        // We should see either Buy or Hold; the key is no panic
        // Exact signal depends on indicator warmup state
        assert!(
            result.signal == MomentumSurgeSignal::Buy || result.signal == MomentumSurgeSignal::Hold
        );
        assert!(!result.reason.is_empty());
    }

    // ── Stress test ──────────────────────────────────────────────────────

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = MomentumSurgeStrategy::new(MomentumSurgeConfig::crypto_aggressive());
        let mut price = 50000.0;
        for i in 0..2000 {
            let direction = if (i / 80) % 2 == 0 { 1.0 } else { -1.0 };
            price += direction * 25.0 + (i as f64 * 0.1).sin() * 40.0;
            price = price.max(100.0); // keep positive
            let high = price + 30.0;
            let low = price - 30.0;
            let open = price - direction * 5.0;
            let volume = 1000.0 + (i as f64 * 0.3).cos().abs() * 3000.0;
            let _ = strategy.update_ohlcv(open, high, low, price, volume);
        }
        assert_eq!(strategy.candle_count(), 2000);
        // History should be capped at max_history
        assert!(strategy.history_len() <= strategy.config().max_history);
    }

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        let result = strategy.update_ohlcv(50000.0, 50010.0, 49990.0, 50000.0, 1000.0);
        assert!(!result.reason.is_empty());
    }

    #[test]
    fn test_config_accessor() {
        let strategy = MomentumSurgeStrategy::with_defaults();
        assert_eq!(strategy.config().lookback_candles, 15);
        assert!((strategy.config().momentum_threshold_pct - 5.0).abs() < 1e-10);
    }

    // ── HLC interface test ───────────────────────────────────────────────

    #[test]
    fn test_hlc_interface() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        for i in 0..25 {
            let price = 50000.0 + i as f64;
            strategy.update_hlc(price + 10.0, price - 10.0, price);
        }
        assert!(strategy.is_ready());
        assert!(strategy.last_atr().is_some());
    }

    // ── Get momentum test ────────────────────────────────────────────────

    #[test]
    fn test_get_momentum_not_ready() {
        let strategy = MomentumSurgeStrategy::with_defaults();
        assert!(strategy.get_momentum().is_none());
    }

    #[test]
    fn test_get_momentum_after_warmup() {
        let mut strategy = MomentumSurgeStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);
        let momentum = strategy.get_momentum();
        assert!(momentum.is_some());
        let (pct, _vol) = momentum.unwrap();
        // Should be a small positive change since we trend up slightly
        assert!(pct > 0.0);
    }
}
