//! # Multi-Timeframe Trend Strategy
//!
//! Swing-timeframe trend strategy using EMA 50/200 crossover with ADX trend
//! strength confirmation and higher-timeframe (HTF) trend alignment.
//!
//! ## How It Works
//!
//! 1. **Trend Direction**: EMA 50 vs EMA 200 determines the primary trend.
//!    Price must be on the correct side of the 200 EMA.
//!
//! 2. **Trend Strength**: ADX must be above a configurable threshold (default:
//!    25.0) to confirm that the market is actually trending, not just drifting.
//!
//! 3. **Pullback Entry**: Rather than entering on the initial crossover, the
//!    strategy waits for price to pull back to the 50 EMA within an
//!    established trend. This gives better risk/reward.
//!
//! 4. **HTF Alignment**: An externally-set higher-timeframe trend bias must
//!    agree with the setup direction. This prevents counter-trend entries on
//!    the lower timeframe.
//!
//! 5. **Candle Confirmation**: The entry candle must be directionally aligned
//!    with a strong body (body > 60% of range).
//!
//! 6. **ATR-Based Stops**: Stop loss at the 200 EMA ± ATR multiple, take
//!    profit at a larger ATR multiple from entry.
//!
//! ## Regime Integration
//!
//! This is a pure trend-following strategy:
//!
//! - **Trending(Bullish/Bearish)** → Yes (primary use case)
//! - **Volatile** → No (ADX can be misleading in volatile chop)
//! - **MeanReverting** → No (no trend to follow)
//! - **Uncertain** → No (wait for clarity)
//!
//! ## Differences from Kraken Version
//!
//! The Kraken `MultiTimeframeTrend` used a multi-symbol HashMap and its own
//! local indicator types. This JANUS version uses `janus-regime` indicators
//! (EMA, ATR, ADX) and follows the single-asset pattern established by
//! other JANUS strategies (VwapScalper, OrbStrategy, etc.).
//!
//! The strategy requires more candles to warm up (200+ for the long EMA) and
//! is intended for higher-timeframe candles. In the JANUS pipeline, this can
//! be fed from a separate candle aggregator with a larger tick-per-candle
//! setting, or from pre-aggregated candle data.
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/swing.rs::MultiTimeframeTrend`, adapted for
//! the JANUS single-asset design, `janus-regime` indicator types, and
//! regime-aware position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::{ADX, ATR, EMA};
use janus_regime::types::TrendDirection;
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal Types
// ============================================================================

/// Signal generated by the Multi-Timeframe Trend strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MultiTfSignal {
    /// Enter long — bullish trend pullback to EMA 50 with ADX strength.
    Buy,
    /// Enter short / exit long — bearish trend pullback with ADX strength.
    Sell,
    /// No action.
    Hold,
}

impl std::fmt::Display for MultiTfSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MultiTfSignal::Buy => write!(f, "BUY"),
            MultiTfSignal::Sell => write!(f, "SELL"),
            MultiTfSignal::Hold => write!(f, "HOLD"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the Multi-Timeframe Trend strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MultiTfConfig {
    /// Short EMA period (default: 50).
    pub ema_short_period: usize,

    /// Long EMA period (default: 200).
    pub ema_long_period: usize,

    /// ADX period for trend strength measurement (default: 14).
    pub adx_period: usize,

    /// ADX threshold — values above this confirm a trending market (default: 25.0).
    pub adx_threshold: f64,

    /// ATR period for volatility measurement (default: 14).
    pub atr_period: usize,

    /// ATR multiplier for stop-loss distance (default: 2.0).
    pub atr_stop_multiplier: f64,

    /// ATR multiplier for take-profit distance (default: 4.0).
    pub atr_tp_multiplier: f64,

    /// Pullback tolerance — how far above/below the short EMA the price can
    /// be and still count as a "pullback". Expressed as a fraction of price
    /// (default: 0.01 = 1%).
    pub pullback_tolerance: f64,

    /// Minimum candle body ratio (body / range) for entry confirmation
    /// (default: 0.60).
    pub min_body_ratio: f64,

    /// Minimum confidence score to emit a signal (default: 0.55).
    pub min_confidence: f64,

    /// Minimum number of candles before the strategy is ready (default: 210).
    /// Must be at least `ema_long_period + 10` to ensure the 200 EMA has
    /// warmed up.
    pub warmup_candles: usize,
}

impl Default for MultiTfConfig {
    fn default() -> Self {
        Self {
            ema_short_period: 50,
            ema_long_period: 200,
            adx_period: 14,
            adx_threshold: 25.0,
            atr_period: 14,
            atr_stop_multiplier: 2.0,
            atr_tp_multiplier: 4.0,
            pullback_tolerance: 0.01,
            min_body_ratio: 0.60,
            min_confidence: 0.55,
            warmup_candles: 210,
        }
    }
}

impl MultiTfConfig {
    /// Aggressive config for crypto — lower ADX threshold, tighter stops.
    pub fn crypto_aggressive() -> Self {
        Self {
            adx_threshold: 20.0,
            atr_stop_multiplier: 1.5,
            atr_tp_multiplier: 3.5,
            pullback_tolerance: 0.015,
            min_body_ratio: 0.50,
            min_confidence: 0.50,
            warmup_candles: 205,
            ..Default::default()
        }
    }

    /// Conservative config — higher ADX threshold, wider stops.
    pub fn conservative() -> Self {
        Self {
            adx_threshold: 30.0,
            atr_stop_multiplier: 2.5,
            atr_tp_multiplier: 5.0,
            pullback_tolerance: 0.008,
            min_body_ratio: 0.65,
            min_confidence: 0.65,
            warmup_candles: 215,
            ..Default::default()
        }
    }
}

// ============================================================================
// Detailed Result
// ============================================================================

/// Detailed result from a Multi-Timeframe Trend strategy update.
#[derive(Debug, Clone)]
pub struct MultiTfResult {
    /// The signal produced.
    pub signal: MultiTfSignal,
    /// Current short EMA value (50-period).
    pub ema_short: Option<f64>,
    /// Current long EMA value (200-period).
    pub ema_long: Option<f64>,
    /// Current ADX value.
    pub adx: Option<f64>,
    /// Current ATR value.
    pub atr: Option<f64>,
    /// Detected lower-timeframe trend direction.
    pub ltf_trend: Option<TrendDirection>,
    /// HTF trend bias (externally set).
    pub htf_trend: Option<TrendDirection>,
    /// Confidence score (0.0–1.0).
    pub confidence: f64,
    /// Computed stop-loss price.
    pub stop_loss: Option<f64>,
    /// Computed take-profit price.
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// Strategy
// ============================================================================

/// Multi-Timeframe Trend Strategy
///
/// Swing-timeframe EMA 50/200 crossover with ADX trend strength and HTF
/// alignment. Single-asset — instantiate one per symbol.
#[derive(Debug)]
pub struct MultiTfTrendStrategy {
    config: MultiTfConfig,

    // Indicators
    ema_short: EMA,
    ema_long: EMA,
    adx: ADX,
    atr: ATR,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<MultiTfSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Last computed values (cached)
    last_ema_short: Option<f64>,
    last_ema_long: Option<f64>,
    last_adx: Option<f64>,
    last_atr: Option<f64>,
    last_signal: MultiTfSignal,
    candle_count: usize,

    // HTF trend bias (set externally from higher-timeframe analysis)
    htf_trend: Option<TrendDirection>,
}

impl MultiTfTrendStrategy {
    /// Create a new Multi-TF Trend strategy with the given config.
    pub fn new(config: MultiTfConfig) -> Self {
        let ema_short = EMA::new(config.ema_short_period);
        let ema_long = EMA::new(config.ema_long_period);
        let adx = ADX::new(config.adx_period);
        let atr = ATR::new(config.atr_period);

        Self {
            ema_short,
            ema_long,
            adx,
            atr,
            config,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            last_ema_short: None,
            last_ema_long: None,
            last_adx: None,
            last_atr: None,
            last_signal: MultiTfSignal::Hold,
            candle_count: 0,
            htf_trend: None,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(MultiTfConfig::default())
    }

    /// Set higher-timeframe trend bias. When set, long setups require HTF
    /// bullish, short setups require HTF bearish. If not set (None or Flat
    /// equivalent), the strategy will not produce signals — HTF alignment
    /// is mandatory for this strategy.
    pub fn set_htf_trend(&mut self, trend: TrendDirection) {
        self.htf_trend = Some(trend);
    }

    /// Clear the HTF trend bias. Without an HTF trend, this strategy will
    /// not produce any signals.
    pub fn clear_htf_trend(&mut self) {
        self.htf_trend = None;
    }

    /// Update with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> MultiTfSignal {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
        .signal
    }

    /// Update with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(&mut self, candle: &janus_models::Candle) -> MultiTfResult {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
    }

    /// Main update with OHLCV values — returns a detailed result.
    pub fn update_ohlcv(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        _volume: f64,
    ) -> MultiTfResult {
        self.candle_count += 1;

        // Update indicators
        self.ema_short.update(close);
        self.ema_long.update(close);
        self.adx.update(high, low, close);
        self.atr.update(high, low, close);

        self.last_ema_short = self.ema_short.value();
        self.last_ema_long = self.ema_long.value();
        self.last_adx = self.adx.value();
        self.last_atr = self.atr.value();

        // Not ready yet?
        if self.candle_count < self.config.warmup_candles {
            return self.make_result(MultiTfSignal::Hold, 0.0, "Warming up".to_string());
        }

        let ema_s = match self.last_ema_short {
            Some(v) => v,
            None => {
                return self.make_result(
                    MultiTfSignal::Hold,
                    0.0,
                    "Short EMA not ready".to_string(),
                );
            }
        };
        let ema_l = match self.last_ema_long {
            Some(v) => v,
            None => {
                return self.make_result(
                    MultiTfSignal::Hold,
                    0.0,
                    "Long EMA not ready".to_string(),
                );
            }
        };
        let adx_val = self.last_adx.unwrap_or(0.0);
        let atr_val = match self.last_atr {
            Some(a) if a > 0.0 => a,
            _ => {
                return self.make_result(MultiTfSignal::Hold, 0.0, "ATR not ready".to_string());
            }
        };

        // Determine lower-timeframe trend from EMAs
        let ltf_trend = if ema_s > ema_l {
            TrendDirection::Bullish
        } else {
            TrendDirection::Bearish
        };

        // HTF trend is mandatory for this strategy
        let htf_trend = match self.htf_trend {
            Some(t) => t,
            None => {
                return self.make_result(
                    MultiTfSignal::Hold,
                    0.0,
                    "No HTF trend set — waiting for higher-timeframe signal".to_string(),
                );
            }
        };

        // Candle properties
        let body = (close - open).abs();
        let range = high - low;
        let is_bullish = close > open;
        let is_bearish = close < open;
        let body_ratio = if range > 0.0 { body / range } else { 0.0 };
        let price = close;

        // Check for exit if in position
        if self.in_position
            && let Some(ref side) = self.entry_side
        {
            let exit = self.check_exit(close, ema_l, atr_val, side);
            if let Some(exit_signal) = exit {
                self.exit_position();
                return self.make_result(
                    exit_signal,
                    0.8,
                    format!("MTF exit: price {:.2} (EMA200={:.2})", close, ema_l),
                );
            }
        }

        // Already in position — don't open another
        if self.in_position {
            return self.make_result(MultiTfSignal::Hold, 0.0, "In position".to_string());
        }

        // === BULLISH SETUP ===
        // HTF bullish + price > 200 EMA + ADX strong + pullback to 50 EMA + bullish candle
        if htf_trend == TrendDirection::Bullish
            && price > ema_l
            && adx_val >= self.config.adx_threshold
            && price <= ema_s * (1.0 + self.config.pullback_tolerance)
            && is_bullish
        {
            let stop = ema_l - atr_val * self.config.atr_stop_multiplier;
            let tp = price + atr_val * self.config.atr_tp_multiplier;

            let mut confidence: f64 = 0.40;

            // LTF trend agreement (EMA50 > EMA200)
            if ltf_trend == TrendDirection::Bullish {
                confidence += 0.15;
            }

            // Strong ADX
            if adx_val > 30.0 {
                confidence += 0.10;
            }

            // Strong candle body
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.10;
            }

            // Close above both EMAs
            if price > ema_s && price > ema_l {
                confidence += 0.05;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                self.enter_position(MultiTfSignal::Buy, price, stop, tp);
                self.last_signal = MultiTfSignal::Buy;

                return self.make_result(
                    MultiTfSignal::Buy,
                    confidence,
                    format!(
                        "MTF bullish: pullback to EMA50 {:.2}, ADX {:.1}, price > EMA200 {:.2}, body {:.0}%",
                        ema_s, adx_val, ema_l, body_ratio * 100.0
                    ),
                );
            }
        }

        // === BEARISH SETUP ===
        // HTF bearish + price < 200 EMA + ADX strong + pullback to 50 EMA + bearish candle
        if htf_trend == TrendDirection::Bearish
            && price < ema_l
            && adx_val >= self.config.adx_threshold
            && price >= ema_s * (1.0 - self.config.pullback_tolerance)
            && is_bearish
        {
            let stop = ema_l + atr_val * self.config.atr_stop_multiplier;
            let tp = price - atr_val * self.config.atr_tp_multiplier;

            let mut confidence: f64 = 0.40;

            // LTF trend agreement
            if ltf_trend == TrendDirection::Bearish {
                confidence += 0.15;
            }

            // Strong ADX
            if adx_val > 30.0 {
                confidence += 0.10;
            }

            // Strong candle body
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.10;
            }

            // Close below both EMAs
            if price < ema_s && price < ema_l {
                confidence += 0.05;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                self.enter_position(MultiTfSignal::Sell, price, stop, tp);
                self.last_signal = MultiTfSignal::Sell;

                return self.make_result(
                    MultiTfSignal::Sell,
                    confidence,
                    format!(
                        "MTF bearish: pullback to EMA50 {:.2}, ADX {:.1}, price < EMA200 {:.2}, body {:.0}%",
                        ema_s, adx_val, ema_l, body_ratio * 100.0
                    ),
                );
            }
        }

        self.last_signal = MultiTfSignal::Hold;
        self.make_result(
            MultiTfSignal::Hold,
            0.0,
            format!(
                "No signal: price {:.2}, EMA50={:.2}, EMA200={:.2}, ADX={:.1}, HTF={:?}, LTF={:?}",
                price, ema_s, ema_l, adx_val, htf_trend, ltf_trend
            ),
        )
    }

    /// Update with HLC values (no volume).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> MultiTfResult {
        self.update_ohlcv(close, high, low, close, 0.0)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// Multi-TF Trend is purely trend-following — it only works in clearly
    /// trending markets. Unlike other trend strategies, it does NOT trade in
    /// volatile markets because ADX readings become unreliable during high
    /// volatility chop.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(regime, MarketRegime::Trending(_))
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    ///
    /// Returns `Some(factor)` if the regime is suitable, `None` otherwise.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::Trending(_) => {
                // Primary regime — full confidence scaling
                Some(confidence.clamp(0.4, 1.0))
            }
            _ => None,
        }
    }

    // ========================================================================
    // Trend info accessor
    // ========================================================================

    /// Get the current trend info: (ltf_trend, adx_value).
    /// Returns None if indicators are not ready.
    pub fn get_trend_info(&self) -> Option<(TrendDirection, f64)> {
        let ema_s = self.last_ema_short?;
        let ema_l = self.last_ema_long?;
        let adx = self.last_adx.unwrap_or(0.0);

        let trend = if ema_s > ema_l {
            TrendDirection::Bullish
        } else {
            TrendDirection::Bearish
        };

        Some((trend, adx))
    }

    // ========================================================================
    // Position management (internal)
    // ========================================================================

    fn enter_position(&mut self, side: MultiTfSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(
        &self,
        close: f64,
        ema_long: f64,
        _atr: f64,
        side: &MultiTfSignal,
    ) -> Option<MultiTfSignal> {
        match side {
            MultiTfSignal::Buy => {
                // Exit long if price closes below 200 EMA (major trend break)
                if close < ema_long {
                    return Some(MultiTfSignal::Sell);
                }
                // Stop loss
                if let Some(stop) = self.stop_loss
                    && close <= stop
                {
                    return Some(MultiTfSignal::Sell);
                }
                // Take profit
                if let Some(tp) = self.take_profit
                    && close >= tp
                {
                    return Some(MultiTfSignal::Sell);
                }
                None
            }
            MultiTfSignal::Sell => {
                // Exit short if price closes above 200 EMA
                if close > ema_long {
                    return Some(MultiTfSignal::Buy);
                }
                if let Some(stop) = self.stop_loss
                    && close >= stop
                {
                    return Some(MultiTfSignal::Buy);
                }
                if let Some(tp) = self.take_profit
                    && close <= tp
                {
                    return Some(MultiTfSignal::Buy);
                }
                None
            }
            MultiTfSignal::Hold => None,
        }
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(&self, signal: MultiTfSignal, confidence: f64, reason: String) -> MultiTfResult {
        let ltf_trend = match (self.last_ema_short, self.last_ema_long) {
            (Some(s), Some(l)) if s > l => Some(TrendDirection::Bullish),
            (Some(s), Some(l)) if s < l => Some(TrendDirection::Bearish),
            _ => None,
        };

        MultiTfResult {
            signal,
            ema_short: self.last_ema_short,
            ema_long: self.last_ema_long,
            adx: self.last_adx,
            atr: self.last_atr,
            ltf_trend,
            htf_trend: self.htf_trend,
            confidence,
            stop_loss: if matches!(signal, MultiTfSignal::Buy | MultiTfSignal::Sell) {
                self.stop_loss
            } else {
                None
            },
            take_profit: if matches!(signal, MultiTfSignal::Buy | MultiTfSignal::Sell) {
                self.take_profit
            } else {
                None
            },
            reason,
        }
    }

    // ========================================================================
    // Reset
    // ========================================================================

    /// Full reset — clears all indicator and position state.
    pub fn reset(&mut self) {
        self.ema_short = EMA::new(self.config.ema_short_period);
        self.ema_long = EMA::new(self.config.ema_long_period);
        self.adx = ADX::new(self.config.adx_period);
        self.atr = ATR::new(self.config.atr_period);
        self.exit_position();
        self.last_ema_short = None;
        self.last_ema_long = None;
        self.last_adx = None;
        self.last_atr = None;
        self.last_signal = MultiTfSignal::Hold;
        self.candle_count = 0;
        self.htf_trend = None;
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Whether the strategy has enough data to produce signals.
    pub fn is_ready(&self) -> bool {
        self.candle_count >= self.config.warmup_candles
            && self.last_ema_short.is_some()
            && self.last_ema_long.is_some()
            && self.last_atr.is_some()
    }

    /// Whether the strategy currently has an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// The last short EMA value (50-period).
    pub fn last_ema_short(&self) -> Option<f64> {
        self.last_ema_short
    }

    /// The last long EMA value (200-period).
    pub fn last_ema_long(&self) -> Option<f64> {
        self.last_ema_long
    }

    /// The last ADX value.
    pub fn last_adx(&self) -> Option<f64> {
        self.last_adx
    }

    /// The last ATR value.
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// The last signal produced.
    pub fn last_signal(&self) -> MultiTfSignal {
        self.last_signal
    }

    /// Total candles processed.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Current entry price (if in position).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Current stop loss (if in position).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Current take profit (if in position).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// Strategy configuration.
    pub fn config(&self) -> &MultiTfConfig {
        &self.config
    }

    /// Current HTF trend bias (if set).
    pub fn htf_trend(&self) -> Option<TrendDirection> {
        self.htf_trend
    }

    /// Detected LTF trend from EMAs.
    pub fn detected_ltf_trend(&self) -> Option<TrendDirection> {
        match (self.last_ema_short, self.last_ema_long) {
            (Some(s), Some(l)) if s > l => Some(TrendDirection::Bullish),
            (Some(s), Some(l)) if s < l => Some(TrendDirection::Bearish),
            _ => None,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Feed candles to warm up the strategy with a given trend.
    fn warm_up_trend(
        strategy: &mut MultiTfTrendStrategy,
        base_price: f64,
        count: usize,
        step: f64,
    ) {
        for i in 0..count {
            let price = base_price + (i as f64) * step;
            strategy.update_ohlcv(price - 5.0, price + 20.0, price - 20.0, price, 1000.0);
        }
    }

    // ── Config tests ─────────────────────────────────────────────────────

    #[test]
    fn test_default_config() {
        let config = MultiTfConfig::default();
        assert_eq!(config.ema_short_period, 50);
        assert_eq!(config.ema_long_period, 200);
        assert_eq!(config.adx_period, 14);
        assert!((config.adx_threshold - 25.0).abs() < 1e-10);
        assert_eq!(config.atr_period, 14);
        assert!((config.atr_stop_multiplier - 2.0).abs() < 1e-10);
        assert!((config.atr_tp_multiplier - 4.0).abs() < 1e-10);
        assert!((config.pullback_tolerance - 0.01).abs() < 1e-10);
        assert!((config.min_body_ratio - 0.60).abs() < 1e-10);
        assert!((config.min_confidence - 0.55).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 210);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = MultiTfConfig::crypto_aggressive();
        assert!((config.adx_threshold - 20.0).abs() < 1e-10);
        assert!((config.atr_stop_multiplier - 1.5).abs() < 1e-10);
        assert!((config.min_confidence - 0.50).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 205);
    }

    #[test]
    fn test_conservative_config() {
        let config = MultiTfConfig::conservative();
        assert!((config.adx_threshold - 30.0).abs() < 1e-10);
        assert!((config.atr_stop_multiplier - 2.5).abs() < 1e-10);
        assert!((config.min_confidence - 0.65).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 215);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = MultiTfConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: MultiTfConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.ema_short_period, config.ema_short_period);
        assert_eq!(deserialized.ema_long_period, config.ema_long_period);
        assert_eq!(deserialized.adx_period, config.adx_period);
    }

    // ── Strategy creation tests ──────────────────────────────────────────

    #[test]
    fn test_strategy_creation() {
        let strategy = MultiTfTrendStrategy::with_defaults();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.last_signal(), MultiTfSignal::Hold);
        assert!(strategy.htf_trend().is_none());
    }

    #[test]
    fn test_warmup_hold() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        for i in 0..50 {
            let result = strategy.update_ohlcv(
                100.0 + i as f64,
                110.0 + i as f64,
                90.0 + i as f64,
                100.0 + i as f64,
                1000.0,
            );
            assert_eq!(result.signal, MultiTfSignal::Hold);
        }
        assert!(!strategy.is_ready());
    }

    #[test]
    fn test_becomes_ready_after_warmup() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        warm_up_trend(&mut strategy, 50000.0, 220, 5.0);
        assert!(strategy.is_ready());
    }

    // ── HTF trend tests ──────────────────────────────────────────────────

    #[test]
    fn test_htf_trend_set_clear() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        assert!(strategy.htf_trend().is_none());

        strategy.set_htf_trend(TrendDirection::Bullish);
        assert_eq!(strategy.htf_trend(), Some(TrendDirection::Bullish));

        strategy.set_htf_trend(TrendDirection::Bearish);
        assert_eq!(strategy.htf_trend(), Some(TrendDirection::Bearish));

        strategy.clear_htf_trend();
        assert!(strategy.htf_trend().is_none());
    }

    #[test]
    fn test_no_signal_without_htf_trend() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        warm_up_trend(&mut strategy, 50000.0, 220, 5.0);
        assert!(strategy.is_ready());

        // Without HTF trend set, should always get Hold
        let result = strategy.update_ohlcv(
            51100.0 - 10.0,
            51100.0 + 20.0,
            51100.0 - 20.0,
            51100.0,
            1000.0,
        );
        assert_eq!(result.signal, MultiTfSignal::Hold);
        assert!(result.reason.contains("HTF trend"));
    }

    // ── Regime gating tests ──────────────────────────────────────────────

    #[test]
    fn test_should_trade_in_trending_bullish() {
        assert!(MultiTfTrendStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
    }

    #[test]
    fn test_should_trade_in_trending_bearish() {
        assert!(MultiTfTrendStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_not_trade_in_volatile() {
        assert!(!MultiTfTrendStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_should_not_trade_in_mean_reverting() {
        assert!(!MultiTfTrendStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_not_trade_in_uncertain() {
        assert!(!MultiTfTrendStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_regime_size_factor_trending() {
        let factor = MultiTfTrendStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.8,
        );
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.8).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_trending_clamped_low() {
        let factor = MultiTfTrendStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.2,
        );
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.4).abs() < 1e-10); // clamped to 0.4
    }

    #[test]
    fn test_regime_size_factor_volatile_is_none() {
        let factor = MultiTfTrendStrategy::regime_size_factor(&MarketRegime::Volatile, 0.8);
        assert!(factor.is_none());
    }

    #[test]
    fn test_regime_size_factor_mean_reverting_is_none() {
        let factor = MultiTfTrendStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.8);
        assert!(factor.is_none());
    }

    // ── Reset tests ──────────────────────────────────────────────────────

    #[test]
    fn test_full_reset() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        warm_up_trend(&mut strategy, 50000.0, 220, 5.0);
        assert!(strategy.is_ready());

        strategy.reset();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert!(strategy.last_ema_short().is_none());
        assert!(strategy.last_ema_long().is_none());
        assert!(strategy.last_adx().is_none());
        assert!(strategy.htf_trend().is_none());
    }

    // ── Position tracking tests ──────────────────────────────────────────

    #[test]
    fn test_not_in_position_initially() {
        let strategy = MultiTfTrendStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    #[test]
    fn test_internal_position_tracking() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        strategy.enter_position(MultiTfSignal::Buy, 50000.0, 48500.0, 54000.0);
        assert!(strategy.is_in_position());
        assert_eq!(strategy.entry_price(), Some(50000.0));
        assert_eq!(strategy.stop_loss(), Some(48500.0));
        assert_eq!(strategy.take_profit(), Some(54000.0));

        strategy.exit_position();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
    }

    // ── Signal display tests ─────────────────────────────────────────────

    #[test]
    fn test_signal_display() {
        assert_eq!(format!("{}", MultiTfSignal::Buy), "BUY");
        assert_eq!(format!("{}", MultiTfSignal::Sell), "SELL");
        assert_eq!(format!("{}", MultiTfSignal::Hold), "HOLD");
    }

    #[test]
    fn test_signal_serialization() {
        let signal = MultiTfSignal::Buy;
        let json = serde_json::to_string(&signal).unwrap();
        let deserialized: MultiTfSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, signal);
    }

    // ── Trend info tests ─────────────────────────────────────────────────

    #[test]
    fn test_get_trend_info_not_ready() {
        let strategy = MultiTfTrendStrategy::with_defaults();
        assert!(strategy.get_trend_info().is_none());
    }

    #[test]
    fn test_get_trend_info_after_warmup() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        // Uptrend
        warm_up_trend(&mut strategy, 50000.0, 220, 5.0);
        let info = strategy.get_trend_info();
        assert!(info.is_some());
        let (trend, adx) = info.unwrap();
        // With a consistent uptrend, LTF should be Bullish
        assert_eq!(trend, TrendDirection::Bullish);
        // ADX should be non-negative
        assert!(adx >= 0.0);
    }

    #[test]
    fn test_detected_ltf_trend_none_initially() {
        let strategy = MultiTfTrendStrategy::with_defaults();
        assert!(strategy.detected_ltf_trend().is_none());
    }

    #[test]
    fn test_detected_ltf_trend_bullish() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        warm_up_trend(&mut strategy, 50000.0, 220, 5.0);
        assert_eq!(strategy.detected_ltf_trend(), Some(TrendDirection::Bullish));
    }

    #[test]
    fn test_detected_ltf_trend_bearish() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        warm_up_trend(&mut strategy, 55000.0, 220, -5.0);
        assert_eq!(strategy.detected_ltf_trend(), Some(TrendDirection::Bearish));
    }

    // ── Accessor tests ───────────────────────────────────────────────────

    #[test]
    fn test_config_accessor() {
        let strategy = MultiTfTrendStrategy::with_defaults();
        assert_eq!(strategy.config().ema_short_period, 50);
        assert_eq!(strategy.config().ema_long_period, 200);
        assert_eq!(strategy.config().adx_period, 14);
    }

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        let result = strategy.update_ohlcv(50000.0, 50010.0, 49990.0, 50000.0, 1000.0);
        assert!(!result.reason.is_empty());
    }

    // ── HLC interface test ───────────────────────────────────────────────

    #[test]
    fn test_hlc_interface() {
        let mut strategy = MultiTfTrendStrategy::with_defaults();
        for i in 0..220 {
            let price = 50000.0 + i as f64 * 5.0;
            strategy.update_hlc(price + 10.0, price - 10.0, price);
        }
        assert!(strategy.is_ready());
        assert!(strategy.last_atr().is_some());
        assert!(strategy.last_ema_short().is_some());
        assert!(strategy.last_ema_long().is_some());
    }

    // ── Stress test ──────────────────────────────────────────────────────

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = MultiTfTrendStrategy::new(MultiTfConfig::crypto_aggressive());
        strategy.set_htf_trend(TrendDirection::Bullish);
        let mut price = 50000.0;
        for i in 0..2000 {
            let direction = if (i / 200) % 2 == 0 { 1.0 } else { -1.0 };
            price += direction * 10.0 + (i as f64 * 0.1).sin() * 20.0;
            let high = price + 25.0;
            let low = price - 25.0;
            let open = price - direction * 5.0;
            let _ = strategy.update_ohlcv(open, high, low, price, 1000.0);
        }
        assert_eq!(strategy.candle_count(), 2000);
    }

    #[test]
    fn test_many_candles_trend_change() {
        let mut strategy = MultiTfTrendStrategy::new(MultiTfConfig::crypto_aggressive());

        // Phase 1: uptrend with bullish HTF
        strategy.set_htf_trend(TrendDirection::Bullish);
        warm_up_trend(&mut strategy, 50000.0, 220, 5.0);
        assert!(strategy.is_ready());

        // Phase 2: switch to downtrend
        strategy.set_htf_trend(TrendDirection::Bearish);
        for i in 0..100 {
            let price = 51100.0 - (i as f64) * 10.0;
            strategy.update_ohlcv(price + 5.0, price + 20.0, price - 20.0, price, 1000.0);
        }

        // Should have processed all candles without panic
        assert_eq!(strategy.candle_count(), 320);
        assert!(strategy.is_ready());
    }
}
