//! # Opening Range Breakout (ORB) Strategy
//!
//! Defines the first N candles as the "opening range" and trades breakouts
//! above or below that range with volume confirmation. Targets 1–2× range
//! extension.
//!
//! ## How It Works
//!
//! 1. **Opening Range Formation**: The first `opening_range_candles` candles
//!    after a session start (or after calling `start_session()`) define the
//!    opening range — the highest high and lowest low during that period.
//!
//! 2. **Breakout Detection**: Once the opening range is complete, a close
//!    above the range high (bullish) or below the range low (bearish)
//!    triggers a breakout signal.
//!
//! 3. **Volume Confirmation**: Breakout candles with above-average volume
//!    receive a confidence boost. Strong candle bodies (large body relative
//!    to range) also add confidence.
//!
//! 4. **ATR-Based Stops**: Stop loss is placed at 0.5× ATR inside the
//!    opening range boundary. Take profit targets 1.5× the opening range
//!    size as a range extension.
//!
//! 5. **Session Reset**: Call `start_session()` at the beginning of each
//!    trading session to reset the opening range. For 24/7 crypto markets,
//!    use London or NY overlap as the session start.
//!
//! ## Regime Integration
//!
//! ORB works best when the market is transitioning from consolidation to
//! trend — it's a momentum/breakout strategy. Use `should_trade_in_regime()`
//! to gate activation:
//!
//! - **MeanReverting** → Yes (breakout from the range)
//! - **Uncertain** → Yes with reduced size (range may be forming)
//! - **Trending** → Conditional — only early in a trend
//! - **Volatile** → No (false breakouts are common)
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/intraday.rs::OpeningRangeBreakout`, adapted
//! for the JANUS single-asset design, `janus-regime` indicator types, and
//! regime-aware position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::ATR;
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal
// ============================================================================

/// Signal generated by the Opening Range Breakout strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrbSignal {
    /// Bullish breakout — price closed above the opening range high.
    BuyBreakout,
    /// Bearish breakout — price closed below the opening range low.
    SellBreakout,
    /// Opening range is still forming — no action yet.
    Forming,
    /// No signal — range is complete but no breakout detected.
    Hold,
}

impl std::fmt::Display for OrbSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OrbSignal::BuyBreakout => write!(f, "BuyBreakout"),
            OrbSignal::SellBreakout => write!(f, "SellBreakout"),
            OrbSignal::Forming => write!(f, "Forming"),
            OrbSignal::Hold => write!(f, "Hold"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the Opening Range Breakout strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrbConfig {
    /// Number of candles that define the opening range (default: 6).
    /// E.g. on a 5-minute chart, 6 candles = 30-minute opening range.
    pub opening_range_candles: usize,

    /// ATR period for stop-loss / volatility measurement (default: 14).
    pub atr_period: usize,

    /// ATR multiplier for stop offset inside the opening range boundary
    /// (default: 0.5). Stop = OR boundary − (ATR × this value).
    pub atr_stop_offset: f64,

    /// Take-profit multiplier applied to the opening range size
    /// (default: 1.5). TP = breakout price + range_size × this value.
    pub range_tp_multiplier: f64,

    /// Rolling volume lookback period for spike detection (default: 20).
    pub volume_period: usize,

    /// Minimum volume multiplier (vs rolling average) for a valid breakout
    /// (default: 1.2). Higher values require stronger volume confirmation.
    pub min_volume_multiplier: f64,

    /// Minimum confidence score to emit a signal (default: 0.55).
    pub min_confidence: f64,

    /// Minimum candle body ratio (body / range) for a "strong" breakout
    /// candle (default: 0.5).
    pub min_body_ratio: f64,

    /// Whether to allow re-entry after the first breakout in the same
    /// session (default: false). When false, only the first breakout
    /// per session is traded.
    pub allow_reentry: bool,
}

impl Default for OrbConfig {
    fn default() -> Self {
        Self {
            opening_range_candles: 6,
            atr_period: 14,
            atr_stop_offset: 0.5,
            range_tp_multiplier: 1.5,
            volume_period: 20,
            min_volume_multiplier: 1.2,
            min_confidence: 0.55,
            min_body_ratio: 0.5,
            allow_reentry: false,
        }
    }
}

impl OrbConfig {
    /// Aggressive config for crypto — shorter opening range, lower thresholds.
    pub fn crypto_aggressive() -> Self {
        Self {
            opening_range_candles: 4,
            atr_stop_offset: 0.3,
            range_tp_multiplier: 2.0,
            min_volume_multiplier: 1.0,
            min_confidence: 0.50,
            min_body_ratio: 0.45,
            allow_reentry: true,
            ..Default::default()
        }
    }

    /// Conservative config — longer opening range, stricter thresholds.
    pub fn conservative() -> Self {
        Self {
            opening_range_candles: 10,
            atr_stop_offset: 0.7,
            range_tp_multiplier: 1.2,
            min_volume_multiplier: 1.5,
            min_confidence: 0.65,
            min_body_ratio: 0.55,
            allow_reentry: false,
            ..Default::default()
        }
    }
}

// ============================================================================
// Detailed Result
// ============================================================================

/// Detailed result from an ORB strategy update.
#[derive(Debug, Clone)]
pub struct OrbResult {
    /// The signal produced.
    pub signal: OrbSignal,
    /// Opening range high (if complete).
    pub range_high: Option<f64>,
    /// Opening range low (if complete).
    pub range_low: Option<f64>,
    /// Opening range size (high - low).
    pub range_size: Option<f64>,
    /// Current ATR value (if available).
    pub atr: Option<f64>,
    /// Volume multiplier relative to rolling average.
    pub volume_multiplier: f64,
    /// Confidence score (0.0–1.0).
    pub confidence: f64,
    /// Computed stop-loss price (only set on breakout signals).
    pub stop_loss: Option<f64>,
    /// Computed take-profit price (only set on breakout signals).
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// Opening Range Tracker (internal)
// ============================================================================

/// Tracks the opening range for the current session.
#[derive(Debug)]
struct OpeningRangeTracker {
    /// Number of candles that define the range.
    range_candles: usize,
    /// High of the opening range.
    high: f64,
    /// Low of the opening range.
    low: f64,
    /// Number of candles seen so far in this session.
    candles_seen: usize,
    /// Whether the opening range is fully formed.
    is_complete: bool,
    /// Whether a session has been started.
    session_active: bool,
}

impl OpeningRangeTracker {
    fn new(range_candles: usize) -> Self {
        Self {
            range_candles: range_candles.max(1),
            high: f64::NEG_INFINITY,
            low: f64::INFINITY,
            candles_seen: 0,
            is_complete: false,
            session_active: false,
        }
    }

    /// Start a new session — resets the opening range.
    fn start_session(&mut self) {
        self.high = f64::NEG_INFINITY;
        self.low = f64::INFINITY;
        self.candles_seen = 0;
        self.is_complete = false;
        self.session_active = true;
    }

    /// Feed a candle to the opening range tracker.
    fn update(&mut self, high: f64, low: f64) {
        if !self.session_active || self.is_complete {
            return;
        }

        self.high = self.high.max(high);
        self.low = self.low.min(low);
        self.candles_seen += 1;

        if self.candles_seen >= self.range_candles {
            self.is_complete = true;
        }
    }

    /// The size of the opening range (high - low).
    fn range_size(&self) -> f64 {
        if self.high > f64::NEG_INFINITY && self.low < f64::INFINITY {
            self.high - self.low
        } else {
            0.0
        }
    }
}

// ============================================================================
// Volume Analyzer (internal)
// ============================================================================

/// Rolling volume analyzer — detects volume spikes relative to the moving
/// average of recent candle volumes.
#[derive(Debug)]
struct VolumeAnalyzer {
    period: usize,
    volumes: Vec<f64>,
}

impl VolumeAnalyzer {
    fn new(period: usize) -> Self {
        Self {
            period: period.max(1),
            volumes: Vec::with_capacity(period),
        }
    }

    /// Push a new volume value. Returns the multiplier (volume / rolling avg).
    /// Returns 1.0 if there's no history yet.
    fn update(&mut self, volume: f64) -> f64 {
        let avg = self.average();

        self.volumes.push(volume);
        if self.volumes.len() > self.period {
            self.volumes.remove(0);
        }

        if avg > 0.0 { volume / avg } else { 1.0 }
    }

    /// Rolling average volume over the configured period.
    fn average(&self) -> f64 {
        if self.volumes.is_empty() {
            0.0
        } else {
            self.volumes.iter().sum::<f64>() / self.volumes.len() as f64
        }
    }
}

// ============================================================================
// Strategy
// ============================================================================

/// Opening Range Breakout Strategy
///
/// Tracks the opening range for a trading session and generates breakout
/// signals when price escapes the range with confirmation. Single-asset —
/// instantiate one per symbol.
#[derive(Debug)]
pub struct OrbStrategy {
    config: OrbConfig,

    // Components
    range: OpeningRangeTracker,
    atr: ATR,
    volume_analyzer: VolumeAnalyzer,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<OrbSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Session tracking
    breakout_fired: bool,

    // Last computed values
    last_atr: Option<f64>,
    last_signal: OrbSignal,
    candle_count: usize,
}

impl OrbStrategy {
    /// Create a new Opening Range Breakout strategy with the given config.
    pub fn new(config: OrbConfig) -> Self {
        let atr = ATR::new(config.atr_period);
        let volume_analyzer = VolumeAnalyzer::new(config.volume_period);
        let range = OpeningRangeTracker::new(config.opening_range_candles);

        Self {
            range,
            atr,
            volume_analyzer,
            config,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            breakout_fired: false,
            last_atr: None,
            last_signal: OrbSignal::Hold,
            candle_count: 0,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(OrbConfig::default())
    }

    /// Start a new trading session. Must be called before the strategy
    /// can generate breakout signals.
    ///
    /// For crypto (24/7 markets), call this at your chosen session boundary
    /// (e.g. 00:00 UTC, London open at 08:00 UTC, or NY open at 13:00 UTC).
    pub fn start_session(&mut self) {
        self.range.start_session();
        self.breakout_fired = false;
        self.exit_position();
    }

    /// Update the strategy with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> OrbSignal {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
        .signal
    }

    /// Update the strategy with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(&mut self, candle: &janus_models::Candle) -> OrbResult {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
    }

    /// Update with OHLCV values and return detailed result.
    pub fn update_ohlcv(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
    ) -> OrbResult {
        self.candle_count += 1;

        // Update ATR (always, even before session starts)
        self.atr.update(high, low, close);
        self.last_atr = self.atr.value();

        // Update volume analyzer
        let vol_mult = self.volume_analyzer.update(volume);

        // No session active
        if !self.range.session_active {
            return self.make_result(
                OrbSignal::Hold,
                vol_mult,
                0.0,
                "No session active — call start_session()".to_string(),
            );
        }

        // Still forming the opening range
        if !self.range.is_complete {
            self.range.update(high, low);

            if self.range.is_complete {
                return self.make_result(
                    OrbSignal::Forming,
                    vol_mult,
                    0.0,
                    format!(
                        "Opening range complete: high={:.2}, low={:.2}, size={:.2}",
                        self.range.high,
                        self.range.low,
                        self.range.range_size()
                    ),
                );
            }

            return self.make_result(
                OrbSignal::Forming,
                vol_mult,
                0.0,
                format!(
                    "Forming opening range: {}/{} candles, high={:.2}, low={:.2}",
                    self.range.candles_seen,
                    self.range.range_candles,
                    if self.range.high > f64::NEG_INFINITY {
                        self.range.high
                    } else {
                        0.0
                    },
                    if self.range.low < f64::INFINITY {
                        self.range.low
                    } else {
                        0.0
                    },
                ),
            );
        }

        let or_high = self.range.high;
        let or_low = self.range.low;
        let or_range = self.range.range_size();

        if or_range <= 0.0 {
            return self.make_result(
                OrbSignal::Hold,
                vol_mult,
                0.0,
                "Opening range has zero size".to_string(),
            );
        }

        // Check if breakout already fired (no re-entry unless configured)
        if self.breakout_fired && !self.config.allow_reentry {
            return self.make_result(
                OrbSignal::Hold,
                vol_mult,
                0.0,
                "Breakout already fired this session".to_string(),
            );
        }

        let atr_val = match self.atr.value() {
            Some(a) if a > 0.0 => a,
            _ => {
                return self.make_result(
                    OrbSignal::Hold,
                    vol_mult,
                    0.0,
                    "ATR not ready".to_string(),
                );
            }
        };

        // Candle properties
        let body = (close - open).abs();
        let range_candle = high - low;
        let is_bullish = close > open;
        let is_bearish = close < open;
        let body_ratio = if range_candle > 0.0 {
            body / range_candle
        } else {
            0.0
        };

        // Check for exit if in position
        if self.in_position
            && let Some(ref side) = self.entry_side
        {
            let exit = self.check_exit(close, side);
            if let Some(exit_signal) = exit {
                self.exit_position();
                return self.make_result(
                    exit_signal,
                    vol_mult,
                    0.8,
                    format!("ORB exit: price {:.2} reached TP/SL", close),
                );
            }
        }

        // Already in position — don't open another
        if self.in_position {
            return self.make_result(OrbSignal::Hold, vol_mult, 0.0, "In position".to_string());
        }

        // === BULLISH BREAKOUT ===
        if close > or_high && is_bullish {
            let mut confidence: f64 = 0.50;

            // Volume confirmation
            if vol_mult >= self.config.min_volume_multiplier {
                confidence += 0.15;
            }

            // Strong candle body
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.10;
            }

            // How far above the range — modest extension is ideal
            let extension_pct = (close - or_high) / or_range;
            if extension_pct > 0.0 && extension_pct < 0.5 {
                // Clean breakout, not too extended
                confidence += 0.10;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                let stop = or_high - atr_val * self.config.atr_stop_offset;
                let tp = close + or_range * self.config.range_tp_multiplier;

                self.enter_position(OrbSignal::BuyBreakout, close, stop, tp);
                self.breakout_fired = true;
                self.last_signal = OrbSignal::BuyBreakout;

                return self.make_result(
                    OrbSignal::BuyBreakout,
                    vol_mult,
                    confidence,
                    format!(
                        "ORB bullish breakout: price {:.2} > OR high {:.2}, range {:.2}, vol {:.1}x",
                        close, or_high, or_range, vol_mult
                    ),
                );
            }
        }

        // === BEARISH BREAKOUT ===
        if close < or_low && is_bearish {
            let mut confidence: f64 = 0.50;

            // Volume confirmation
            if vol_mult >= self.config.min_volume_multiplier {
                confidence += 0.15;
            }

            // Strong candle body
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.10;
            }

            // How far below the range
            let extension_pct = (or_low - close) / or_range;
            if extension_pct > 0.0 && extension_pct < 0.5 {
                confidence += 0.10;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                let stop = or_low + atr_val * self.config.atr_stop_offset;
                let tp = close - or_range * self.config.range_tp_multiplier;

                self.enter_position(OrbSignal::SellBreakout, close, stop, tp);
                self.breakout_fired = true;
                self.last_signal = OrbSignal::SellBreakout;

                return self.make_result(
                    OrbSignal::SellBreakout,
                    vol_mult,
                    confidence,
                    format!(
                        "ORB bearish breakout: price {:.2} < OR low {:.2}, range {:.2}, vol {:.1}x",
                        close, or_low, or_range, vol_mult
                    ),
                );
            }
        }

        self.last_signal = OrbSignal::Hold;
        self.make_result(
            OrbSignal::Hold,
            vol_mult,
            0.0,
            format!(
                "No breakout: price {:.2}, OR [{:.2}, {:.2}]",
                close, or_low, or_high
            ),
        )
    }

    /// Update with HLC values (no volume — uses volume=0.0 / fallback).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> OrbResult {
        self.update_ohlcv(close, high, low, close, 0.0)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// ORB is a breakout/momentum strategy. It fires when price escapes a
    /// consolidation range, so it works best at regime transitions.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(
            regime,
            MarketRegime::MeanReverting | MarketRegime::Uncertain
        )
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    ///
    /// Returns `Some(factor)` if the regime is suitable, `None` otherwise.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::MeanReverting => {
                // ORB from a ranging market — breakout likely to run
                Some(confidence.clamp(0.4, 1.0))
            }
            MarketRegime::Uncertain => {
                // May be transitioning — allow with reduced size
                Some(if confidence >= 0.5 { 0.35 } else { 0.20 })
            }
            _ => None,
        }
    }

    // ========================================================================
    // Position management (internal)
    // ========================================================================

    fn enter_position(&mut self, side: OrbSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(&self, price: f64, side: &OrbSignal) -> Option<OrbSignal> {
        let stop = self.stop_loss.unwrap_or(0.0);
        let tp = self.take_profit.unwrap_or(price);

        match side {
            OrbSignal::BuyBreakout => {
                if price >= tp || price <= stop {
                    Some(OrbSignal::SellBreakout)
                } else {
                    None
                }
            }
            OrbSignal::SellBreakout => {
                if price <= tp || price >= stop {
                    Some(OrbSignal::BuyBreakout)
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(
        &self,
        signal: OrbSignal,
        volume_multiplier: f64,
        confidence: f64,
        reason: String,
    ) -> OrbResult {
        let (rh, rl, rs) = if self.range.is_complete
            && self.range.high > f64::NEG_INFINITY
            && self.range.low < f64::INFINITY
        {
            (
                Some(self.range.high),
                Some(self.range.low),
                Some(self.range.range_size()),
            )
        } else {
            (None, None, None)
        };

        OrbResult {
            signal,
            range_high: rh,
            range_low: rl,
            range_size: rs,
            atr: self.last_atr,
            volume_multiplier,
            confidence,
            stop_loss: if signal == OrbSignal::BuyBreakout || signal == OrbSignal::SellBreakout {
                self.stop_loss
            } else {
                None
            },
            take_profit: if signal == OrbSignal::BuyBreakout || signal == OrbSignal::SellBreakout {
                self.take_profit
            } else {
                None
            },
            reason,
        }
    }

    // ========================================================================
    // Full reset
    // ========================================================================

    /// Full reset — clears all state including positions, opening range,
    /// and indicators.
    pub fn reset(&mut self) {
        self.range = OpeningRangeTracker::new(self.config.opening_range_candles);
        self.atr.reset();
        self.volume_analyzer = VolumeAnalyzer::new(self.config.volume_period);
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
        self.breakout_fired = false;
        self.last_atr = None;
        self.last_signal = OrbSignal::Hold;
        self.candle_count = 0;
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Whether the opening range is fully formed.
    pub fn is_range_complete(&self) -> bool {
        self.range.is_complete
    }

    /// Whether a session is currently active.
    pub fn is_session_active(&self) -> bool {
        self.range.session_active
    }

    /// Whether the strategy currently tracks an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// Whether a breakout has already been fired in this session.
    pub fn breakout_fired(&self) -> bool {
        self.breakout_fired
    }

    /// Opening range high (if complete).
    pub fn range_high(&self) -> Option<f64> {
        if self.range.is_complete {
            Some(self.range.high)
        } else {
            None
        }
    }

    /// Opening range low (if complete).
    pub fn range_low(&self) -> Option<f64> {
        if self.range.is_complete {
            Some(self.range.low)
        } else {
            None
        }
    }

    /// Opening range size (if complete).
    pub fn range_size(&self) -> Option<f64> {
        if self.range.is_complete {
            Some(self.range.range_size())
        } else {
            None
        }
    }

    /// Current ATR value (if available).
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// Last signal produced.
    pub fn last_signal(&self) -> OrbSignal {
        self.last_signal
    }

    /// Number of candles processed since creation / last reset.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Entry price of the current position (if any).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Stop loss of the current position (if any).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Take profit of the current position (if any).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// Reference to the strategy configuration.
    pub fn config(&self) -> &OrbConfig {
        &self.config
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use janus_regime::TrendDirection;

    // Helper: warm up ATR with some candles before starting a session
    fn warm_up_atr(strategy: &mut OrbStrategy, base_price: f64, count: usize) {
        for i in 0..count {
            let noise = (i as f64 * 0.3).sin() * 5.0;
            let close = base_price + noise;
            // Feed directly to ATR + volume (not via update_ohlcv, to avoid
            // session logic). Instead we use update_ohlcv with no session.
            strategy.update_ohlcv(
                close - 1.0,
                close + 10.0,
                close - 10.0,
                close,
                1000.0 + i as f64 * 10.0,
            );
        }
    }

    // ── Config tests ────────────────────────────────────────────────────

    #[test]
    fn test_default_config() {
        let config = OrbConfig::default();
        assert_eq!(config.opening_range_candles, 6);
        assert_eq!(config.atr_period, 14);
        assert!((config.atr_stop_offset - 0.5).abs() < f64::EPSILON);
        assert!((config.range_tp_multiplier - 1.5).abs() < f64::EPSILON);
        assert_eq!(config.volume_period, 20);
        assert!(!config.allow_reentry);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = OrbConfig::crypto_aggressive();
        assert!(config.opening_range_candles < OrbConfig::default().opening_range_candles);
        assert!(config.min_confidence <= OrbConfig::default().min_confidence);
        assert!(config.allow_reentry);
    }

    #[test]
    fn test_conservative_config() {
        let config = OrbConfig::conservative();
        assert!(config.opening_range_candles > OrbConfig::default().opening_range_candles);
        assert!(config.min_confidence >= OrbConfig::default().min_confidence);
        assert!(!config.allow_reentry);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = OrbConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: OrbConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(
            deserialized.opening_range_candles,
            config.opening_range_candles
        );
        assert_eq!(deserialized.atr_period, config.atr_period);
    }

    // ── Strategy creation ───────────────────────────────────────────────

    #[test]
    fn test_strategy_creation() {
        let strategy = OrbStrategy::with_defaults();
        assert!(!strategy.is_range_complete());
        assert!(!strategy.is_session_active());
        assert!(!strategy.is_in_position());
        assert!(!strategy.breakout_fired());
        assert_eq!(strategy.last_signal(), OrbSignal::Hold);
        assert_eq!(strategy.candle_count(), 0);
    }

    // ── Session management ──────────────────────────────────────────────

    #[test]
    fn test_start_session() {
        let mut strategy = OrbStrategy::with_defaults();
        assert!(!strategy.is_session_active());
        strategy.start_session();
        assert!(strategy.is_session_active());
        assert!(!strategy.is_range_complete());
    }

    #[test]
    fn test_no_signal_without_session() {
        let mut strategy = OrbStrategy::with_defaults();
        // Feed candles without starting a session
        let result = strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        assert_eq!(result.signal, OrbSignal::Hold);
    }

    // ── Opening range formation ─────────────────────────────────────────

    #[test]
    fn test_opening_range_formation() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 3,
            ..Default::default()
        });

        // Warm up ATR
        warm_up_atr(&mut strategy, 100.0, 20);

        strategy.start_session();

        // First candle
        let r1 = strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        assert_eq!(r1.signal, OrbSignal::Forming);
        assert!(!strategy.is_range_complete());

        // Second candle
        let r2 = strategy.update_ohlcv(102.0, 108.0, 97.0, 104.0, 1000.0);
        assert_eq!(r2.signal, OrbSignal::Forming);
        assert!(!strategy.is_range_complete());

        // Third candle — completes the range
        let r3 = strategy.update_ohlcv(104.0, 106.0, 99.0, 103.0, 1000.0);
        assert_eq!(r3.signal, OrbSignal::Forming);
        assert!(strategy.is_range_complete());

        // Verify range boundaries
        assert_eq!(strategy.range_high(), Some(108.0)); // Max high
        assert_eq!(strategy.range_low(), Some(95.0)); // Min low
        assert!((strategy.range_size().unwrap() - 13.0).abs() < f64::EPSILON);
    }

    // ── Breakout detection ──────────────────────────────────────────────

    #[test]
    fn test_bullish_breakout() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            min_confidence: 0.45,
            min_volume_multiplier: 0.5,
            min_body_ratio: 0.3,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        // Form opening range: high=105, low=95
        strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        strategy.update_ohlcv(102.0, 104.0, 96.0, 103.0, 1000.0);

        assert!(strategy.is_range_complete());

        // Breakout above: bullish candle closing above 105
        let result = strategy.update_ohlcv(104.0, 112.0, 103.0, 110.0, 1500.0);

        assert_eq!(result.signal, OrbSignal::BuyBreakout);
        assert!(result.confidence >= 0.45);
        assert!(result.stop_loss.is_some());
        assert!(result.take_profit.is_some());
        assert!(strategy.breakout_fired());
    }

    #[test]
    fn test_bearish_breakout() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            min_confidence: 0.45,
            min_volume_multiplier: 0.5,
            min_body_ratio: 0.3,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        // Form opening range: high=105, low=95
        strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        strategy.update_ohlcv(102.0, 104.0, 96.0, 100.0, 1000.0);

        // Breakout below: bearish candle closing below 95
        let result = strategy.update_ohlcv(96.0, 97.0, 88.0, 90.0, 1500.0);

        assert_eq!(result.signal, OrbSignal::SellBreakout);
        assert!(result.confidence >= 0.45);
        assert!(strategy.breakout_fired());
    }

    #[test]
    fn test_no_breakout_inside_range() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        // Form opening range
        strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        strategy.update_ohlcv(102.0, 104.0, 96.0, 100.0, 1000.0);

        // Price stays inside range
        let result = strategy.update_ohlcv(100.0, 103.0, 97.0, 101.0, 1000.0);
        assert_eq!(result.signal, OrbSignal::Hold);
        assert!(!strategy.breakout_fired());
    }

    // ── Re-entry control ────────────────────────────────────────────────

    #[test]
    fn test_no_reentry_by_default() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            min_confidence: 0.45,
            min_volume_multiplier: 0.5,
            min_body_ratio: 0.3,
            allow_reentry: false,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        strategy.update_ohlcv(102.0, 104.0, 96.0, 103.0, 1000.0);

        // First breakout fires
        let r1 = strategy.update_ohlcv(104.0, 112.0, 103.0, 110.0, 1500.0);
        assert_eq!(r1.signal, OrbSignal::BuyBreakout);

        // Exit the position manually
        strategy.exit_position();

        // Second breakout attempt — should be blocked
        let r2 = strategy.update_ohlcv(109.0, 115.0, 108.0, 114.0, 2000.0);
        assert_eq!(r2.signal, OrbSignal::Hold);
    }

    #[test]
    fn test_reentry_when_allowed() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            min_confidence: 0.45,
            min_volume_multiplier: 0.5,
            min_body_ratio: 0.3,
            allow_reentry: true,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        strategy.update_ohlcv(102.0, 104.0, 96.0, 103.0, 1000.0);

        // First breakout
        let r1 = strategy.update_ohlcv(104.0, 112.0, 103.0, 110.0, 1500.0);
        assert_eq!(r1.signal, OrbSignal::BuyBreakout);

        // Exit the position manually
        strategy.exit_position();

        // Second breakout — should be allowed
        let r2 = strategy.update_ohlcv(109.0, 115.0, 108.0, 114.0, 2000.0);
        // May or may not fire depending on in_position logic, but won't be
        // blocked by the breakout_fired guard
        assert!(
            r2.signal == OrbSignal::BuyBreakout || r2.signal == OrbSignal::Hold,
            "Re-entry should not be blocked, got {:?}",
            r2.signal
        );
    }

    // ── Session reset ───────────────────────────────────────────────────

    #[test]
    fn test_new_session_resets_range() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        strategy.update_ohlcv(100.0, 105.0, 95.0, 102.0, 1000.0);
        strategy.update_ohlcv(102.0, 104.0, 96.0, 100.0, 1000.0);
        assert!(strategy.is_range_complete());

        // Start a new session
        strategy.start_session();
        assert!(!strategy.is_range_complete());
        assert!(!strategy.breakout_fired());
    }

    // ── Full reset ──────────────────────────────────────────────────────

    #[test]
    fn test_full_reset() {
        let mut strategy = OrbStrategy::with_defaults();
        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        assert!(strategy.candle_count() > 0);

        strategy.reset();
        assert_eq!(strategy.candle_count(), 0);
        assert!(!strategy.is_session_active());
        assert!(!strategy.is_in_position());
    }

    // ── Regime gating ───────────────────────────────────────────────────

    #[test]
    fn test_should_trade_in_mean_reverting() {
        assert!(OrbStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_trade_in_uncertain() {
        assert!(OrbStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_should_not_trade_in_trending() {
        assert!(!OrbStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
        assert!(!OrbStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_not_trade_in_volatile() {
        assert!(!OrbStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_regime_size_factor_mean_reverting() {
        let factor = OrbStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.8);
        assert!(factor.is_some());
        let f = factor.unwrap();
        assert!(
            (0.4..=1.0).contains(&f),
            "Factor {f} should be clamped 0.4–1.0"
        );
    }

    #[test]
    fn test_regime_size_factor_uncertain() {
        let factor = OrbStrategy::regime_size_factor(&MarketRegime::Uncertain, 0.3);
        assert!(factor.is_some());
        let f = factor.unwrap();
        assert!(f > 0.0 && f <= 0.5, "Uncertain factor {f} should be small");
    }

    #[test]
    fn test_regime_size_factor_trending_is_none() {
        let factor =
            OrbStrategy::regime_size_factor(&MarketRegime::Trending(TrendDirection::Bullish), 0.9);
        assert!(factor.is_none());
    }

    // ── Signal display ──────────────────────────────────────────────────

    #[test]
    fn test_signal_display() {
        assert_eq!(format!("{}", OrbSignal::BuyBreakout), "BuyBreakout");
        assert_eq!(format!("{}", OrbSignal::SellBreakout), "SellBreakout");
        assert_eq!(format!("{}", OrbSignal::Forming), "Forming");
        assert_eq!(format!("{}", OrbSignal::Hold), "Hold");
    }

    #[test]
    fn test_signal_serialization() {
        let json = serde_json::to_string(&OrbSignal::BuyBreakout).unwrap();
        let deserialized: OrbSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, OrbSignal::BuyBreakout);
    }

    // ── Result fields ───────────────────────────────────────────────────

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = OrbStrategy::with_defaults();
        let result = strategy.update_ohlcv(100.0, 101.0, 99.0, 100.0, 1000.0);
        assert!(
            !result.reason.is_empty(),
            "Reason should always be populated"
        );
    }

    #[test]
    fn test_result_range_fields_after_completion() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 2,
            ..Default::default()
        });

        warm_up_atr(&mut strategy, 100.0, 20);
        strategy.start_session();

        strategy.update_ohlcv(100.0, 110.0, 90.0, 105.0, 1000.0);
        let result = strategy.update_ohlcv(105.0, 108.0, 92.0, 100.0, 1000.0);

        // Range should now be complete
        assert!(result.range_high.is_some());
        assert!(result.range_low.is_some());
        assert!(result.range_size.is_some());
        assert_eq!(result.range_high.unwrap(), 110.0);
        assert_eq!(result.range_low.unwrap(), 90.0);
        assert!((result.range_size.unwrap() - 20.0).abs() < f64::EPSILON);
    }

    // ── HLC interface ───────────────────────────────────────────────────

    #[test]
    fn test_hlc_interface() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 3,
            ..Default::default()
        });

        strategy.start_session();

        // Should not panic even without volume
        for _ in 0..5 {
            let result = strategy.update_hlc(101.0, 99.0, 100.0);
            assert!(
                result.signal == OrbSignal::Forming
                    || result.signal == OrbSignal::Hold
                    || result.signal == OrbSignal::BuyBreakout
                    || result.signal == OrbSignal::SellBreakout
            );
        }
    }

    // ── Position tracking ───────────────────────────────────────────────

    #[test]
    fn test_not_in_position_initially() {
        let strategy = OrbStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    #[test]
    fn test_position_accessors() {
        let mut strategy = OrbStrategy::with_defaults();
        strategy.enter_position(OrbSignal::BuyBreakout, 100.0, 95.0, 115.0);

        assert!(strategy.is_in_position());
        assert_eq!(strategy.entry_price(), Some(100.0));
        assert_eq!(strategy.stop_loss(), Some(95.0));
        assert_eq!(strategy.take_profit(), Some(115.0));

        strategy.exit_position();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
    }

    // ── Config accessor ─────────────────────────────────────────────────

    #[test]
    fn test_config_accessor() {
        let config = OrbConfig::conservative();
        let strategy = OrbStrategy::new(config.clone());
        assert_eq!(
            strategy.config().opening_range_candles,
            config.opening_range_candles
        );
        assert_eq!(strategy.config().atr_period, config.atr_period);
    }

    // ── Opening range tracker unit tests ────────────────────────────────

    #[test]
    fn test_range_tracker_basic() {
        let mut tracker = OpeningRangeTracker::new(3);
        assert!(!tracker.is_complete);
        assert!(!tracker.session_active);

        tracker.start_session();
        assert!(tracker.session_active);

        tracker.update(105.0, 95.0);
        assert!(!tracker.is_complete);
        assert_eq!(tracker.candles_seen, 1);

        tracker.update(110.0, 98.0);
        tracker.update(108.0, 92.0);
        assert!(tracker.is_complete);
        assert!((tracker.high - 110.0).abs() < f64::EPSILON);
        assert!((tracker.low - 92.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_range_tracker_no_update_after_complete() {
        let mut tracker = OpeningRangeTracker::new(2);
        tracker.start_session();
        tracker.update(105.0, 95.0);
        tracker.update(108.0, 92.0);
        assert!(tracker.is_complete);

        // This should not change the range
        tracker.update(200.0, 50.0);
        assert!((tracker.high - 108.0).abs() < f64::EPSILON);
        assert!((tracker.low - 92.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_range_tracker_no_update_without_session() {
        let mut tracker = OpeningRangeTracker::new(2);
        tracker.update(105.0, 95.0);
        assert_eq!(tracker.candles_seen, 0);
    }

    #[test]
    fn test_range_tracker_range_size() {
        let mut tracker = OpeningRangeTracker::new(2);
        tracker.start_session();
        tracker.update(110.0, 90.0);
        tracker.update(105.0, 95.0);
        assert!((tracker.range_size() - 20.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_range_tracker_reset_on_new_session() {
        let mut tracker = OpeningRangeTracker::new(2);
        tracker.start_session();
        tracker.update(110.0, 90.0);
        tracker.update(105.0, 95.0);
        assert!(tracker.is_complete);

        tracker.start_session();
        assert!(!tracker.is_complete);
        assert_eq!(tracker.candles_seen, 0);
    }

    // ── Volume analyzer unit tests ──────────────────────────────────────

    #[test]
    fn test_volume_analyzer_basic() {
        let mut va = VolumeAnalyzer::new(5);
        let mult = va.update(100.0);
        assert!((mult - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_volume_analyzer_spike() {
        let mut va = VolumeAnalyzer::new(5);
        for _ in 0..5 {
            va.update(100.0);
        }
        let mult = va.update(300.0);
        assert!(mult > 2.5, "Volume multiplier {mult} should detect spike");
    }

    // ── Stress test ─────────────────────────────────────────────────────

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = OrbStrategy::new(OrbConfig::crypto_aggressive());

        warm_up_atr(&mut strategy, 100.0, 20);

        let mut sessions = 0;
        let mut breakouts = 0;

        for session in 0..5 {
            strategy.start_session();
            sessions += 1;

            for i in 0..50 {
                let base = 100.0 + (session as f64) * 10.0;
                let noise = (i as f64 * 0.2).sin() * 8.0;
                let close = base + noise;
                let result = strategy.update_ohlcv(
                    close - 1.0,
                    close + 12.0,
                    close - 12.0,
                    close,
                    1000.0 + (i as f64 * 50.0),
                );
                if result.signal == OrbSignal::BuyBreakout
                    || result.signal == OrbSignal::SellBreakout
                {
                    breakouts += 1;
                }
            }
        }

        println!(
            "Stress test: {} sessions, {} breakouts",
            sessions, breakouts
        );
        assert!(strategy.candle_count() > 200);
    }

    // ── End-to-end test ─────────────────────────────────────────────────

    #[test]
    fn test_end_to_end_session() {
        let mut strategy = OrbStrategy::new(OrbConfig {
            opening_range_candles: 3,
            min_confidence: 0.45,
            min_volume_multiplier: 0.5,
            min_body_ratio: 0.3,
            ..Default::default()
        });

        // Warm up ATR
        for i in 0..20 {
            let p = 100.0 + (i as f64 * 0.5).sin() * 3.0;
            strategy.update_ohlcv(p, p + 2.0, p - 2.0, p, 1000.0);
        }

        // Start session
        strategy.start_session();

        // Form opening range: 3 candles, range [95, 105]
        let r = strategy.update_ohlcv(100.0, 103.0, 97.0, 101.0, 1000.0);
        assert_eq!(r.signal, OrbSignal::Forming);

        let r = strategy.update_ohlcv(101.0, 105.0, 96.0, 103.0, 1000.0);
        assert_eq!(r.signal, OrbSignal::Forming);

        let r = strategy.update_ohlcv(103.0, 104.0, 95.0, 100.0, 1000.0);
        assert_eq!(r.signal, OrbSignal::Forming);
        assert!(strategy.is_range_complete());
        assert_eq!(strategy.range_high(), Some(105.0));
        assert_eq!(strategy.range_low(), Some(95.0));

        // Candle inside range → Hold
        let r = strategy.update_ohlcv(100.0, 104.0, 96.0, 102.0, 1000.0);
        assert_eq!(r.signal, OrbSignal::Hold);

        // Bullish breakout candle
        let r = strategy.update_ohlcv(104.0, 112.0, 103.0, 110.0, 2000.0);
        assert_eq!(r.signal, OrbSignal::BuyBreakout);
        assert!(r.stop_loss.is_some());
        assert!(r.take_profit.is_some());
        assert!(r.confidence >= 0.45);

        // Stop should be below OR high
        assert!(r.stop_loss.unwrap() < 105.0);
        // TP should be above entry
        assert!(r.take_profit.unwrap() > 110.0);
    }
}
