//! # Trend Pullback Strategy
//!
//! Identifies pullbacks within established trends using Fibonacci retracement
//! levels, RSI divergence, and candlestick reversal patterns (pin bars,
//! engulfing candles).
//!
//! ## How It Works
//!
//! 1. **Trend Identification**: EMA 50/200 determines the primary trend
//!    direction. Both EMAs must agree for a valid setup.
//!
//! 2. **Swing Point Tracking**: Maintains rolling swing high/low over recent
//!    candles to define the retracement range.
//!
//! 3. **Fibonacci Zone**: Price must pull back into a configurable Fibonacci
//!    retracement zone (default: 38.2%, 50.0%, 61.8%) of the last swing.
//!
//! 4. **RSI Confirmation**: RSI should be approaching oversold (for longs) or
//!    overbought (for shorts), indicating the pullback is exhausting.
//!
//! 5. **Candlestick Reversal**: The entry candle must show a reversal pattern
//!    — either a pin bar (long wick rejection) or an engulfing pattern.
//!
//! 6. **ATR-Based Stops**: Stop loss below/above the swing low/high, take
//!    profit at the swing high/low extended by an ATR multiple.
//!
//! ## Regime Integration
//!
//! This strategy is designed for trending markets with pullback opportunities:
//!
//! - **Trending(Bullish/Bearish)** → Yes (primary use case)
//! - **Volatile** → Yes with reduced size (deeper pullbacks possible)
//! - **MeanReverting** → No (no clear trend to pull back within)
//! - **Uncertain** → No (wait for clarity)
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/intraday.rs::TrendPullback`, adapted for
//! the JANUS single-asset design, `janus-regime` indicator types, and
//! regime-aware position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::{ATR, EMA, RSI};
use janus_regime::types::TrendDirection;
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal Types
// ============================================================================

/// Signal generated by the Trend Pullback strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrendPullbackSignal {
    /// Enter long — bullish pullback to Fibonacci zone with reversal pattern.
    Buy,
    /// Enter short / exit long — bearish pullback with reversal pattern.
    Sell,
    /// No action.
    Hold,
}

impl std::fmt::Display for TrendPullbackSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TrendPullbackSignal::Buy => write!(f, "BUY"),
            TrendPullbackSignal::Sell => write!(f, "SELL"),
            TrendPullbackSignal::Hold => write!(f, "HOLD"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the Trend Pullback strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrendPullbackConfig {
    /// Short EMA period for trend detection (default: 50).
    pub ema_short_period: usize,

    /// Long EMA period for trend detection (default: 200).
    pub ema_long_period: usize,

    /// RSI period (default: 14).
    pub rsi_period: usize,

    /// RSI oversold threshold — below this in a bullish pullback increases
    /// confidence (default: 30.0).
    pub rsi_oversold: f64,

    /// RSI overbought threshold — above this in a bearish pullback increases
    /// confidence (default: 70.0).
    pub rsi_overbought: f64,

    /// RSI "approaching" offset — RSI within `oversold + offset` (or
    /// `overbought - offset`) counts as "approaching" the extreme (default: 10.0).
    pub rsi_approach_offset: f64,

    /// ATR period for volatility measurement (default: 14).
    pub atr_period: usize,

    /// ATR multiplier for stop-loss extension beyond the swing point (default: 1.0).
    pub atr_stop_multiplier: f64,

    /// ATR multiplier for take-profit extension beyond the swing point (default: 2.0).
    pub atr_tp_multiplier: f64,

    /// Fibonacci retracement levels to check (default: 0.382, 0.500, 0.618).
    pub fib_levels: Vec<f64>,

    /// Tolerance around each Fibonacci level as a fraction of the swing range
    /// (default: 0.02 = 2%).
    pub fib_tolerance: f64,

    /// Number of candles to look back for swing high/low (default: 20).
    pub swing_lookback: usize,

    /// Minimum pin bar wick-to-body ratio (default: 2.0).
    pub pin_bar_wick_ratio: f64,

    /// Minimum confidence score to emit a signal (default: 0.55).
    pub min_confidence: f64,

    /// Minimum number of candles before the strategy is ready (default: 50).
    pub warmup_candles: usize,
}

impl Default for TrendPullbackConfig {
    fn default() -> Self {
        Self {
            ema_short_period: 50,
            ema_long_period: 200,
            rsi_period: 14,
            rsi_oversold: 30.0,
            rsi_overbought: 70.0,
            rsi_approach_offset: 10.0,
            atr_period: 14,
            atr_stop_multiplier: 1.0,
            atr_tp_multiplier: 2.0,
            fib_levels: vec![0.382, 0.500, 0.618],
            fib_tolerance: 0.02,
            swing_lookback: 20,
            pin_bar_wick_ratio: 2.0,
            min_confidence: 0.55,
            warmup_candles: 50,
        }
    }
}

impl TrendPullbackConfig {
    /// Aggressive config for crypto — wider fib tolerance, lower confidence.
    pub fn crypto_aggressive() -> Self {
        Self {
            ema_short_period: 50,
            ema_long_period: 200,
            rsi_approach_offset: 15.0,
            atr_stop_multiplier: 1.2,
            atr_tp_multiplier: 2.5,
            fib_tolerance: 0.03,
            pin_bar_wick_ratio: 1.5,
            min_confidence: 0.50,
            warmup_candles: 40,
            ..Default::default()
        }
    }

    /// Conservative config — tighter fib tolerance, higher confidence.
    pub fn conservative() -> Self {
        Self {
            rsi_approach_offset: 5.0,
            atr_stop_multiplier: 1.5,
            atr_tp_multiplier: 3.0,
            fib_tolerance: 0.015,
            pin_bar_wick_ratio: 2.5,
            min_confidence: 0.65,
            warmup_candles: 60,
            ..Default::default()
        }
    }
}

// ============================================================================
// Detailed Result
// ============================================================================

/// Detailed result from a Trend Pullback strategy update.
#[derive(Debug, Clone)]
pub struct TrendPullbackResult {
    /// The signal produced.
    pub signal: TrendPullbackSignal,
    /// Current short EMA value.
    pub ema_short: Option<f64>,
    /// Current long EMA value.
    pub ema_long: Option<f64>,
    /// Current RSI value.
    pub rsi: Option<f64>,
    /// Current ATR value.
    pub atr: Option<f64>,
    /// Current swing high.
    pub swing_high: Option<f64>,
    /// Current swing low.
    pub swing_low: Option<f64>,
    /// The Fibonacci level that was hit (if any).
    pub fib_level_hit: Option<f64>,
    /// Detected candlestick pattern name (if any).
    pub candle_pattern: Option<String>,
    /// Detected trend direction.
    pub trend: Option<TrendDirection>,
    /// Confidence score (0.0–1.0).
    pub confidence: f64,
    /// Computed stop-loss price.
    pub stop_loss: Option<f64>,
    /// Computed take-profit price.
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// Internal candle representation
// ============================================================================

/// Minimal candle data stored for swing point and pattern detection.
#[derive(Debug, Clone)]
struct CandleData {
    open: f64,
    high: f64,
    low: f64,
    close: f64,
}

#[allow(dead_code)]
impl CandleData {
    fn is_bullish(&self) -> bool {
        self.close > self.open
    }

    fn is_bearish(&self) -> bool {
        self.close < self.open
    }

    fn body_size(&self) -> f64 {
        (self.close - self.open).abs()
    }

    fn range(&self) -> f64 {
        self.high - self.low
    }

    fn upper_wick(&self) -> f64 {
        self.high - self.close.max(self.open)
    }

    fn lower_wick(&self) -> f64 {
        self.close.min(self.open) - self.low
    }

    /// Check if this candle is a pin bar (long wick rejection).
    fn is_pin_bar(&self, wick_ratio: f64) -> bool {
        let body = self.body_size();
        let range = self.range();
        if range <= 0.0 || body <= 0.0 {
            return false;
        }
        // Bullish pin bar: long lower wick
        let bullish_pin = self.lower_wick() >= body * wick_ratio && self.upper_wick() < body;
        // Bearish pin bar: long upper wick
        let bearish_pin = self.upper_wick() >= body * wick_ratio && self.lower_wick() < body;

        bullish_pin || bearish_pin
    }

    /// Check if this candle is a bullish pin bar (hammer).
    fn is_bullish_pin_bar(&self, wick_ratio: f64) -> bool {
        let body = self.body_size();
        if body <= 0.0 {
            return false;
        }
        self.lower_wick() >= body * wick_ratio && self.upper_wick() < body
    }

    /// Check if this candle is a bearish pin bar (shooting star).
    fn is_bearish_pin_bar(&self, wick_ratio: f64) -> bool {
        let body = self.body_size();
        if body <= 0.0 {
            return false;
        }
        self.upper_wick() >= body * wick_ratio && self.lower_wick() < body
    }

    /// Check if this candle engulfs the previous candle.
    fn is_engulfing(&self, prev: &CandleData) -> bool {
        if self.is_bullish() && prev.is_bearish() {
            // Bullish engulfing
            self.close > prev.open && self.open < prev.close
        } else if self.is_bearish() && prev.is_bullish() {
            // Bearish engulfing
            self.close < prev.open && self.open > prev.close
        } else {
            false
        }
    }

    /// Check if this is a bullish engulfing of the previous candle.
    fn is_bullish_engulfing(&self, prev: &CandleData) -> bool {
        self.is_bullish() && prev.is_bearish() && self.close > prev.open && self.open < prev.close
    }

    /// Check if this is a bearish engulfing of the previous candle.
    fn is_bearish_engulfing(&self, prev: &CandleData) -> bool {
        self.is_bearish() && prev.is_bullish() && self.close < prev.open && self.open > prev.close
    }
}

// ============================================================================
// Strategy
// ============================================================================

/// Trend Pullback Strategy
///
/// Identifies Fibonacci retracement entries within established trends,
/// confirmed by RSI and candlestick reversal patterns. Single-asset —
/// instantiate one per symbol.
#[derive(Debug)]
pub struct TrendPullbackStrategy {
    config: TrendPullbackConfig,

    // Indicators
    ema_short: EMA,
    ema_long: EMA,
    rsi: RSI,
    atr: ATR,

    // Candle history for swing points and patterns
    candles: Vec<CandleData>,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<TrendPullbackSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Last computed values (cached)
    last_ema_short: Option<f64>,
    last_ema_long: Option<f64>,
    last_rsi: Option<f64>,
    last_atr: Option<f64>,
    last_signal: TrendPullbackSignal,
    candle_count: usize,

    // HTF trend bias (optional)
    htf_trend: Option<TrendDirection>,
}

impl TrendPullbackStrategy {
    /// Create a new Trend Pullback strategy with the given config.
    pub fn new(config: TrendPullbackConfig) -> Self {
        let ema_short = EMA::new(config.ema_short_period);
        let ema_long = EMA::new(config.ema_long_period);
        let rsi = RSI::new(config.rsi_period);
        let atr = ATR::new(config.atr_period);

        Self {
            ema_short,
            ema_long,
            rsi,
            atr,
            candles: Vec::with_capacity(config.swing_lookback + 5),
            config,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            last_ema_short: None,
            last_ema_long: None,
            last_rsi: None,
            last_atr: None,
            last_signal: TrendPullbackSignal::Hold,
            candle_count: 0,
            htf_trend: None,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(TrendPullbackConfig::default())
    }

    /// Set higher-timeframe trend bias.
    pub fn set_htf_trend(&mut self, trend: TrendDirection) {
        self.htf_trend = Some(trend);
    }

    /// Clear the HTF trend bias.
    pub fn clear_htf_trend(&mut self) {
        self.htf_trend = None;
    }

    /// Update with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> TrendPullbackSignal {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
        .signal
    }

    /// Update with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(
        &mut self,
        candle: &janus_models::Candle,
    ) -> TrendPullbackResult {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
    }

    /// Main update with OHLCV values — returns a detailed result.
    pub fn update_ohlcv(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        _volume: f64,
    ) -> TrendPullbackResult {
        self.candle_count += 1;

        // Update indicators
        self.ema_short.update(close);
        self.ema_long.update(close);
        let rsi_val = self.rsi.update(close);
        self.atr.update(high, low, close);

        self.last_ema_short = self.ema_short.value();
        self.last_ema_long = self.ema_long.value();
        self.last_rsi = rsi_val;
        self.last_atr = self.atr.value();

        // Store candle for pattern detection
        let candle_data = CandleData {
            open,
            high,
            low,
            close,
        };
        self.candles.push(candle_data);
        let max_candles = self.config.swing_lookback + 5;
        if self.candles.len() > max_candles {
            self.candles.remove(0);
        }

        // Not ready yet?
        if self.candle_count < self.config.warmup_candles {
            return self.make_result(
                TrendPullbackSignal::Hold,
                None,
                None,
                0.0,
                "Warming up".to_string(),
            );
        }

        let ema_s = match self.last_ema_short {
            Some(v) => v,
            None => {
                return self.make_result(
                    TrendPullbackSignal::Hold,
                    None,
                    None,
                    0.0,
                    "Short EMA not ready".to_string(),
                );
            }
        };
        let ema_l = match self.last_ema_long {
            Some(v) => v,
            None => {
                return self.make_result(
                    TrendPullbackSignal::Hold,
                    None,
                    None,
                    0.0,
                    "Long EMA not ready".to_string(),
                );
            }
        };

        let atr_val = match self.last_atr {
            Some(a) if a > 0.0 => a,
            _ => {
                return self.make_result(
                    TrendPullbackSignal::Hold,
                    None,
                    None,
                    0.0,
                    "ATR not ready".to_string(),
                );
            }
        };

        // RSI may not be ready yet — that's fine, we'll just skip the RSI bonus
        let rsi_now = self.last_rsi;

        // Determine trend from EMAs
        let trend = if close > ema_l && ema_s > ema_l {
            Some(TrendDirection::Bullish)
        } else if close < ema_l && ema_s < ema_l {
            Some(TrendDirection::Bearish)
        } else {
            None
        };

        // HTF agreement
        let htf = self.htf_trend;

        // Compute swing high/low from candle history
        let (swing_high, swing_low) = self.compute_swing_points();

        // Check for exit if in position
        if self.in_position
            && let Some(ref side) = self.entry_side
        {
            let exit = self.check_exit(close, ema_l, atr_val, side);
            if let Some(exit_signal) = exit {
                self.exit_position();
                return self.make_result(
                    exit_signal,
                    None,
                    None,
                    0.8,
                    format!("Pullback exit: price {:.2} (EMA_L={:.2})", close, ema_l),
                );
            }
        }

        // Already in position — don't open another
        if self.in_position {
            return self.make_result(
                TrendPullbackSignal::Hold,
                None,
                None,
                0.0,
                "In position".to_string(),
            );
        }

        // Need at least 2 candles for pattern detection
        if self.candles.len() < 2 {
            return self.make_result(
                TrendPullbackSignal::Hold,
                None,
                None,
                0.0,
                "Need more candles for pattern detection".to_string(),
            );
        }

        let current = &self.candles[self.candles.len() - 1];
        let prev = &self.candles[self.candles.len() - 2];

        // Need a valid swing range
        if swing_high <= swing_low || (swing_high - swing_low) < atr_val * 0.5 {
            return self.make_result(
                TrendPullbackSignal::Hold,
                None,
                None,
                0.0,
                format!(
                    "Swing range too narrow: high {:.2} low {:.2}",
                    swing_high, swing_low
                ),
            );
        }

        // === BULLISH PULLBACK ===
        if trend == Some(TrendDirection::Bullish) {
            // Check HTF agreement (allow if htf not set or bullish)
            let htf_ok = htf.is_none() || htf == Some(TrendDirection::Bullish);
            if !htf_ok {
                return self.make_result(
                    TrendPullbackSignal::Hold,
                    None,
                    None,
                    0.0,
                    "HTF trend disagrees with bullish pullback".to_string(),
                );
            }

            // Check if price is in a Fibonacci zone
            if let Some(fib_level) = self.check_fib_zone(close, swing_high, swing_low) {
                // RSI confirmation: approaching oversold
                let rsi_bullish = rsi_now
                    .map(|r| r < self.config.rsi_oversold + self.config.rsi_approach_offset)
                    .unwrap_or(false);

                // Candlestick reversal pattern
                let is_pin = current.is_bullish()
                    && current.is_bullish_pin_bar(self.config.pin_bar_wick_ratio);
                let is_engulf = current.is_bullish_engulfing(prev);
                let candle_signal = current.is_bullish() && (is_pin || is_engulf);

                if rsi_bullish && candle_signal {
                    let stop = swing_low - atr_val * self.config.atr_stop_multiplier;
                    let tp = swing_high + atr_val * self.config.atr_tp_multiplier;

                    let mut confidence = 0.40;

                    // Deeper pullback = more confidence (closer to 0.618 is better)
                    confidence += (1.0 - fib_level) * 0.20;

                    // RSI fully oversold
                    if let Some(r) = rsi_now
                        && r < self.config.rsi_oversold
                    {
                        confidence += 0.15;
                    }

                    // Engulfing is stronger than pin bar
                    if is_engulf {
                        confidence += 0.10;
                    } else if is_pin {
                        confidence += 0.05;
                    }

                    // HTF agreement
                    if htf == Some(TrendDirection::Bullish) {
                        confidence += 0.10;
                    }

                    confidence = confidence.min(1.0);

                    let pattern_name = if is_engulf { "engulfing" } else { "pin bar" };

                    if confidence >= self.config.min_confidence {
                        self.enter_position(TrendPullbackSignal::Buy, close, stop, tp);
                        self.last_signal = TrendPullbackSignal::Buy;

                        return self.make_result(
                            TrendPullbackSignal::Buy,
                            Some(fib_level),
                            Some(pattern_name.to_string()),
                            confidence,
                            format!(
                                "Bullish pullback to {:.1}% Fib, RSI {:.1}, {} pattern, swing [{:.2}, {:.2}]",
                                fib_level * 100.0,
                                rsi_now.unwrap_or(0.0),
                                pattern_name,
                                swing_low,
                                swing_high,
                            ),
                        );
                    }
                }
            }
        }

        // === BEARISH PULLBACK ===
        if trend == Some(TrendDirection::Bearish) {
            let htf_ok = htf.is_none() || htf == Some(TrendDirection::Bearish);
            if !htf_ok {
                return self.make_result(
                    TrendPullbackSignal::Hold,
                    None,
                    None,
                    0.0,
                    "HTF trend disagrees with bearish pullback".to_string(),
                );
            }

            // For bearish pullback, price rallies UP into the fib zone
            // (we invert: measure retracement from low to high)
            if let Some(fib_level) = self.check_fib_zone_inverted(close, swing_high, swing_low) {
                let rsi_bearish = rsi_now
                    .map(|r| r > self.config.rsi_overbought - self.config.rsi_approach_offset)
                    .unwrap_or(false);

                let is_pin = current.is_bearish()
                    && current.is_bearish_pin_bar(self.config.pin_bar_wick_ratio);
                let is_engulf = current.is_bearish_engulfing(prev);
                let candle_signal = current.is_bearish() && (is_pin || is_engulf);

                if rsi_bearish && candle_signal {
                    let stop = swing_high + atr_val * self.config.atr_stop_multiplier;
                    let tp = swing_low - atr_val * self.config.atr_tp_multiplier;

                    let mut confidence = 0.40;

                    confidence += fib_level * 0.20;

                    if let Some(r) = rsi_now
                        && r > self.config.rsi_overbought
                    {
                        confidence += 0.15;
                    }

                    if is_engulf {
                        confidence += 0.10;
                    } else if is_pin {
                        confidence += 0.05;
                    }

                    if htf == Some(TrendDirection::Bearish) {
                        confidence += 0.10;
                    }

                    confidence = confidence.min(1.0);

                    let pattern_name = if is_engulf { "engulfing" } else { "pin bar" };

                    if confidence >= self.config.min_confidence {
                        self.enter_position(TrendPullbackSignal::Sell, close, stop, tp);
                        self.last_signal = TrendPullbackSignal::Sell;

                        return self.make_result(
                            TrendPullbackSignal::Sell,
                            Some(fib_level),
                            Some(pattern_name.to_string()),
                            confidence,
                            format!(
                                "Bearish pullback to {:.1}% Fib, RSI {:.1}, {} pattern, swing [{:.2}, {:.2}]",
                                fib_level * 100.0,
                                rsi_now.unwrap_or(0.0),
                                pattern_name,
                                swing_low,
                                swing_high,
                            ),
                        );
                    }
                }
            }
        }

        self.last_signal = TrendPullbackSignal::Hold;
        self.make_result(
            TrendPullbackSignal::Hold,
            None,
            None,
            0.0,
            format!(
                "No signal: price {:.2}, trend {:?}, swing [{:.2}, {:.2}], RSI {:.1}",
                close,
                trend,
                swing_low,
                swing_high,
                rsi_now.unwrap_or(0.0),
            ),
        )
    }

    /// Update with HLC values (no volume).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> TrendPullbackResult {
        self.update_ohlcv(close, high, low, close, 0.0)
    }

    // ========================================================================
    // Fibonacci helpers
    // ========================================================================

    /// Calculate a Fibonacci retracement level.
    /// For a bullish swing (low → high), fib level 0.382 means price has
    /// retraced 38.2% from the high back toward the low.
    fn fib_price(high: f64, low: f64, level: f64) -> f64 {
        high - (high - low) * level
    }

    /// For a bearish swing (high → low), inverted fib.
    fn fib_price_inverted(high: f64, low: f64, level: f64) -> f64 {
        low + (high - low) * level
    }

    /// Check if price is in any of the configured Fibonacci zones
    /// (bullish retracement: price pulling back from high toward low).
    fn check_fib_zone(&self, price: f64, high: f64, low: f64) -> Option<f64> {
        let swing_range = high - low;
        if swing_range <= 0.0 {
            return None;
        }
        let tolerance = swing_range * self.config.fib_tolerance;

        for &level in &self.config.fib_levels {
            let fib_price = Self::fib_price(high, low, level);
            if (price - fib_price).abs() <= tolerance {
                return Some(level);
            }
        }
        None
    }

    /// Check if price is in any Fibonacci zone for bearish retracement
    /// (price rallying from low back toward high).
    fn check_fib_zone_inverted(&self, price: f64, high: f64, low: f64) -> Option<f64> {
        let swing_range = high - low;
        if swing_range <= 0.0 {
            return None;
        }
        let tolerance = swing_range * self.config.fib_tolerance;

        for &level in &self.config.fib_levels {
            let fib_price = Self::fib_price_inverted(high, low, level);
            if (price - fib_price).abs() <= tolerance {
                return Some(level);
            }
        }
        None
    }

    // ========================================================================
    // Swing point computation
    // ========================================================================

    /// Compute the swing high and swing low from the recent candle history.
    fn compute_swing_points(&self) -> (f64, f64) {
        let lookback = self.config.swing_lookback.min(self.candles.len());
        if lookback == 0 {
            return (0.0, f64::MAX);
        }

        let start = self.candles.len() - lookback;
        let mut high = f64::MIN;
        let mut low = f64::MAX;

        for candle in &self.candles[start..] {
            if candle.high > high {
                high = candle.high;
            }
            if candle.low < low {
                low = candle.low;
            }
        }

        (high, low)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// Trend Pullback needs a clear trend to pull back within.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(regime, MarketRegime::Trending(_) | MarketRegime::Volatile)
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::Trending(_) => {
                // Primary regime — full confidence scaling
                Some(confidence.clamp(0.4, 1.0))
            }
            MarketRegime::Volatile => {
                // Deeper pullbacks possible but riskier
                Some(if confidence >= 0.6 { 0.35 } else { 0.20 })
            }
            _ => None,
        }
    }

    // ========================================================================
    // Position management (internal)
    // ========================================================================

    fn enter_position(&mut self, side: TrendPullbackSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(
        &self,
        close: f64,
        ema_long: f64,
        _atr: f64,
        side: &TrendPullbackSignal,
    ) -> Option<TrendPullbackSignal> {
        match side {
            TrendPullbackSignal::Buy => {
                // Exit long if price closes below long EMA (trend break)
                if close < ema_long {
                    return Some(TrendPullbackSignal::Sell);
                }
                // Stop loss
                if let Some(stop) = self.stop_loss
                    && close <= stop
                {
                    return Some(TrendPullbackSignal::Sell);
                }
                // Take profit
                if let Some(tp) = self.take_profit
                    && close >= tp
                {
                    return Some(TrendPullbackSignal::Sell);
                }
                None
            }
            TrendPullbackSignal::Sell => {
                // Exit short if price closes above long EMA
                if close > ema_long {
                    return Some(TrendPullbackSignal::Buy);
                }
                if let Some(stop) = self.stop_loss
                    && close >= stop
                {
                    return Some(TrendPullbackSignal::Buy);
                }
                if let Some(tp) = self.take_profit
                    && close <= tp
                {
                    return Some(TrendPullbackSignal::Buy);
                }
                None
            }
            TrendPullbackSignal::Hold => None,
        }
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(
        &self,
        signal: TrendPullbackSignal,
        fib_level_hit: Option<f64>,
        candle_pattern: Option<String>,
        confidence: f64,
        reason: String,
    ) -> TrendPullbackResult {
        let (swing_high, swing_low) = self.compute_swing_points();
        let trend = match (self.last_ema_short, self.last_ema_long) {
            (Some(s), Some(l)) if s > l => Some(TrendDirection::Bullish),
            (Some(s), Some(l)) if s < l => Some(TrendDirection::Bearish),
            _ => None,
        };

        TrendPullbackResult {
            signal,
            ema_short: self.last_ema_short,
            ema_long: self.last_ema_long,
            rsi: self.last_rsi,
            atr: self.last_atr,
            swing_high: if swing_high > f64::MIN {
                Some(swing_high)
            } else {
                None
            },
            swing_low: if swing_low < f64::MAX {
                Some(swing_low)
            } else {
                None
            },
            fib_level_hit,
            candle_pattern,
            trend,
            confidence,
            stop_loss: if matches!(signal, TrendPullbackSignal::Buy | TrendPullbackSignal::Sell) {
                self.stop_loss
            } else {
                None
            },
            take_profit: if matches!(signal, TrendPullbackSignal::Buy | TrendPullbackSignal::Sell) {
                self.take_profit
            } else {
                None
            },
            reason,
        }
    }

    // ========================================================================
    // Reset
    // ========================================================================

    /// Full reset — clears all indicator and position state.
    pub fn reset(&mut self) {
        self.ema_short = EMA::new(self.config.ema_short_period);
        self.ema_long = EMA::new(self.config.ema_long_period);
        self.rsi = RSI::new(self.config.rsi_period);
        self.atr = ATR::new(self.config.atr_period);
        self.candles.clear();
        self.exit_position();
        self.last_ema_short = None;
        self.last_ema_long = None;
        self.last_rsi = None;
        self.last_atr = None;
        self.last_signal = TrendPullbackSignal::Hold;
        self.candle_count = 0;
        self.htf_trend = None;
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Whether the strategy has enough data to produce signals.
    pub fn is_ready(&self) -> bool {
        self.candle_count >= self.config.warmup_candles
            && self.last_ema_short.is_some()
            && self.last_ema_long.is_some()
            && self.last_atr.is_some()
    }

    /// Whether the strategy currently has an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// The last short EMA value.
    pub fn last_ema_short(&self) -> Option<f64> {
        self.last_ema_short
    }

    /// The last long EMA value.
    pub fn last_ema_long(&self) -> Option<f64> {
        self.last_ema_long
    }

    /// The last RSI value.
    pub fn last_rsi(&self) -> Option<f64> {
        self.last_rsi
    }

    /// The last ATR value.
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// The last signal produced.
    pub fn last_signal(&self) -> TrendPullbackSignal {
        self.last_signal
    }

    /// Total candles processed.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Current entry price (if in position).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Current stop loss (if in position).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Current take profit (if in position).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// Strategy configuration.
    pub fn config(&self) -> &TrendPullbackConfig {
        &self.config
    }

    /// Current HTF trend bias (if set).
    pub fn htf_trend(&self) -> Option<TrendDirection> {
        self.htf_trend
    }

    /// Current swing high/low from candle history.
    pub fn swing_points(&self) -> (f64, f64) {
        self.compute_swing_points()
    }

    /// Detected trend direction from EMAs.
    pub fn detected_trend(&self) -> Option<TrendDirection> {
        match (self.last_ema_short, self.last_ema_long) {
            (Some(s), Some(l)) if s > l => Some(TrendDirection::Bullish),
            (Some(s), Some(l)) if s < l => Some(TrendDirection::Bearish),
            _ => None,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Feed candles to warm up the strategy with a given trend direction.
    fn warm_up_trend(
        strategy: &mut TrendPullbackStrategy,
        base_price: f64,
        count: usize,
        step: f64,
    ) {
        for i in 0..count {
            let price = base_price + (i as f64) * step;
            strategy.update_ohlcv(price - 5.0, price + 20.0, price - 20.0, price, 1000.0);
        }
    }

    // ── Config tests ─────────────────────────────────────────────────────

    #[test]
    fn test_default_config() {
        let config = TrendPullbackConfig::default();
        assert_eq!(config.ema_short_period, 50);
        assert_eq!(config.ema_long_period, 200);
        assert_eq!(config.rsi_period, 14);
        assert!((config.rsi_oversold - 30.0).abs() < 1e-10);
        assert!((config.rsi_overbought - 70.0).abs() < 1e-10);
        assert_eq!(config.fib_levels.len(), 3);
        assert!((config.fib_levels[0] - 0.382).abs() < 1e-10);
        assert!((config.fib_levels[1] - 0.500).abs() < 1e-10);
        assert!((config.fib_levels[2] - 0.618).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 50);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = TrendPullbackConfig::crypto_aggressive();
        assert!((config.atr_stop_multiplier - 1.2).abs() < 1e-10);
        assert!((config.min_confidence - 0.50).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 40);
    }

    #[test]
    fn test_conservative_config() {
        let config = TrendPullbackConfig::conservative();
        assert!((config.atr_stop_multiplier - 1.5).abs() < 1e-10);
        assert!((config.min_confidence - 0.65).abs() < 1e-10);
        assert_eq!(config.warmup_candles, 60);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = TrendPullbackConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: TrendPullbackConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.ema_short_period, config.ema_short_period);
        assert_eq!(deserialized.ema_long_period, config.ema_long_period);
        assert_eq!(deserialized.fib_levels.len(), config.fib_levels.len());
    }

    // ── Strategy creation tests ──────────────────────────────────────────

    #[test]
    fn test_strategy_creation() {
        let strategy = TrendPullbackStrategy::with_defaults();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert_eq!(strategy.last_signal(), TrendPullbackSignal::Hold);
    }

    #[test]
    fn test_warmup_hold() {
        let mut strategy = TrendPullbackStrategy::with_defaults();
        for i in 0..10 {
            let result = strategy.update_ohlcv(
                100.0 + i as f64,
                110.0 + i as f64,
                90.0 + i as f64,
                100.0 + i as f64,
                1000.0,
            );
            assert_eq!(result.signal, TrendPullbackSignal::Hold);
        }
        assert!(!strategy.is_ready());
    }

    #[test]
    fn test_becomes_ready_after_warmup() {
        let mut strategy = TrendPullbackStrategy::new(TrendPullbackConfig {
            warmup_candles: 50,
            ..Default::default()
        });
        warm_up_trend(&mut strategy, 50000.0, 210, 10.0);
        assert!(strategy.is_ready());
    }

    // ── Fibonacci tests ──────────────────────────────────────────────────

    #[test]
    fn test_fib_price_calculation() {
        let high = 100.0;
        let low = 80.0;

        // 38.2% retracement from high
        let fib_382 = TrendPullbackStrategy::fib_price(high, low, 0.382);
        assert!((fib_382 - 92.36).abs() < 0.01);

        // 50% retracement
        let fib_50 = TrendPullbackStrategy::fib_price(high, low, 0.500);
        assert!((fib_50 - 90.0).abs() < 0.01);

        // 61.8% retracement
        let fib_618 = TrendPullbackStrategy::fib_price(high, low, 0.618);
        assert!((fib_618 - 87.64).abs() < 0.01);
    }

    #[test]
    fn test_fib_price_inverted() {
        let high = 100.0;
        let low = 80.0;

        // 38.2% retracement from low (for bearish pullback)
        let fib_382 = TrendPullbackStrategy::fib_price_inverted(high, low, 0.382);
        assert!((fib_382 - 87.64).abs() < 0.01);
    }

    #[test]
    fn test_check_fib_zone() {
        let strategy = TrendPullbackStrategy::with_defaults();
        // Default tolerance = 0.02, swing range = 20
        // Tolerance = 20 * 0.02 = 0.4

        // 50% retracement of 80..100 = 90.0
        let result = strategy.check_fib_zone(90.0, 100.0, 80.0);
        assert!(result.is_some());
        assert!((result.unwrap() - 0.500).abs() < 1e-10);

        // Price not near any fib level
        let result = strategy.check_fib_zone(95.0, 100.0, 80.0);
        assert!(result.is_none());
    }

    // ── Candle pattern tests ─────────────────────────────────────────────

    #[test]
    fn test_candle_data_bullish() {
        let candle = CandleData {
            open: 100.0,
            high: 110.0,
            low: 95.0,
            close: 108.0,
        };
        assert!(candle.is_bullish());
        assert!(!candle.is_bearish());
        assert!((candle.body_size() - 8.0).abs() < 1e-10);
        assert!((candle.range() - 15.0).abs() < 1e-10);
    }

    #[test]
    fn test_pin_bar_detection() {
        // Bullish pin bar: long lower wick
        let candle = CandleData {
            open: 100.0,
            high: 101.0,
            low: 90.0,
            close: 101.0,
        };
        // body = 1, lower_wick = 10, upper_wick = 0
        assert!(candle.is_pin_bar(2.0));
        assert!(candle.is_bullish_pin_bar(2.0));
        assert!(!candle.is_bearish_pin_bar(2.0));
    }

    #[test]
    fn test_bearish_pin_bar() {
        let candle = CandleData {
            open: 100.0,
            high: 110.0,
            low: 98.5,
            close: 99.0,
        };
        // body = |100 - 99| = 1.0, upper_wick = 110 - 100 = 10, lower_wick = 99 - 99.5 = 0 (min(100,99)=99, 99-99.5<0 → 0 via structure)
        // Actually: close=99, open=100 → bearish candle
        // upper_wick = high - max(open, close) = 110 - 100 = 10
        // lower_wick = min(open, close) - low = 99.0 - 99.5 → but low can't be > close, let's fix:
        // With open=100, high=110, low=98.5, close=99:
        // body = 1.0, upper_wick = 10, lower_wick = 99 - 98.5 = 0.5 < 1.0 ✓
        // upper_wick(10) >= body(1)*wick_ratio(2) = 2 ✓
        assert!(candle.is_bearish_pin_bar(2.0));
    }

    #[test]
    fn test_engulfing_pattern() {
        let prev = CandleData {
            open: 105.0,
            high: 106.0,
            low: 100.0,
            close: 101.0,
        }; // bearish
        let current = CandleData {
            open: 100.0,
            high: 107.0,
            low: 99.0,
            close: 106.0,
        }; // bullish
        assert!(current.is_engulfing(&prev));
        assert!(current.is_bullish_engulfing(&prev));
        assert!(!current.is_bearish_engulfing(&prev));
    }

    // ── Regime gating tests ──────────────────────────────────────────────

    #[test]
    fn test_should_trade_in_trending_bullish() {
        assert!(TrendPullbackStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
    }

    #[test]
    fn test_should_trade_in_trending_bearish() {
        assert!(TrendPullbackStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_trade_in_volatile() {
        assert!(TrendPullbackStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_should_not_trade_in_mean_reverting() {
        assert!(!TrendPullbackStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_not_trade_in_uncertain() {
        assert!(!TrendPullbackStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_regime_size_factor_trending() {
        let factor = TrendPullbackStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.8,
        );
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.8).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_volatile() {
        let factor = TrendPullbackStrategy::regime_size_factor(&MarketRegime::Volatile, 0.7);
        assert!(factor.is_some());
        assert!((factor.unwrap() - 0.35).abs() < 1e-10);
    }

    #[test]
    fn test_regime_size_factor_mean_reverting_is_none() {
        let factor = TrendPullbackStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.8);
        assert!(factor.is_none());
    }

    // ── HTF trend tests ──────────────────────────────────────────────────

    #[test]
    fn test_htf_trend_set_clear() {
        let mut strategy = TrendPullbackStrategy::with_defaults();
        assert!(strategy.htf_trend().is_none());

        strategy.set_htf_trend(TrendDirection::Bullish);
        assert_eq!(strategy.htf_trend(), Some(TrendDirection::Bullish));

        strategy.clear_htf_trend();
        assert!(strategy.htf_trend().is_none());
    }

    // ── Reset tests ──────────────────────────────────────────────────────

    #[test]
    fn test_full_reset() {
        let mut strategy = TrendPullbackStrategy::new(TrendPullbackConfig {
            warmup_candles: 50,
            ..Default::default()
        });
        warm_up_trend(&mut strategy, 50000.0, 210, 10.0);
        assert!(strategy.is_ready());

        strategy.reset();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.candle_count(), 0);
        assert!(strategy.last_ema_short().is_none());
        assert!(strategy.last_ema_long().is_none());
        assert!(strategy.last_rsi().is_none());
    }

    // ── Position tracking tests ──────────────────────────────────────────

    #[test]
    fn test_not_in_position_initially() {
        let strategy = TrendPullbackStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    #[test]
    fn test_internal_position_tracking() {
        let mut strategy = TrendPullbackStrategy::with_defaults();
        strategy.enter_position(TrendPullbackSignal::Buy, 50000.0, 49000.0, 52000.0);
        assert!(strategy.is_in_position());
        assert_eq!(strategy.entry_price(), Some(50000.0));
        assert_eq!(strategy.stop_loss(), Some(49000.0));
        assert_eq!(strategy.take_profit(), Some(52000.0));

        strategy.exit_position();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
    }

    // ── Signal display tests ─────────────────────────────────────────────

    #[test]
    fn test_signal_display() {
        assert_eq!(format!("{}", TrendPullbackSignal::Buy), "BUY");
        assert_eq!(format!("{}", TrendPullbackSignal::Sell), "SELL");
        assert_eq!(format!("{}", TrendPullbackSignal::Hold), "HOLD");
    }

    #[test]
    fn test_signal_serialization() {
        let signal = TrendPullbackSignal::Buy;
        let json = serde_json::to_string(&signal).unwrap();
        let deserialized: TrendPullbackSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, signal);
    }

    // ── Swing point tests ────────────────────────────────────────────────

    #[test]
    fn test_swing_points_computation() {
        let mut strategy = TrendPullbackStrategy::with_defaults();

        // Feed some candles with known high/low
        for i in 0..10 {
            let price = 100.0 + i as f64;
            strategy.update_ohlcv(price, price + 5.0, price - 5.0, price, 100.0);
        }

        let (high, low) = strategy.swing_points();
        // Last candle: price=109, high=114, low=104
        // First candle: price=100, low=95
        assert!((high - 114.0).abs() < 1e-10);
        assert!((low - 95.0).abs() < 1e-10);
    }

    // ── Accessor tests ───────────────────────────────────────────────────

    #[test]
    fn test_config_accessor() {
        let strategy = TrendPullbackStrategy::with_defaults();
        assert_eq!(strategy.config().ema_short_period, 50);
        assert_eq!(strategy.config().ema_long_period, 200);
    }

    #[test]
    fn test_detected_trend_none_initially() {
        let strategy = TrendPullbackStrategy::with_defaults();
        assert!(strategy.detected_trend().is_none());
    }

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = TrendPullbackStrategy::with_defaults();
        let result = strategy.update_ohlcv(50000.0, 50010.0, 49990.0, 50000.0, 1000.0);
        assert!(!result.reason.is_empty());
    }

    // ── HLC interface test ───────────────────────────────────────────────

    #[test]
    fn test_hlc_interface() {
        let mut strategy = TrendPullbackStrategy::new(TrendPullbackConfig {
            warmup_candles: 50,
            ..Default::default()
        });
        for i in 0..210 {
            let price = 50000.0 + i as f64 * 10.0;
            strategy.update_hlc(price + 10.0, price - 10.0, price);
        }
        assert!(strategy.is_ready());
        assert!(strategy.last_atr().is_some());
    }

    // ── Stress test ──────────────────────────────────────────────────────

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = TrendPullbackStrategy::new(TrendPullbackConfig::crypto_aggressive());
        let mut price = 50000.0;
        for i in 0..2000 {
            let direction = if (i / 100) % 2 == 0 { 1.0 } else { -1.0 };
            price += direction * 15.0 + (i as f64 * 0.1).sin() * 30.0;
            let high = price + 25.0;
            let low = price - 25.0;
            let open = price - direction * 3.0;
            let _ = strategy.update_ohlcv(open, high, low, price, 1000.0);
        }
        assert_eq!(strategy.candle_count(), 2000);
    }
}
