//! # VWAP Scalper Strategy
//!
//! Mean reversion scalping around the Volume-Weighted Average Price (VWAP)
//! with standard deviation bands. Enters long when price touches the lower
//! VWAP band with a bullish candle, short when it touches the upper band
//! with a bearish candle. Targets the VWAP (mean) for exits.
//!
//! ## How It Works
//!
//! 1. **VWAP Calculation**: Tracks cumulative typical-price × volume and
//!    cumulative volume to compute the session VWAP. Standard deviation
//!    bands are derived from the volume-weighted squared deviations.
//!
//! 2. **Band Touch Entry**: When price closes at or beyond a VWAP band,
//!    a mean-reversion entry is signaled. The assumption is that price
//!    will revert to the VWAP mean.
//!
//! 3. **Candle Confirmation**: Bullish candles at the lower band, bearish
//!    candles at the upper band. Pin-bar / hammer patterns add confidence.
//!
//! 4. **ATR-Based Stops**: Stop loss placed at an ATR multiple beyond the
//!    entry. Take profit targets the VWAP (the mean).
//!
//! 5. **Volume Spike Detection**: A rolling volume analyzer detects unusual
//!    volume, which boosts signal confidence.
//!
//! ## Regime Integration
//!
//! VWAP scalping is a mean-reversion strategy and works best when the market
//! is ranging. Use `should_trade_in_regime()` to gate activation:
//!
//! - **MeanReverting** → Yes (primary operating regime)
//! - **Uncertain** → Yes with reduced size (may be ranging)
//! - **Trending** → No (VWAP will lag badly in trends)
//! - **Volatile** → No (bands widen too much, stops get hit)
//!
//! ## Origin
//!
//! Ported from Kraken's `strategy/scalping.rs::VwapScalper`, adapted for the
//! JANUS single-asset design, `janus-regime` indicator types, and regime-aware
//! position sizing.

use janus_regime::MarketRegime;
use janus_regime::indicators::ATR;
use serde::{Deserialize, Serialize};

// ============================================================================
// Signal
// ============================================================================

/// Signal generated by the VWAP Scalper strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum VwapSignal {
    /// Enter long — price at/below lower VWAP band with bullish confirmation.
    Buy,
    /// Enter short / exit long — price at/above upper VWAP band with bearish confirmation.
    Sell,
    /// No action.
    Hold,
}

impl std::fmt::Display for VwapSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            VwapSignal::Buy => write!(f, "BUY"),
            VwapSignal::Sell => write!(f, "SELL"),
            VwapSignal::Hold => write!(f, "HOLD"),
        }
    }
}

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the VWAP Scalper strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VwapScalperConfig {
    /// VWAP standard-deviation multiplier for band width (default: 2.0).
    /// Higher values mean wider bands → fewer but higher-quality signals.
    pub vwap_std_dev: f64,

    /// ATR period for stop-loss / volatility measurement (default: 14).
    pub atr_period: usize,

    /// ATR multiplier for stop-loss distance (default: 1.5).
    pub atr_stop_multiplier: f64,

    /// Rolling volume lookback period for spike detection (default: 20).
    pub volume_period: usize,

    /// Minimum volume multiplier (vs rolling average) to boost confidence
    /// (default: 1.5). A candle with volume ≥ this × average gets +0.10
    /// confidence.
    pub min_volume_multiplier: f64,

    /// Minimum confidence score to emit a signal (default: 0.55).
    pub min_confidence: f64,

    /// Minimum candle body ratio (body / range) to count as "strong" candle
    /// (default: 0.5).
    pub min_body_ratio: f64,

    /// Minimum number of candles before the strategy is considered ready
    /// (default: 20). Ensures VWAP has enough data.
    pub warmup_candles: usize,
}

impl Default for VwapScalperConfig {
    fn default() -> Self {
        Self {
            vwap_std_dev: 2.0,
            atr_period: 14,
            atr_stop_multiplier: 1.5,
            volume_period: 20,
            min_volume_multiplier: 1.5,
            min_confidence: 0.55,
            min_body_ratio: 0.5,
            warmup_candles: 20,
        }
    }
}

impl VwapScalperConfig {
    /// Aggressive config for crypto — tighter bands, lower confidence threshold.
    pub fn crypto_aggressive() -> Self {
        Self {
            vwap_std_dev: 1.5,
            atr_stop_multiplier: 1.2,
            min_confidence: 0.50,
            min_body_ratio: 0.45,
            warmup_candles: 15,
            ..Default::default()
        }
    }

    /// Conservative config — wider bands, higher confidence required.
    pub fn conservative() -> Self {
        Self {
            vwap_std_dev: 2.5,
            atr_stop_multiplier: 2.0,
            min_confidence: 0.65,
            min_body_ratio: 0.55,
            warmup_candles: 30,
            ..Default::default()
        }
    }
}

// ============================================================================
// Detailed Result
// ============================================================================

/// Detailed result from a VWAP Scalper strategy update.
#[derive(Debug, Clone)]
pub struct VwapScalperResult {
    /// The signal produced.
    pub signal: VwapSignal,
    /// Current VWAP value (if available).
    pub vwap: Option<f64>,
    /// Upper VWAP band (vwap + std_dev * multiplier).
    pub upper_band: Option<f64>,
    /// Lower VWAP band (vwap - std_dev * multiplier).
    pub lower_band: Option<f64>,
    /// Current ATR value (if available).
    pub atr: Option<f64>,
    /// Volume multiplier relative to rolling average.
    pub volume_multiplier: f64,
    /// Confidence score (0.0–1.0).
    pub confidence: f64,
    /// Computed stop-loss price (only set on buy/sell signals).
    pub stop_loss: Option<f64>,
    /// Computed take-profit price (only set on buy/sell signals).
    pub take_profit: Option<f64>,
    /// Human-readable reason string.
    pub reason: String,
}

// ============================================================================
// VWAP Calculator (internal)
// ============================================================================

/// Calculates the Volume-Weighted Average Price and its standard deviation.
///
/// Resets at the start of each session. For 24/7 crypto markets, call
/// `reset()` at whatever session boundary you define (e.g. 00:00 UTC).
#[derive(Debug)]
struct VwapCalculator {
    cumulative_tp_volume: f64,
    cumulative_volume: f64,
    squared_deviation_sum: f64,
    candle_count: usize,
}

impl VwapCalculator {
    fn new() -> Self {
        Self {
            cumulative_tp_volume: 0.0,
            cumulative_volume: 0.0,
            squared_deviation_sum: 0.0,
            candle_count: 0,
        }
    }

    /// Update with a new candle. Returns `(vwap, std_dev)`.
    ///
    /// If volume is zero or not available, we use a fallback volume of 1.0
    /// so VWAP still tracks the typical price (equal-weighted).
    fn update(&mut self, high: f64, low: f64, close: f64, volume: f64) -> (f64, f64) {
        let tp = (high + low + close) / 3.0;
        let vol = if volume > 0.0 { volume } else { 1.0 };

        self.cumulative_tp_volume += tp * vol;
        self.cumulative_volume += vol;
        self.candle_count += 1;

        let vwap = if self.cumulative_volume > 0.0 {
            self.cumulative_tp_volume / self.cumulative_volume
        } else {
            tp
        };

        let deviation = tp - vwap;
        self.squared_deviation_sum += deviation * deviation * vol;

        let std_dev = if self.cumulative_volume > 0.0 && self.candle_count > 1 {
            (self.squared_deviation_sum / self.cumulative_volume).sqrt()
        } else {
            0.0
        };

        (vwap, std_dev)
    }

    /// Reset for a new session.
    fn reset(&mut self) {
        self.cumulative_tp_volume = 0.0;
        self.cumulative_volume = 0.0;
        self.squared_deviation_sum = 0.0;
        self.candle_count = 0;
    }

    /// Number of candles processed since last reset.
    #[allow(dead_code)]
    fn candle_count(&self) -> usize {
        self.candle_count
    }
}

// ============================================================================
// Volume Analyzer (internal)
// ============================================================================

/// Rolling volume analyzer — detects volume spikes relative to the moving
/// average of recent candle volumes.
#[derive(Debug)]
struct VolumeAnalyzer {
    period: usize,
    volumes: Vec<f64>,
}

impl VolumeAnalyzer {
    fn new(period: usize) -> Self {
        Self {
            period: period.max(1),
            volumes: Vec::with_capacity(period),
        }
    }

    /// Push a new volume value. Returns the multiplier (volume / rolling avg).
    /// Returns 1.0 if there's no history yet.
    fn update(&mut self, volume: f64) -> f64 {
        let avg = self.average();

        self.volumes.push(volume);
        if self.volumes.len() > self.period {
            self.volumes.remove(0);
        }

        if avg > 0.0 { volume / avg } else { 1.0 }
    }

    /// Rolling average volume over the configured period.
    fn average(&self) -> f64 {
        if self.volumes.is_empty() {
            0.0
        } else {
            self.volumes.iter().sum::<f64>() / self.volumes.len() as f64
        }
    }
}

// ============================================================================
// Strategy
// ============================================================================

/// VWAP Scalper Strategy
///
/// Mean-reversion scalping around VWAP bands. Single-asset — instantiate one
/// per symbol.
#[derive(Debug)]
pub struct VwapScalperStrategy {
    config: VwapScalperConfig,

    // Indicators
    vwap: VwapCalculator,
    atr: ATR,
    volume_analyzer: VolumeAnalyzer,

    // Position tracking
    in_position: bool,
    entry_price: Option<f64>,
    entry_side: Option<VwapSignal>,
    stop_loss: Option<f64>,
    take_profit: Option<f64>,

    // Last computed values
    last_vwap: Option<f64>,
    last_std_dev: Option<f64>,
    last_atr: Option<f64>,
    last_signal: VwapSignal,
    candle_count: usize,
}

impl VwapScalperStrategy {
    /// Create a new VWAP Scalper strategy with the given config.
    pub fn new(config: VwapScalperConfig) -> Self {
        let atr = ATR::new(config.atr_period);
        let volume_analyzer = VolumeAnalyzer::new(config.volume_period);

        Self {
            vwap: VwapCalculator::new(),
            atr,
            volume_analyzer,
            config,
            in_position: false,
            entry_price: None,
            entry_side: None,
            stop_loss: None,
            take_profit: None,
            last_vwap: None,
            last_std_dev: None,
            last_atr: None,
            last_signal: VwapSignal::Hold,
            candle_count: 0,
        }
    }

    /// Create with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(VwapScalperConfig::default())
    }

    /// Update the strategy with a `janus-models` Candle.
    pub fn update_candle(&mut self, candle: &janus_models::Candle) -> VwapSignal {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
        .signal
    }

    /// Update the strategy with a `janus-models` Candle and return detailed result.
    pub fn update_candle_with_reason(
        &mut self,
        candle: &janus_models::Candle,
    ) -> VwapScalperResult {
        self.update_ohlcv(
            candle.open,
            candle.high,
            candle.low,
            candle.close,
            candle.volume,
        )
    }

    /// Update with OHLCV values and return detailed result.
    pub fn update_ohlcv(
        &mut self,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
    ) -> VwapScalperResult {
        self.candle_count += 1;

        // Update indicators
        let (vwap, std_dev) = self.vwap.update(high, low, close, volume);
        self.atr.update(high, low, close);
        let vol_mult = self.volume_analyzer.update(volume);

        self.last_vwap = Some(vwap);
        self.last_std_dev = Some(std_dev);
        self.last_atr = self.atr.value();

        // Not ready yet?
        if self.candle_count < self.config.warmup_candles || std_dev <= 0.0 {
            return self.make_result(VwapSignal::Hold, vol_mult, 0.0, "Warming up".to_string());
        }

        let atr_val = match self.atr.value() {
            Some(a) if a > 0.0 => a,
            _ => {
                return self.make_result(
                    VwapSignal::Hold,
                    vol_mult,
                    0.0,
                    "ATR not ready".to_string(),
                );
            }
        };

        let upper_band = vwap + self.config.vwap_std_dev * std_dev;
        let lower_band = vwap - self.config.vwap_std_dev * std_dev;

        // Candle properties
        let body = (close - open).abs();
        let range = high - low;
        let is_bullish = close > open;
        let is_bearish = close < open;
        let body_ratio = if range > 0.0 { body / range } else { 0.0 };
        let upper_wick = high - close.max(open);
        let lower_wick = close.min(open) - low;

        // Check for exit if in position
        if self.in_position
            && let Some(ref side) = self.entry_side
        {
            let exit = self.check_exit(close, vwap, atr_val, side);
            if let Some(exit_signal) = exit {
                self.exit_position();
                return self.make_result(
                    exit_signal,
                    vol_mult,
                    0.8,
                    format!(
                        "VWAP exit: price {:.2} reached target/stop (vwap={:.2})",
                        close, vwap
                    ),
                );
            }
        }

        // Already in position — don't open another
        if self.in_position {
            return self.make_result(VwapSignal::Hold, vol_mult, 0.0, "In position".to_string());
        }

        // === LONG SETUP (Mean Reversion from Lower Band) ===
        if close <= lower_band && is_bullish {
            let deviation = if std_dev > 0.0 {
                (vwap - close) / std_dev
            } else {
                0.0
            };

            let mut confidence = 0.40 + (deviation / 4.0).min(0.30);

            // Volume spike boost
            if vol_mult >= self.config.min_volume_multiplier {
                confidence += 0.10;
            }

            // Pin bar / hammer pattern: long lower wick
            if lower_wick > body * 2.0 {
                confidence += 0.15;
            }

            // Strong body
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.05;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                let stop = close - atr_val * self.config.atr_stop_multiplier;
                let tp = vwap; // Target the mean

                self.enter_position(VwapSignal::Buy, close, stop, tp);
                self.last_signal = VwapSignal::Buy;

                return self.make_result(
                    VwapSignal::Buy,
                    vol_mult,
                    confidence,
                    format!(
                        "VWAP long: price {:.2} at lower band {:.2}, target VWAP {:.2}, dev {:.1}σ, vol {:.1}x",
                        close, lower_band, vwap, deviation, vol_mult
                    ),
                );
            }
        }

        // === SHORT SETUP (Mean Reversion from Upper Band) ===
        if close >= upper_band && is_bearish {
            let deviation = if std_dev > 0.0 {
                (close - vwap) / std_dev
            } else {
                0.0
            };

            let mut confidence = 0.40 + (deviation / 4.0).min(0.30);

            // Volume spike boost
            if vol_mult >= self.config.min_volume_multiplier {
                confidence += 0.10;
            }

            // Shooting star pattern: long upper wick
            if upper_wick > body * 2.0 {
                confidence += 0.15;
            }

            // Strong body
            if body_ratio >= self.config.min_body_ratio {
                confidence += 0.05;
            }

            confidence = confidence.min(1.0);

            if confidence >= self.config.min_confidence {
                let stop = close + atr_val * self.config.atr_stop_multiplier;
                let tp = vwap; // Target the mean

                self.enter_position(VwapSignal::Sell, close, stop, tp);
                self.last_signal = VwapSignal::Sell;

                return self.make_result(
                    VwapSignal::Sell,
                    vol_mult,
                    confidence,
                    format!(
                        "VWAP short: price {:.2} at upper band {:.2}, target VWAP {:.2}, dev {:.1}σ, vol {:.1}x",
                        close, upper_band, vwap, deviation, vol_mult
                    ),
                );
            }
        }

        self.last_signal = VwapSignal::Hold;
        self.make_result(
            VwapSignal::Hold,
            vol_mult,
            0.0,
            format!(
                "No signal: price {:.2}, VWAP {:.2}, bands [{:.2}, {:.2}]",
                close, vwap, lower_band, upper_band
            ),
        )
    }

    /// Update with HLC values (no volume — uses volume=1.0 fallback).
    pub fn update_hlc(&mut self, high: f64, low: f64, close: f64) -> VwapScalperResult {
        self.update_ohlcv(close, high, low, close, 0.0)
    }

    // ========================================================================
    // Regime gating
    // ========================================================================

    /// Check whether this strategy should trade in the given market regime.
    ///
    /// VWAP scalping is mean-reversion around the session average — it works
    /// best when the market oscillates around a stable mean.
    pub fn should_trade_in_regime(regime: &MarketRegime) -> bool {
        matches!(
            regime,
            MarketRegime::MeanReverting | MarketRegime::Uncertain
        )
    }

    /// Compute a confidence-weighted position size factor for the given regime.
    ///
    /// Returns `Some(factor)` if the regime is suitable, `None` otherwise.
    pub fn regime_size_factor(regime: &MarketRegime, confidence: f64) -> Option<f64> {
        match regime {
            MarketRegime::MeanReverting => {
                // Primary regime — full confidence scaling
                Some(confidence.clamp(0.4, 1.0))
            }
            MarketRegime::Uncertain => {
                // May be ranging — allow with reduced size
                Some(if confidence >= 0.5 { 0.30 } else { 0.20 })
            }
            _ => None,
        }
    }

    // ========================================================================
    // Session management
    // ========================================================================

    /// Reset VWAP for a new session. Call this at session boundaries
    /// (e.g. 00:00 UTC for crypto).
    pub fn reset_session(&mut self) {
        self.vwap.reset();
        self.last_vwap = None;
        self.last_std_dev = None;
        // Note: ATR and volume analyzer are NOT reset — they provide
        // cross-session context.
    }

    /// Full reset — clears all state including positions and indicators.
    pub fn reset(&mut self) {
        self.vwap.reset();
        self.atr.reset();
        self.volume_analyzer = VolumeAnalyzer::new(self.config.volume_period);
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
        self.last_vwap = None;
        self.last_std_dev = None;
        self.last_atr = None;
        self.last_signal = VwapSignal::Hold;
        self.candle_count = 0;
    }

    // ========================================================================
    // Position management (internal)
    // ========================================================================

    fn enter_position(&mut self, side: VwapSignal, price: f64, stop: f64, tp: f64) {
        self.in_position = true;
        self.entry_price = Some(price);
        self.entry_side = Some(side);
        self.stop_loss = Some(stop);
        self.take_profit = Some(tp);
    }

    fn check_exit(
        &self,
        price: f64,
        vwap: f64,
        _atr: f64,
        side: &VwapSignal,
    ) -> Option<VwapSignal> {
        let stop = self.stop_loss.unwrap_or(0.0);
        let tp = self.take_profit.unwrap_or(vwap);

        match side {
            VwapSignal::Buy => {
                // Long position: exit at VWAP (TP) or below stop
                if price >= tp || price <= stop {
                    Some(VwapSignal::Sell)
                } else {
                    None
                }
            }
            VwapSignal::Sell => {
                // Short position: exit at VWAP (TP) or above stop
                if price <= tp || price >= stop {
                    Some(VwapSignal::Buy)
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    fn exit_position(&mut self) {
        self.in_position = false;
        self.entry_price = None;
        self.entry_side = None;
        self.stop_loss = None;
        self.take_profit = None;
    }

    fn make_result(
        &self,
        signal: VwapSignal,
        volume_multiplier: f64,
        confidence: f64,
        reason: String,
    ) -> VwapScalperResult {
        let (upper, lower) = match (self.last_vwap, self.last_std_dev) {
            (Some(v), Some(s)) if s > 0.0 => (
                Some(v + self.config.vwap_std_dev * s),
                Some(v - self.config.vwap_std_dev * s),
            ),
            _ => (None, None),
        };

        VwapScalperResult {
            signal,
            vwap: self.last_vwap,
            upper_band: upper,
            lower_band: lower,
            atr: self.last_atr,
            volume_multiplier,
            confidence,
            stop_loss: if signal == VwapSignal::Buy || signal == VwapSignal::Sell {
                self.stop_loss
            } else {
                None
            },
            take_profit: if signal == VwapSignal::Buy || signal == VwapSignal::Sell {
                self.take_profit
            } else {
                None
            },
            reason,
        }
    }

    // ========================================================================
    // Accessors
    // ========================================================================

    /// Whether the strategy has processed enough candles to generate signals.
    pub fn is_ready(&self) -> bool {
        self.candle_count >= self.config.warmup_candles
    }

    /// Whether the strategy currently tracks an open position.
    pub fn is_in_position(&self) -> bool {
        self.in_position
    }

    /// Current VWAP value (if available).
    pub fn last_vwap(&self) -> Option<f64> {
        self.last_vwap
    }

    /// Current VWAP standard deviation (if available).
    pub fn last_std_dev(&self) -> Option<f64> {
        self.last_std_dev
    }

    /// Current ATR value (if available).
    pub fn last_atr(&self) -> Option<f64> {
        self.last_atr
    }

    /// Last signal produced.
    pub fn last_signal(&self) -> VwapSignal {
        self.last_signal
    }

    /// Number of candles processed since creation / last reset.
    pub fn candle_count(&self) -> usize {
        self.candle_count
    }

    /// Entry price of the current position (if any).
    pub fn entry_price(&self) -> Option<f64> {
        self.entry_price
    }

    /// Stop loss of the current position (if any).
    pub fn stop_loss(&self) -> Option<f64> {
        self.stop_loss
    }

    /// Take profit of the current position (if any).
    pub fn take_profit(&self) -> Option<f64> {
        self.take_profit
    }

    /// Reference to the strategy configuration.
    pub fn config(&self) -> &VwapScalperConfig {
        &self.config
    }

    /// Get current VWAP levels: `(vwap, lower_band, upper_band)`.
    pub fn vwap_levels(&self) -> Option<(f64, f64, f64)> {
        match (self.last_vwap, self.last_std_dev) {
            (Some(v), Some(s)) if s > 0.0 => {
                let upper = v + self.config.vwap_std_dev * s;
                let lower = v - self.config.vwap_std_dev * s;
                Some((v, lower, upper))
            }
            _ => None,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use janus_regime::TrendDirection;

    // Helper: warm up the strategy with stable-price candles so it becomes ready.
    fn warm_up(strategy: &mut VwapScalperStrategy, base_price: f64, count: usize) {
        for i in 0..count {
            let noise = (i as f64 * 0.3).sin() * 5.0;
            let close = base_price + noise;
            strategy.update_ohlcv(
                close - 1.0,
                close + 10.0,
                close - 10.0,
                close,
                1000.0 + i as f64 * 10.0,
            );
        }
    }

    // ── Config tests ────────────────────────────────────────────────────

    #[test]
    fn test_default_config() {
        let config = VwapScalperConfig::default();
        assert!((config.vwap_std_dev - 2.0).abs() < f64::EPSILON);
        assert_eq!(config.atr_period, 14);
        assert!((config.atr_stop_multiplier - 1.5).abs() < f64::EPSILON);
        assert_eq!(config.volume_period, 20);
        assert_eq!(config.warmup_candles, 20);
    }

    #[test]
    fn test_crypto_aggressive_config() {
        let config = VwapScalperConfig::crypto_aggressive();
        assert!(config.vwap_std_dev < VwapScalperConfig::default().vwap_std_dev);
        assert!(config.min_confidence <= VwapScalperConfig::default().min_confidence);
    }

    #[test]
    fn test_conservative_config() {
        let config = VwapScalperConfig::conservative();
        assert!(config.vwap_std_dev > VwapScalperConfig::default().vwap_std_dev);
        assert!(config.min_confidence >= VwapScalperConfig::default().min_confidence);
        assert!(config.warmup_candles >= VwapScalperConfig::default().warmup_candles);
    }

    #[test]
    fn test_config_serialization_roundtrip() {
        let config = VwapScalperConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deserialized: VwapScalperConfig = serde_json::from_str(&json).unwrap();
        assert!((deserialized.vwap_std_dev - config.vwap_std_dev).abs() < f64::EPSILON);
        assert_eq!(deserialized.atr_period, config.atr_period);
    }

    // ── Strategy creation ───────────────────────────────────────────────

    #[test]
    fn test_strategy_creation() {
        let strategy = VwapScalperStrategy::with_defaults();
        assert!(!strategy.is_ready());
        assert!(!strategy.is_in_position());
        assert_eq!(strategy.last_signal(), VwapSignal::Hold);
        assert_eq!(strategy.candle_count(), 0);
    }

    #[test]
    fn test_warmup_hold() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        for i in 0..10 {
            let result = strategy.update_ohlcv(100.0, 101.0, 99.0, 100.0, 1000.0 + i as f64);
            assert_eq!(result.signal, VwapSignal::Hold);
        }
        assert!(!strategy.is_ready());
    }

    #[test]
    fn test_becomes_ready_after_warmup() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);
        assert!(strategy.is_ready());
    }

    // ── VWAP calculation ────────────────────────────────────────────────

    #[test]
    fn test_vwap_calculator_basic() {
        let mut vwap = VwapCalculator::new();

        // First candle: VWAP = typical price
        let (v, _s) = vwap.update(102.0, 98.0, 100.0, 1000.0);
        assert!((v - 100.0).abs() < 0.01);

        // Same price, same volume → VWAP stays
        let (v2, _s2) = vwap.update(102.0, 98.0, 100.0, 1000.0);
        assert!((v2 - 100.0).abs() < 0.01);
    }

    #[test]
    fn test_vwap_calculator_weighted() {
        let mut vwap = VwapCalculator::new();

        // Low price with high volume
        let _ = vwap.update(101.0, 99.0, 100.0, 10000.0); // tp = 100.0
        // High price with low volume
        let (v, _) = vwap.update(201.0, 199.0, 200.0, 100.0); // tp = 200.0

        // VWAP should be weighted towards the high-volume candle
        assert!(
            v < 110.0,
            "VWAP {v} should be close to 100 (high-volume candle)"
        );
    }

    #[test]
    fn test_vwap_calculator_reset() {
        let mut vwap = VwapCalculator::new();
        vwap.update(102.0, 98.0, 100.0, 1000.0);
        assert_eq!(vwap.candle_count(), 1);
        vwap.reset();
        assert_eq!(vwap.candle_count(), 0);
    }

    #[test]
    fn test_vwap_zero_volume_fallback() {
        let mut vwap = VwapCalculator::new();
        // Volume = 0 → should use fallback of 1.0, not crash
        let (v, _) = vwap.update(102.0, 98.0, 100.0, 0.0);
        assert!((v - 100.0).abs() < 0.01);
    }

    // ── Volume analyzer ─────────────────────────────────────────────────

    #[test]
    fn test_volume_analyzer_basic() {
        let mut va = VolumeAnalyzer::new(5);
        // First call — no history, returns 1.0
        let mult = va.update(100.0);
        assert!((mult - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_volume_analyzer_spike_detection() {
        let mut va = VolumeAnalyzer::new(5);
        // Fill with normal volume
        for _ in 0..5 {
            va.update(100.0);
        }
        // Spike: 3x normal
        let mult = va.update(300.0);
        assert!(mult > 2.5, "Volume multiplier {mult} should detect spike");
    }

    // ── Signal generation ───────────────────────────────────────────────

    #[test]
    fn test_buy_signal_at_lower_band() {
        let mut strategy = VwapScalperStrategy::new(VwapScalperConfig {
            warmup_candles: 5,
            min_confidence: 0.40,
            vwap_std_dev: 1.5,
            min_body_ratio: 0.3,
            ..Default::default()
        });

        // Warm up with stable prices around 100
        for i in 0..10 {
            strategy.update_ohlcv(100.0, 101.0, 99.0, 100.0, 1000.0 + i as f64);
        }

        // Now drop price significantly below the lower band (bullish candle)
        let result = strategy.update_ohlcv(90.0, 93.0, 88.0, 92.0, 2000.0);

        // Price should be below lower band → may generate Buy
        // Whether it fires depends on exact VWAP/std_dev state, but it shouldn't panic
        assert!(
            result.signal == VwapSignal::Buy || result.signal == VwapSignal::Hold,
            "Signal should be Buy or Hold, got {:?}",
            result.signal
        );
        assert!(!result.reason.is_empty());
    }

    #[test]
    fn test_sell_signal_at_upper_band() {
        let mut strategy = VwapScalperStrategy::new(VwapScalperConfig {
            warmup_candles: 5,
            min_confidence: 0.40,
            vwap_std_dev: 1.5,
            min_body_ratio: 0.3,
            ..Default::default()
        });

        // Warm up with stable prices around 100
        for i in 0..10 {
            strategy.update_ohlcv(100.0, 101.0, 99.0, 100.0, 1000.0 + i as f64);
        }

        // Spike price above upper band (bearish candle: open > close)
        let result = strategy.update_ohlcv(112.0, 114.0, 108.0, 109.0, 2000.0);

        assert!(
            result.signal == VwapSignal::Sell || result.signal == VwapSignal::Hold,
            "Signal should be Sell or Hold, got {:?}",
            result.signal
        );
    }

    #[test]
    fn test_no_signal_in_middle() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);

        // Price right at VWAP → no signal
        let result = strategy.update_ohlcv(50000.0, 50010.0, 49990.0, 50000.0, 1000.0);
        assert_eq!(result.signal, VwapSignal::Hold);
    }

    // ── Position management ─────────────────────────────────────────────

    #[test]
    fn test_not_in_position_initially() {
        let strategy = VwapScalperStrategy::with_defaults();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
        assert!(strategy.stop_loss().is_none());
        assert!(strategy.take_profit().is_none());
    }

    #[test]
    fn test_internal_position_tracking() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        strategy.enter_position(VwapSignal::Buy, 50000.0, 49500.0, 50500.0);

        assert!(strategy.is_in_position());
        assert_eq!(strategy.entry_price(), Some(50000.0));
        assert_eq!(strategy.stop_loss(), Some(49500.0));
        assert_eq!(strategy.take_profit(), Some(50500.0));

        strategy.exit_position();
        assert!(!strategy.is_in_position());
        assert!(strategy.entry_price().is_none());
    }

    // ── Regime gating ───────────────────────────────────────────────────

    #[test]
    fn test_should_trade_in_mean_reverting() {
        assert!(VwapScalperStrategy::should_trade_in_regime(
            &MarketRegime::MeanReverting
        ));
    }

    #[test]
    fn test_should_trade_in_uncertain() {
        assert!(VwapScalperStrategy::should_trade_in_regime(
            &MarketRegime::Uncertain
        ));
    }

    #[test]
    fn test_should_not_trade_in_trending() {
        assert!(!VwapScalperStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bullish)
        ));
        assert!(!VwapScalperStrategy::should_trade_in_regime(
            &MarketRegime::Trending(TrendDirection::Bearish)
        ));
    }

    #[test]
    fn test_should_not_trade_in_volatile() {
        assert!(!VwapScalperStrategy::should_trade_in_regime(
            &MarketRegime::Volatile
        ));
    }

    #[test]
    fn test_regime_size_factor_mean_reverting() {
        let factor = VwapScalperStrategy::regime_size_factor(&MarketRegime::MeanReverting, 0.8);
        assert!(factor.is_some());
        let f = factor.unwrap();
        assert!(
            (0.4..=1.0).contains(&f),
            "Factor {f} should be clamped 0.4–1.0"
        );
    }

    #[test]
    fn test_regime_size_factor_uncertain() {
        let factor = VwapScalperStrategy::regime_size_factor(&MarketRegime::Uncertain, 0.3);
        assert!(factor.is_some());
        let f = factor.unwrap();
        assert!(f > 0.0 && f <= 0.5, "Uncertain factor {f} should be small");
    }

    #[test]
    fn test_regime_size_factor_trending_is_none() {
        let factor = VwapScalperStrategy::regime_size_factor(
            &MarketRegime::Trending(TrendDirection::Bullish),
            0.9,
        );
        assert!(factor.is_none());
    }

    // ── Session management ──────────────────────────────────────────────

    #[test]
    fn test_reset_session() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);
        assert!(strategy.last_vwap().is_some());

        strategy.reset_session();
        assert!(strategy.last_vwap().is_none());
        // ATR should NOT be reset
        assert!(strategy.candle_count() > 0);
    }

    #[test]
    fn test_full_reset() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        warm_up(&mut strategy, 50000.0, 25);
        assert!(strategy.is_ready());

        strategy.reset();
        assert!(!strategy.is_ready());
        assert_eq!(strategy.candle_count(), 0);
        assert!(!strategy.is_in_position());
    }

    // ── Signal display ──────────────────────────────────────────────────

    #[test]
    fn test_signal_display() {
        assert_eq!(format!("{}", VwapSignal::Buy), "BUY");
        assert_eq!(format!("{}", VwapSignal::Sell), "SELL");
        assert_eq!(format!("{}", VwapSignal::Hold), "HOLD");
    }

    #[test]
    fn test_signal_serialization() {
        let json = serde_json::to_string(&VwapSignal::Buy).unwrap();
        let deserialized: VwapSignal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, VwapSignal::Buy);
    }

    // ── HLC interface ───────────────────────────────────────────────────

    #[test]
    fn test_hlc_interface() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        // Should not panic even without volume
        for _ in 0..25 {
            let result = strategy.update_hlc(50010.0, 49990.0, 50000.0);
            assert!(
                result.signal == VwapSignal::Hold
                    || result.signal == VwapSignal::Buy
                    || result.signal == VwapSignal::Sell
            );
        }
        assert!(strategy.is_ready());
    }

    // ── VWAP levels accessor ────────────────────────────────────────────

    #[test]
    fn test_vwap_levels() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        assert!(strategy.vwap_levels().is_none());

        warm_up(&mut strategy, 50000.0, 25);

        if let Some((vwap, lower, upper)) = strategy.vwap_levels() {
            assert!(lower < vwap, "Lower band should be below VWAP");
            assert!(upper > vwap, "Upper band should be above VWAP");
            assert!(
                (upper - vwap - (vwap - lower)).abs() < 1.0,
                "Bands should be symmetric"
            );
        }
    }

    // ── Stress test ─────────────────────────────────────────────────────

    #[test]
    fn test_many_candles_no_panic() {
        let mut strategy = VwapScalperStrategy::new(VwapScalperConfig::crypto_aggressive());
        let mut buy_count = 0u32;
        let mut sell_count = 0u32;

        for i in 0..1000 {
            let base = 50000.0 + (i as f64 * 0.1).sin() * 500.0;
            let vol = 1000.0 + (i as f64 * 0.05).cos().abs() * 3000.0;
            let result = strategy.update_ohlcv(
                base - 5.0,
                base + 20.0,
                base - 20.0,
                base + 5.0 * (i as f64 * 0.2).sin(),
                vol,
            );
            match result.signal {
                VwapSignal::Buy => buy_count += 1,
                VwapSignal::Sell => sell_count += 1,
                VwapSignal::Hold => {}
            }
        }

        assert_eq!(strategy.candle_count(), 1000);
        println!(
            "Stress test: {} buys, {} sells out of 1000 candles",
            buy_count, sell_count
        );
    }

    #[test]
    fn test_result_reason_populated() {
        let mut strategy = VwapScalperStrategy::with_defaults();
        let result = strategy.update_ohlcv(100.0, 101.0, 99.0, 100.0, 1000.0);
        assert!(
            !result.reason.is_empty(),
            "Reason should always be populated"
        );
    }

    // ── Config accessor ─────────────────────────────────────────────────

    #[test]
    fn test_config_accessor() {
        let config = VwapScalperConfig::conservative();
        let strategy = VwapScalperStrategy::new(config.clone());
        assert!((strategy.config().vwap_std_dev - config.vwap_std_dev).abs() < f64::EPSILON);
        assert_eq!(strategy.config().atr_period, config.atr_period);
    }
}
