//! Backtesting module for trading signal validation.
//!
//! This module provides comprehensive backtesting utilities to validate
//! trading signals generated by the vision pipeline on historical data.
//!
//! # Overview
//!
//! The backtesting pipeline consists of:
//! 1. **Historical Simulation** → Replay signals on past data
//! 2. **Trade Tracking** → Record entries, exits, and P&L
//! 3. **Performance Metrics** → Calculate Sharpe, win rate, drawdown, etc.
//! 4. **Signal Analysis** → Validate signal quality and accuracy
//!
//! # Architecture
//!
//! ```text
//! Historical Data → Signals → Simulation → Trades → Metrics
//!      ✓              ✓          ✓           ✓         ✓
//! ```
//!
//! # Quick Start
//!
//! ```rust,ignore
//! use vision::backtest::*;
//! use vision::signals::*;
//!
//! // 1. Configure simulation
//! let config = SimulationConfig {
//!     initial_capital: 10000.0,
//!     commission_rate: 0.001,
//!     slippage_rate: 0.0005,
//!     position_size: PositionSizing::FixedPercent(0.1),
//!     ..Default::default()
//! };
//!
//! // 2. Create simulator
//! let mut sim = BacktestSimulation::new(config);
//!
//! // 3. Run backtest on signals
//! for signal in signals {
//!     sim.process_signal(&signal, current_price);
//! }
//!
//! // 4. Get performance metrics
//! let metrics = sim.calculate_metrics();
//! println!("Sharpe Ratio: {:.2}", metrics.sharpe_ratio);
//! println!("Win Rate: {:.2}%", metrics.win_rate * 100.0);
//! ```
//!
//! # Features
//!
//! - **Realistic Simulation**: Includes commissions, slippage, and realistic fills
//! - **Multiple Position Sizing**: Fixed percent, Kelly criterion, volatility-based
//! - **Comprehensive Metrics**: Sharpe, Sortino, win rate, profit factor, drawdown
//! - **Trade Analysis**: Individual trade tracking and performance breakdown
//! - **Signal Quality**: Confidence calibration and prediction accuracy
//! - **Risk Metrics**: Maximum drawdown, value at risk, exposure analysis
//!
//! # Position Sizing Strategies
//!
//! ```rust,ignore
//! // Fixed percentage of capital
//! PositionSizing::FixedPercent(0.1) // 10% per trade
//!
//! // Kelly Criterion (optimal growth)
//! PositionSizing::Kelly { win_rate: 0.6, avg_win_loss_ratio: 1.5 }
//!
//! // Volatility-based (risk parity)
//! PositionSizing::VolatilityBased { target_volatility: 0.02 }
//!
//! // Fixed dollar amount
//! PositionSizing::FixedDollar(1000.0)
//! ```

pub mod metrics;
pub mod simulation;
pub mod trade;

// Re-exports for convenience
pub use metrics::{MetricsCalculator, PerformanceMetrics, RiskMetrics, SignalQuality, TradeStats};
pub use simulation::{BacktestSimulation, PositionSizing, SimulationConfig, SimulationState};
pub use trade::{Position, Trade, TradeResult, TradeStatus};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_module_exports() {
        // Verify all main types are accessible
        let _config = SimulationConfig::default();
    }
}
